### ISSUE TITLE
Local install of Eleventy throws date error due to tests packaged in node_modules

### ISSUE THREAD

**Issue by mschmidty** [11ty/eleventy#1073]
**Describe the bug**
I can't get eleventy to work if I install it locally and not globally. It gives me a date front matter error.  I don't have any dates in any front matter in any .md documents (or any other file). 

**To Reproduce**
I locally installed eleventy into a project. 
```
npm init -y
npm install --save-dev @11ty/eleventy
npx @11ty/eleventy
```

It throws an error: 
```
npx @11ty/eleventy                                                                              ~/Dropbox/web_dev/side_projects/bird_id_trainer
Problem writing Eleventy templates: (more in DEBUG output)
> date front matter value (2019-03-13 20:18:42 +0000) is invalid for ./node_modules/@11ty/eleventy/test/stubs-413/date-frontmatter.md

`Error` was thrown:
    Error: date front matter value (2019-03-13 20:18:42 +0000) is invalid for ./node_modules/@11ty/eleventy/test/stubs-413/date-frontmatter.md
        at Template.getMappedDate (/Users/mschmidty/Dropbox/web_dev/side_projects/bird_id_trainer/node_modules/@11ty/eleventy/src/Template.js:626:19)
        at async Template.addPageDate (/Users/mschmidty/Dropbox/web_dev/side_projects/bird_id_trainer/node_modules/@11ty/eleventy/src/Template.js:257:19)
        at async Template.getData (/Users/mschmidty/Dropbox/web_dev/side_projects/bird_id_trainer/node_modules/@11ty/eleventy/src/Template.js:238:20)
        at async Template.getTemplateMapEntries (/Users/mschmidty/Dropbox/web_dev/side_projects/bird_id_trainer/node_modules/@11ty/eleventy/src/Template.js:681:16)
        at async TemplateMap.add (/Users/mschmidty/Dropbox/web_dev/side_projects/bird_id_trainer/node_modules/@11ty/eleventy/src/TemplateMap.js:32:21)
        at async Promise.all (index 881)
        at async TemplateWriter._createTemplateMap (/Users/mschmidty/Dropbox/web_dev/side_projects/bird_id_trainer/node_modules/@11ty/eleventy/src/TemplateWriter.js:132:5)
        at async TemplateWriter.write (/Users/mschmidty/Dropbox/web_dev/side_projects/bird_id_trainer/node_modules/@11ty/eleventy/src/TemplateWriter.js:168:5)
        at async Eleventy.write (/Users/mschmidty/Dropbox/web_dev/side_projects/bird_id_trainer/node_modules/@11ty/eleventy/src/Eleventy.js:659:13)
Copied 35 items / Wrote 0 files in 5.85 seconds (v0.10.0)
```
It looks like the eleventy tests are throwing an error?

**Expected behavior**
When I run eleventy globally by deleting `node_modules` folder and package.json and running:
```
eleventy --serve
```
everything works. 

**Environment:**

- OS and Version: macOS 10.15.2
- Eleventy Version: 0.10.0
- NPM version - 6.13.4
- Node version - v13.4.0

Thanks,

**Comment by Ryuno-Ki** [comment]
Yupp, that's a problem with `2019-03-13 20:18:42 +0000`. See #413 and #573 as example.
`2019-03-13 20:18:42 +00:00` (with colon in offset) should work.

**Comment by mschmidty** [comment]
But the date problem is in the node_module/tests.  Do I just need to change it?

**Comment by Ryuno-Ki** [comment]
Funny, that this is part of the package :o
@zachleat Could you adjust the [files property of package.json](https://docs.npmjs.com/files/package.json#files), so it only packages to npm, what's actually needed?

(Perhaps worth editing the issue title, too).

@mschmidty If you just want to have it run locally, yeah, that should do it.

**Comment by mschmidty** [comment]
I edited the title. Is that better? Do you mean I have it run globally? Until stuff gets updated?  Thanks for your help!!!! Really appreciate it Ryuno-Ki

**Comment by stevenpetryk** [comment]
`.npmignore` is already set up to ignore `test` 🤔 

https://github.com/11ty/eleventy/blob/8ffbb9927ea8482c5a46515f3a2ed25cd8830ad8/.npmignore#L3

**Comment by stevenpetryk** [comment]
Ah, so that file's not released in 0.10, meaning this should be fixed in 0.11 and in fact is already fixed in `0.11.0-beta.3`.

**Comment by Ryuno-Ki** [comment]
Ah, so in this case, no edit necessary. Instead `npm install @11ty/eleventy@beta` to get the latest beta version, @mschmidty.

**Comment by Ryuno-Ki** [comment]
Thanks for the debugging, @stevenpetryk :-)

**Comment by mschmidty** [comment]
Thanks y'all.  I'll close this issue since it is already fixed in the next release.
