### ISSUE TITLE
npm install fails on Debian sid, "Cannot set property 'prev' of null"

### ISSUE THREAD

**Issue by pde** [11ty/eleventy#1108]
This is with on Debian sid, with `npm 6.14.4+ds-1`:

```
$ npm install @11ty/eleventy --save-dev
npm ERR! Cannot set property 'prev' of null

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pde/.npm/_logs/2020-04-21T12_52_07_544Z-debug.log
```

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   '@11ty/eleventy',
1 verbose cli   '--save-dev' ]
2 info using npm@6.14.4
3 info using node@v10.16.3
4 verbose npm-session 80a995dec58ec744
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/@11ty%2feleventy 1697ms (from cache)
8 verbose stack TypeError: Cannot set property 'prev' of null
8 verbose stack     at Yallist.shift (/usr/lib/nodejs/yallist/yallist.js:135:18)
8 verbose stack     at Object.[nextEntry] (/usr/lib/nodejs/tar/lib/parse.js:178:49)
8 verbose stack     at Object.[consumeHeader] (/usr/lib/nodejs/tar/lib/parse.js:148:30)
8 verbose stack     at Object.[consumeChunkSub] (/usr/lib/nodejs/tar/lib/parse.js:385:30)
8 verbose stack     at Object.[consumeChunk] (/usr/lib/nodejs/tar/lib/parse.js:362:30)
8 verbose stack     at Unzip.(anonymous function).on.chunk (/usr/lib/nodejs/tar/lib/parse.js:291:59)
8 verbose stack     at Unzip.emit (events.js:198:13)
8 verbose stack     at Unzip.emit (/usr/lib/nodejs/tar/node_modules/minipass/index.js:309:30)
8 verbose stack     at Unzip.write (/usr/lib/nodejs/tar/node_modules/minipass/index.js:104:17)
8 verbose stack     at Unzip.write (/usr/lib/nodejs/tar/node_modules/minizlib/index.js:284:29)
8 verbose stack     at Object.write (/usr/lib/nodejs/tar/lib/parse.js:299:58)
8 verbose stack     at PassThrough.ondata (_stream_readable.js:709:20)
8 verbose stack     at PassThrough.emit (events.js:198:13)
8 verbose stack     at addChunk (_stream_readable.js:288:12)
8 verbose stack     at readableAddChunk (_stream_readable.js:269:11)
8 verbose stack     at PassThrough.Readable.push (_stream_readable.js:224:10)
9 verbose cwd /home/pde/eleventy
10 verbose Linux 5.4.0-2-amd64
11 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "@11ty/eleventy" "--save-dev"
12 verbose node v10.16.3
13 verbose npm  v6.14.4
14 error Cannot set property 'prev' of null
15 verbose exit [ 1, true ]
```

**Comment by pde** [comment]
Upgrading all of debian's (many!) npm dependencies, and then also npm upgrading core-js@3, fixed this...
