### ISSUE TITLE
eleventy --serve fails after trying to connect to 127.0.0.1:80

### ISSUE THREAD

**Issue by chrismademe** [11ty/eleventy#1121]
**Describe the bug**
This is a weird one, at first this only happened on my Window machine, after running once and then restarting the process. Now it just happened on my Mac, the first time I tried to run `eleventy --serve`.

**To Reproduce**

1. Clone 'https://github.com/chrismademe/11ty-starter-kit'
2. `npm install`
3. `npm run dev`
4. See error (sometimes)

**Expected behavior**
11ty should start a dev server and Gulp will watch for Sass changes.

**Log**
```bash
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/Cellar/node/13.7.0/bin/node',
1 verbose cli   '/usr/local/lib/node_modules/npm/bin/npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'serve'
1 verbose cli ]
2 info using npm@6.14.3
3 info using node@v13.7.0
4 verbose run-script [ 'preserve', 'serve', 'postserve' ]
5 info lifecycle 11ty-starter@1.0.0~preserve: 11ty-starter@1.0.0
6 info lifecycle 11ty-starter@1.0.0~serve: 11ty-starter@1.0.0
7 verbose lifecycle 11ty-starter@1.0.0~serve: unsafe-perm in lifecycle true
8 verbose lifecycle 11ty-starter@1.0.0~serve: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/chris/www/sites/moomoo-mortgages/site/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/chris/www/sites/moomoo-mortgages/site/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle 11ty-starter@1.0.0~serve: CWD: /Users/chris/www/sites/moomoo-mortgages/site
10 silly lifecycle 11ty-starter@1.0.0~serve: Args: [ '-c', 'eleventy --serve' ]
11 silly lifecycle 11ty-starter@1.0.0~serve: Returned: code: 1  signal: null
12 info lifecycle 11ty-starter@1.0.0~serve: Failed to exec serve script
13 verbose stack Error: 11ty-starter@1.0.0 serve: `eleventy --serve`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:321:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:321:20)
13 verbose stack     at maybeClose (internal/child_process.js:1026:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid 11ty-starter@1.0.0
15 verbose cwd /Users/chris/www/sites/moomoo-mortgages/site
16 verbose Darwin 19.3.0
17 verbose argv "/usr/local/Cellar/node/13.7.0/bin/node" "/usr/local/lib/node_modules/npm/bin/npm-cli.js" "run" "serve"
18 verbose node v13.7.0
19 verbose npm  v6.14.3
20 error code ELIFECYCLE
21 error errno 1
22 error 11ty-starter@1.0.0 serve: `eleventy --serve`
22 error Exit status 1
23 error Failed at the 11ty-starter@1.0.0 serve script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Environment:**

- OS and Version: MacOS Catalina 10.15.3
- Eleventy Version 0.10.0

**Comment by chrismademe** [comment]
Well, this is embarressing - I'm pulling data from a local WordPress installation and it wasn't on All sorted 🙃
