### ISSUE TITLE
Using the same input and output does not work (always "Wrote 0 files")

### ISSUE THREAD

**Issue by stuartpb** [11ty/eleventy#1129]
## Describe the bug

[The documentation](https://www.11ty.dev/docs/usage/#using-the-same-input-and-output) states "Yes, you can use the same input and output directories, like so: `npx @11ty/eleventy --input=. --output=. --formats=md`"

However, in practice, running that command always results in a `Wrote 0 files` result. Eleventy appears to be [blacklisting its output directory from input matching](https://github.com/11ty/eleventy/blob/82d83f55b92624b7b307c3814c80c7f83b264d7f/src/EleventyFiles.js#L288), causing all attempts to output to the input directory (or any ancestor of the input directory) to match 0 files.

See the output of the command when `DEBUG=Eleventy:EleventyFiles` is set:

```
  Eleventy:EleventyFiles Searching for: [ './**/*.md', '!./node_modules/**', '!./**', '!./_includes/**', '!./_data/**' ] 
```

Note the `'!./**`(which matches the position of `!./_site/**` when run with default options), effectively negating all of the preceding glob patterns.

**Comment by cekvenich** [comment]
I have the same bug, it is blocking.

**Comment by cekvenich** [comment]
The patch did not fix the bug.  
Wrote 0 files in 0.02 seconds (v1.0.0-beta.0)
with
  dir: {
            input:  "webApp",
            output: "webApp"
          }

How to reproduce. I installed eleventy from github via npm -g and ran with above return and not Wrote 0 files.

**Comment by stuartpb** [comment]
Hmm, I'm pretty sure this patch worked in my environment - from what I recall, I used the patched version to render my wedding website.

Do the files write if you change the output directory to something else, eg. "build"?

What is your operating system and Node version?

**Comment by cekvenich** [comment]
@stuartpb Yes it does work if the folders are different.
Linux and node 14.10

**Comment by stuartpb** [comment]
I'm not sure why that wouldn't work with the patch in #1133: that should evaluate to a check of `"webApp".startsWith("webApp")`, which would suppress the exclusion.

What does `DEBUG=Eleventy:EleventyFiles npx @11ty/eleventy` output?

**Comment by cekvenich** [comment]
@stuartpb Output:

vic@vic-OptiPlex-7020:/media/vic/dat/Github2/11webApp/src$  DEBUG=Eleventy:EleventyFiles npx @11ty/eleventy 
  Eleventy:EleventyFiles /media/vic/dat/Github2/11webApp/src/.gitignore ignoring: !./node_modules/** +0ms
  Eleventy:EleventyFiles /media/vic/dat/Github2/11webApp/src/.gitignore ignoring: !/media/vic/dat/Github2/11webApp/src/node_modules/** +1ms
  Eleventy:EleventyFiles Searching for: [ './**/*.liquid', './**/*.ejs', './**/*.md', './**/*.hbs', './**/*.mustache', './**/*.haml', './**/*.pug', './**/*.njk', './**/*.html', './**/*.11ty.js', './**/*.11ty.cjs', '!./node_modules/**', '!/media/vic/dat/Github2/11webApp/src/node_modules/**', '!./_site/**', '!./_includes/**', '!./_data/**' ] +10ms
Wrote 8 files in 0.29 seconds (v1.0.0-beta.0)


Start time: (2020-09-25 00:20:36 UTC) [treshold=1%]
  #  module                                           time  %
  1  ./src/EleventyErrorHan...ventyErrorHandler.js)   10ms  ▇ 2%
  2  parse-filepath (../../...se-filepath/index.js)    9ms  ▇ 1%
  3  ./TemplatePath (../../.../src/TemplatePath.js)   11ms  ▇ 2%
  4  ./fs (../../../../../....xtra/lib/fs/index.js)    7ms  ▇ 1%
  5  fs-extra (../../../../...s-extra/lib/index.js)   32ms  ▇▇▇ 5%
  6  braces (../../../../.....ules/braces/index.js)    7ms  ▇ 1%
  7  micromatch (../../../..../micromatch/index.js)   14ms  ▇ 2%
  8  ./pattern (../../../.....out/utils/pattern.js)   17ms  ▇▇ 3%
  9  ../utils (../../../../...b/out/utils/index.js)   22ms  ▇▇ 3%
 10  ./managers/tasks (../....ut/managers/tasks.js)   22ms  ▇▇ 3%
 11  @nodelib/fs.scandir (....scandir/out/index.js)    8ms  ▇ 1%
 12  ../readers/async (../....out/readers/async.js)   12ms  ▇ 2%
 13  ./providers/async (../...t/providers/async.js)   13ms  ▇ 2%
 14  @nodelib/fs.walk (../....fs.walk/out/index.js)   18ms  ▇▇ 3%
 15  ../readers/stream (../...ut/readers/stream.js)   22ms  ▇▇ 3%
 16  ./provider (../../../....roviders/provider.js)    7ms  ▇ 1%
 17  ./providers/async (../...t/providers/async.js)   30ms  ▇▇▇ 5%
 18  ./settings (../../../....glob/out/settings.js)   20ms  ▇▇ 3%
 19  fast-glob (../../../.....st-glob/out/index.js)   75ms  ▇▇▇▇▇▇ 12%
 20  ./_baseIsNative (../.....ash/_baseIsNative.js)    7ms  ▇ 1%
 21  ./_getNative (../../.....lodash/_getNative.js)    8ms  ▇ 1%
 22  ./_defineProperty (../...h/_defineProperty.js)    9ms  ▇ 1%
 23  ./_baseAssignValue (...../_baseAssignValue.js)    9ms  ▇ 1%
 24  ./_assignValue (../../...dash/_assignValue.js)   10ms  ▇ 2%
 25  ./_mapCacheClear (../....sh/_mapCacheClear.js)    7ms  ▇ 1%
 26  ./_MapCache (../../../.../lodash/_MapCache.js)   10ms  ▇ 2%
 27  ./memoize (../../../.....es/lodash/memoize.js)   10ms  ▇ 2%
 28  ./_memoizeCapped (../....sh/_memoizeCapped.js)   11ms  ▇ 2%
 29  ./_stringToPath (../.....ash/_stringToPath.js)   11ms  ▇ 2%
 30  ./_castPath (../../../.../lodash/_castPath.js)   16ms  ▇▇ 2%
 31  ./_baseSet (../../../....s/lodash/_baseSet.js)   28ms  ▇▇ 4%
 32  lodash/set (../../../....odules/lodash/set.js)   30ms  ▇▇▇ 5%
 33  lodash/uniq (../../../...dules/lodash/uniq.js)    7ms  ▇ 1%
 34  ./_baseMergeDeep (../....sh/_baseMergeDeep.js)   12ms  ▇ 2%
 35  ./_baseMerge (../../.....lodash/_baseMerge.js)   17ms  ▇▇ 3%
 36  lodash/merge (../../.....ules/lodash/merge.js)   22ms  ▇▇ 3%
 37  semver (../../../../.....ules/semver/index.js)   22ms  ▇▇ 3%
 38  luxon (../../../../../.../build/node/luxon.js)    7ms  ▇ 1%
 39  ./UserConfig (../../.....ty/src/UserConfig.js)   34ms  ▇▇▇ 5%
 40  ./EleventyConfig (../....rc/EleventyConfig.js)   34ms  ▇▇▇ 5%
 41  ./TemplateConfig (../....rc/TemplateConfig.js)   58ms  ▇▇▇▇▇ 9%
 42  ./Config (../../../../...eventy/src/Config.js)   65ms  ▇▇▇▇▇ 10%
 43  ./TemplateEngineManage...lateEngineManager.js)   66ms  ▇▇▇▇▇ 10%
 44  ./EleventyExtensionMap...ventyExtensionMap.js)   66ms  ▇▇▇▇▇ 10%
 45  ./TemplateRender (../....rc/TemplateRender.js)   67ms  ▇▇▇▇▇ 10%
 46  ./TemplateData (../../.../src/TemplateData.js)  216ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 33%
 47  ./json (../../../../.....-yaml/schema/json.js)    7ms  ▇ 1%
 48  ./core (../../../../.....-yaml/schema/core.js)    7ms  ▇ 1%
 49  ./schema/default_safe...hema/default_safe.js)    12ms  ▇ 2%
 50  esprima (../../../../....rima/dist/esprima.js)    9ms  ▇ 1%
 51  ../type/js/function (..../type/js/function.js)    9ms  ▇ 1%
 52  ./schema/default_full...hema/default_full.js)    11ms  ▇ 2%
 53  ./js-yaml/loader (../....ib/js-yaml/loader.js)   27ms  ▇▇ 4%
 54  ./lib/js-yaml.js (../....-yaml/lib/js-yaml.js)   28ms  ▇▇ 4%
 55  js-yaml (../../../../....les/js-yaml/index.js)   29ms  ▇▇▇ 4%
 56  ./engines (../../../.....atter/lib/engines.js)   30ms  ▇▇▇ 5%
 57  ./lib/defaults (../../...tter/lib/defaults.js)   32ms  ▇▇▇ 5%
 58  gray-matter (../../../...gray-matter/index.js)   39ms  ▇▇▇ 6%
 59  ./TemplateContent (../...c/TemplateContent.js)   40ms  ▇▇▇ 6%
 60  ./Template (../../../....enty/src/Template.js)   11ms  ▇ 2%
 61  multimatch (../../../..../multimatch/index.js)    8ms  ▇ 1%
 62  ./TemplateCollection (...emplateCollection.js)   10ms  ▇ 2%
 63  ./TemplateMap (../../....y/src/TemplateMap.js)   10ms  ▇ 2%
 64  glob (../../../../../....modules/glob/glob.js)   10ms  ▇ 2%
 65  globby (../../../../.....ules/globby/index.js)   18ms  ▇▇ 3%
 66  del (../../../../../.....modules/del/index.js)   23ms  ▇▇ 4%
 67  ./lib/copy (../../../....ive-copy/lib/copy.js)   37ms  ▇▇▇ 6%
 68  recursive-copy (../../...ursive-copy/index.js)   38ms  ▇▇▇ 6%
 69  ./TemplatePassthrough...mplatePassthrough.js)    38ms  ▇▇▇ 6%
 70  ./TemplatePassthroughM...assthroughManager.js)   39ms  ▇▇▇ 6%
 71  ./EleventyFiles (../.....src/EleventyFiles.js)   40ms  ▇▇▇ 6%
 72  ./TemplateWriter (../....rc/TemplateWriter.js)   61ms  ▇▇▇▇▇ 9%
 73  ./src/Eleventy (../../...enty/src/Eleventy.js)  332ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 51%
 74  ./common/utils (../../.../lib/common/utils.js)   18ms  ▇▇ 3%
 75  ./parser_block (../../.../lib/parser_block.js)   10ms  ▇ 2%
 76  ./parser_inline (../.....lib/parser_inline.js)    9ms  ▇ 1%
 77  ./lib/ (../../../../.....down-it/lib/index.js)   51ms  ▇▇▇▇ 8%
 78  markdown-it (../../../...markdown-it/index.js)   53ms  ▇▇▇▇ 8%
 79  ./Engines/Markdown (...../Engines/Markdown.js)   53ms  ▇▇▇▇ 8%
 80  acorn (../../../../../.../acorn/dist/acorn.js)    7ms  ▇ 1%
 81  is-expression (../../....-expression/index.js)    8ms  ▇ 1%
 82  pug-lexer (../../../.....s/pug-lexer/index.js)   14ms  ▇ 2%
 83  jstransformer (../../....transformer/index.js)    8ms  ▇ 1%
 84  ./lib/run-filter (../....rs/lib/run-filter.js)   13ms  ▇ 2%
 85  @babel/parser (../../..../parser/lib/index.js)   10ms  ▇ 2%
 86  ./_baseClone (../../.....lodash/_baseClone.js)   12ms  ▇ 2%
 87  lodash/clone (../../.....ules/lodash/clone.js)   12ms  ▇ 2%
 88  ./core (../../../../...../definitions/core.js)   12ms  ▇ 2%
 89  ../definitions (../../...definitions/index.js)   20ms  ▇▇ 3%
 90  ../builder (../../../..../builders/builder.js)   32ms  ▇▇▇ 5%
 91  ../../builders/generat...s/generated/index.js)   36ms  ▇▇▇ 6%
 92  ../../utils/react/clea...ementLiteralChild.js)   37ms  ▇▇▇ 6%
 93  ./builders/react/build...act/buildChildren.js)   39ms  ▇▇▇ 6%
 94  @babel/types (../../.....l/types/lib/index.js)   84ms  ▇▇▇▇▇▇ 13%
 95  constantinople (../../...tinople/lib/index.js)   96ms  ▇▇▇▇▇▇▇ 15%
 96  ./lib/handle-filters (...ib/handle-filters.js)   97ms  ▇▇▇▇▇▇▇ 15%
 97  pug-filters (../../../...pug-filters/index.js)  111ms  ▇▇▇▇▇▇▇▇ 17%
 98  pug-code-gen (../../.....ug-code-gen/index.js)   14ms  ▇ 2%
 99  pug (../../../../../.....les/pug/lib/index.js)  147ms  ▇▇▇▇▇▇▇▇▇▇▇ 23%
100  ./Engines/Pug (../../....y/src/Engines/Pug.js)  147ms  ▇▇▇▇▇▇▇▇▇▇▇ 23%
Total require(): 1507
Total time: 648ms
vic@vic-OptiPlex-7020:/media/vic/dat/Github2/11webApp/src$

**Comment by stuartpb** [comment]
You have to write three backticks around it (<code>```</code>) so GitHub knows not to parse it as Markdown.

**Comment by stuartpb** [comment]
> Wrote 8 files in 0.29 seconds (v1.0.0-beta.0)

Wouldn't that mean it's working?

**Comment by cekvenich** [comment]
@stuartpb It wrote in in src/_site that time with setting of 
```
 dir: {
            input:  "src",
            output: "src"
          }
```
What I need is not in src/_site but in src.
So that I have assets in the same folder as the 'output'.

**Comment by stuartpb** [comment]
Sounds like it used the default `output` directory. Are you sure you ran the command with that configuration?

**Comment by cekvenich** [comment]
3 commands:
```
vic@vic-OptiPlex-7020:/media/vic/dat/Github2/11webApp/src$ eleventy --input=src --output=src?
Wrote 0 files in 0.02 seconds (v1.0.0-beta.0)

vic@vic-OptiPlex-7020:/media/vic/dat/Github2/11webApp/src$ eleventy
Writing _site/aintro/index.html from ./aintro.md.
Writing _site/index.html from ./index.pug.
Writing _site/monthly/index.html from ./monthly.md.
Writing _site/day/index.html from ./day.md.
Writing _site/qtr/index.html from ./qtr.md.
Writing _site/yearly/index.html from ./yearly.md.
Writing _site/zar_hire/index.html from ./zar_hire.md.
Writing _site/zar_leave/index.html from ./zar_leave.md.
Wrote 8 files in 0.19 seconds (v1.0.0-beta.0)

vic@vic-OptiPlex-7020:/media/vic/dat/Github2/11webApp/src$ npx @11ty/eleventy --input=src --output=src
Wrote 0 files in 0.02 seconds (v1.0.0-beta.0)
vic@vic-OptiPlex-7020:/media/vic/dat/Github2/11webApp/src$ 

```

**Comment by stuartpb** [comment]
>```
>vic@vic-OptiPlex-7020:/media/vic/dat/Github2/11webApp/src$ eleventy --input=src --output=src?
>```

Are you sure you get the same output for `eleventy --input=src --output=src` (without the `?` at the end)?

**Comment by zachleat** [comment]
Thanks!

**Comment by tito-arch** [comment]
2022 still I cant solve this

**Comment by tito-arch** [comment]
`animu5@animu5:~/Documents/GitHub/1bunnieabc-blog$ npm start

> 1bunnieabc-blog@1.0.0 start
> eleventy --serve

[11ty] Problem writing Eleventy templates: (more in DEBUG output)
[11ty] TemplateLayoutPathResolver directory does not exist for base.njk: _includes (via Error)
[11ty] 
[11ty] Original error stack trace: Error: TemplateLayoutPathResolver directory does not exist for base.njk: _includes
[11ty]     at TemplateLayoutPathResolver.findFileName (/home/animu5/Documents/GitHub/1bunnieabc-blog/node_modules/@11ty/eleventy/src/TemplateLayoutPathResolver.js:105:13)
[11ty]     at TemplateLayoutPathResolver.init (/home/animu5/Documents/GitHub/1bunnieabc-blog/node_modules/@11ty/eleventy/src/TemplateLayoutPathResolver.js:72:28)
[11ty]     at new TemplateLayoutPathResolver (/home/animu5/Documents/GitHub/1bunnieabc-blog/node_modules/@11ty/eleventy/src/TemplateLayoutPathResolver.js:25:10)
[11ty]     at new TemplateLayout (/home/animu5/Documents/GitHub/1bunnieabc-blog/node_modules/@11ty/eleventy/src/TemplateLayout.js:17:24)
[11ty]     at Function.getTemplate (/home/animu5/Documents/GitHub/1bunnieabc-blog/node_modules/@11ty/eleventy/src/TemplateLayout.js:47:18)
[11ty]     at Template.getLayout (/home/animu5/Documents/GitHub/1bunnieabc-blog/node_modules/@11ty/eleventy/src/Template.js:132:37)
[11ty]     at Template.getData (/home/animu5/Documents/GitHub/1bunnieabc-blog/node_modules/@11ty/eleventy/src/Template.js:417:27)
[11ty]     at async Template.getTemplateMapEntries (/home/animu5/Documents/GitHub/1bunnieabc-blog/node_modules/@11ty/eleventy/src/Template.js:1087:33)
[11ty]     at async TemplateMap.add (/home/animu5/Documents/GitHub/1bunnieabc-blog/node_modules/@11ty/eleventy/src/TemplateMap.js:59:21)
[11ty]     at async Promise.all (index 2)
[11ty] Wrote 0 files in 1.13 seconds (v1.0.1)
animu5@animu5:~/Documents/GitHub/1bunnieabc-blog$ ^C
animu5@animu5:~/Documents/GitHub/1bunnieabc-blog$ npx @11ty/eleventy --input=src --output=src
[11ty] Writing src/blog/2021-05-28-my-third-article/index.html from ./src/blog/2021-05-28-my-third-article.md (liquid)
[11ty] Writing src/blog/2021-05-01-my-first-article/index.html from ./src/blog/2021-05-01-my-first-article.md (liquid)
[11ty] Writing src/blog/2021-06-01-my-fourth-article/index.html from ./src/blog/2021-06-01-my-fourth-article.md (liquid)
[11ty] Writing src/blog/2021-06-15-my-fifth-article/index.html from ./src/blog/2021-06-15-my-fifth-article.md (liquid)
[11ty] Writing src/blog/2021-05-15-my-second-article/index.html from ./src/blog/2021-05-15-my-second-article.md (liquid)
[11ty] Writing src/all-articles/index.html from ./src/all-articles.html (liquid)
[11ty] Writing src/individual-article/index.html from ./src/individual-article.html (liquid)
[11ty] Writing src/index.html from ./src/index.njk
[11ty] Wrote 8 files in 0.11 seconds (v1.0.1)
animu5@animu5:~/Documents/GitHub/1bunnieabc-blog$ npm start

> 1bunnieabc-blog@1.0.0 start
> eleventy --serve

[11ty] Problem writing Eleventy templates: (more in DEBUG output)
[11ty] TemplateLayoutPathResolver directory does not exist for base.njk: _includes (via Error)
[11ty] 
[11ty] Original error stack trace: Error: TemplateLayoutPathResolver directory does not exist for base.njk: _includes
[11ty]     at TemplateLayoutPathResolver.findFileName (/home/animu5/Documents/GitHub/1bunnieabc-blog/node_modules/@11ty/eleventy/src/TemplateLayoutPathResolver.js:105:13)
[11ty]     at TemplateLayoutPathResolver.init (/home/animu5/Documents/GitHub/1bunnieabc-blog/node_modules/@11ty/eleventy/src/TemplateLayoutPathResolver.js:72:28)
[11ty]     at new TemplateLayoutPathResolver (/home/animu5/Documents/GitHub/1bunnieabc-blog/node_modules/@11ty/eleventy/src/TemplateLayoutPathResolver.js:25:10)
[11ty]     at new TemplateLayout (/home/animu5/Documents/GitHub/1bunnieabc-blog/node_modules/@11ty/eleventy/src/TemplateLayout.js:17:24)
[11ty]     at Function.getTemplate (/home/animu5/Documents/GitHub/1bunnieabc-blog/node_modules/@11ty/eleventy/src/TemplateLayout.js:47:18)
[11ty]     at Template.getLayout (/home/animu5/Documents/GitHub/1bunnieabc-blog/node_modules/@11ty/eleventy/src/Template.js:132:37)
[11ty]     at Template.getData (/home/animu5/Documents/GitHub/1bunnieabc-blog/node_modules/@11ty/eleventy/src/Template.js:417:27)
[11ty]     at async Template.getTemplateMapEntries (/home/animu5/Documents/GitHub/1bunnieabc-blog/node_modules/@11ty/eleventy/src/Template.js:1087:33)
[11ty]     at async TemplateMap.add (/home/animu5/Documents/GitHub/1bunnieabc-blog/node_modules/@11ty/eleventy/src/TemplateMap.js:59:21)
[11ty]     at async Promise.all (index 3)
[11ty] Wrote 0 files in 0.08 seconds (v1.0.1)
animu5@animu5:~/Documents/GitHub/1bunnieabc-blog$ npx @11ty/eleventy --input=src --output=public
[11ty] Problem writing Eleventy templates: (more in DEBUG output)
[11ty] Output conflict: multiple input files are writing to `public/blog/2021-05-01-my-first-article/index.html`. Use distinct `permalink` values to resolve this conflict.
[11ty]   1. ./src/blog/2021-05-01-my-first-article/index.html
[11ty]   2. ./src/blog/2021-05-01-my-first-article.md (via DuplicatePermalinkOutputError)
[11ty] 
[11ty] Original error stack trace: (Repeated output has been truncated…)
[11ty]     at TemplateMap.checkForDuplicatePermalinks (/home/animu5/Documents/GitHub/1bunnieabc-blog/node_modules/@11ty/eleventy/src/TemplateMap.js:656:13)
[11ty]     at TemplateMap.cache (/home/animu5/Documents/GitHub/1bunnieabc-blog/node_modules/@11ty/eleventy/src/TemplateMap.js:365:10)
[11ty]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[11ty]     at async TemplateWriter._createTemplateMap (/home/animu5/Documents/GitHub/1bunnieabc-blog/node_modules/@11ty/eleventy/src/TemplateWriter.js:244:5)
[11ty]     at async TemplateWriter.generateTemplates (/home/animu5/Documents/GitHub/1bunnieabc-blog/node_modules/@11ty/eleventy/src/TemplateWriter.js:277:5)
[11ty]     at async TemplateWriter.write (/home/animu5/Documents/GitHub/1bunnieabc-blog/node_modules/@11ty/eleventy/src/TemplateWriter.js:323:23)
[11ty]     at async Eleventy.executeBuild (/home/animu5/Documents/GitHub/1bunnieabc-blog/node_modules/@11ty/eleventy/src/Eleventy.js:1003:13)
[11ty] Wrote 0 files in 0.12 seconds (v1.0.1)
animu5@animu5:~/Documents/GitHub/1bunnieabc-blog$ npx @11ty/eleventy --input=src --output=src
[11ty] Writing src/blog/2021-05-01-my-first-article/index.html from ./src/blog/2021-05-01-my-first-article.md (liquid)
[11ty] Writing src/blog/2021-05-15-my-second-article/index.html from ./src/blog/2021-05-15-my-second-article.md (liquid)
[11ty] Writing src/blog/2021-05-28-my-third-article/index.html from ./src/blog/2021-05-28-my-third-article.md (liquid)
[11ty] Writing src/blog/2021-06-01-my-fourth-article/index.html from ./src/blog/2021-06-01-my-fourth-article.md (liquid)
[11ty] Writing src/blog/2021-06-15-my-fifth-article/index.html from ./src/blog/2021-06-15-my-fifth-article.md (liquid)
[11ty] Writing src/blog/2021-05-01-my-first-article/index-o.html from ./src/blog/2021-05-01-my-first-article/index.html (liquid)
[11ty] Writing src/blog/2021-05-15-my-second-article/index-o.html from ./src/blog/2021-05-15-my-second-article/index.html (liquid)
[11ty] Writing src/blog/2021-06-15-my-fifth-article/index-o.html from ./src/blog/2021-06-15-my-fifth-article/index.html (liquid)
[11ty] Writing src/blog/2021-06-01-my-fourth-article/index-o.html from ./src/blog/2021-06-01-my-fourth-article/index.html (liquid)
[11ty] Writing src/blog/2021-05-28-my-third-article/index-o.html from ./src/blog/2021-05-28-my-third-article/index.html (liquid)
[11ty] Writing src/all-articles/index.html from ./src/all-articles.html (liquid)
[11ty] Writing src/index-o.html from ./src/index.html (liquid)
[11ty] Writing src/individual-article/index.html from ./src/individual-article.html (liquid)
[11ty] Writing src/all-articles/index-o.html from ./src/all-articles/index.html (liquid)
[11ty] Writing src/individual-article/index-o.html from ./src/individual-article/index.html (liquid)
[11ty] Writing src/index.html from ./src/index.njk
[11ty] Wrote 16 files in 0.13 seconds (8.1ms each, v1.0.1)
animu5@animu5:~/Documents/GitHub/1bunnieabc-blog$ npm start

> 1bunnieabc-blog@1.0.0 start
> eleventy --serve

[11ty] Problem writing Eleventy templates: (more in DEBUG output)
[11ty] TemplateLayoutPathResolver directory does not exist for base.njk: _includes (via Error)
[11ty] 
[11ty] Original error stack trace: Error: TemplateLayoutPathResolver directory does not exist for base.njk: _includes
[11ty]     at TemplateLayoutPathResolver.findFileName (/home/animu5/Documents/GitHub/1bunnieabc-blog/node_modules/@11ty/eleventy/src/TemplateLayoutPathResolver.js:105:13)
[11ty]     at TemplateLayoutPathResolver.init (/home/animu5/Documents/GitHub/1bunnieabc-blog/node_modules/@11ty/eleventy/src/TemplateLayoutPathResolver.js:72:28)
[11ty]     at new TemplateLayoutPathResolver (/home/animu5/Documents/GitHub/1bunnieabc-blog/node_modules/@11ty/eleventy/src/TemplateLayoutPathResolver.js:25:10)
[11ty]     at new TemplateLayout (/home/animu5/Documents/GitHub/1bunnieabc-blog/node_modules/@11ty/eleventy/src/TemplateLayout.js:17:24)
[11ty]     at Function.getTemplate (/home/animu5/Documents/GitHub/1bunnieabc-blog/node_modules/@11ty/eleventy/src/TemplateLayout.js:47:18)
[11ty]     at Template.getLayout (/home/animu5/Documents/GitHub/1bunnieabc-blog/node_modules/@11ty/eleventy/src/Template.js:132:37)
[11ty]     at Template.getData (/home/animu5/Documents/GitHub/1bunnieabc-blog/node_modules/@11ty/eleventy/src/Template.js:417:27)
[11ty]     at async Template.getTemplateMapEntries (/home/animu5/Documents/GitHub/1bunnieabc-blog/node_modules/@11ty/eleventy/src/Template.js:1087:33)
[11ty]     at async TemplateMap.add (/home/animu5/Documents/GitHub/1bunnieabc-blog/node_modules/@11ty/eleventy/src/TemplateMap.js:59:21)
[11ty]     at async Promise.all (index 4)
[11ty] Wrote 0 files in 0.12 seconds (v1.0.1)
animu5@animu5:~/Documents/GitHub/1bunnieabc-blog$ npx @11ty/eleventy --input=src --output=src
[11ty] Writing src/blog/2021-05-01-my-first-article/index.html from ./src/blog/2021-05-01-my-first-article.md (liquid)
[11ty] Writing src/blog/2021-05-15-my-second-article/index.html from ./src/blog/2021-05-15-my-second-article.md (liquid)
[11ty] Writing src/blog/2021-05-28-my-third-article/index.html from ./src/blog/2021-05-28-my-third-article.md (liquid)
[11ty] Writing src/blog/2021-06-01-my-fourth-article/index.html from ./src/blog/2021-06-01-my-fourth-article.md (liquid)
[11ty] Writing src/blog/2021-06-15-my-fifth-article/index.html from ./src/blog/2021-06-15-my-fifth-article.md (liquid)
[11ty] Writing src/blog/2021-05-01-my-first-article/index-o/index.html from ./src/blog/2021-05-01-my-first-article/index-o.html (liquid)
[11ty] Writing src/blog/2021-05-01-my-first-article/index-o.html from ./src/blog/2021-05-01-my-first-article/index.html (liquid)
[11ty] Writing src/blog/2021-05-15-my-second-article/index-o/index.html from ./src/blog/2021-05-15-my-second-article/index-o.html (liquid)
[11ty] Writing src/blog/2021-05-15-my-second-article/index-o.html from ./src/blog/2021-05-15-my-second-article/index.html (liquid)
[11ty] Writing src/blog/2021-05-28-my-third-article/index-o/index.html from ./src/blog/2021-05-28-my-third-article/index-o.html (liquid)
[11ty] Writing src/blog/2021-05-28-my-third-article/index-o.html from ./src/blog/2021-05-28-my-third-article/index.html (liquid)
[11ty] Writing src/blog/2021-06-01-my-fourth-article/index-o/index.html from ./src/blog/2021-06-01-my-fourth-article/index-o.html (liquid)
[11ty] Writing src/blog/2021-06-01-my-fourth-article/index-o.html from ./src/blog/2021-06-01-my-fourth-article/index.html (liquid)
[11ty] Writing src/blog/2021-06-15-my-fifth-article/index-o/index.html from ./src/blog/2021-06-15-my-fifth-article/index-o.html (liquid)
[11ty] Writing src/blog/2021-06-15-my-fifth-article/index-o.html from ./src/blog/2021-06-15-my-fifth-article/index.html (liquid)
[11ty] Writing src/all-articles/index.html from ./src/all-articles.html (liquid)
[11ty] Writing src/index-o/index.html from ./src/index-o.html (liquid)
[11ty] Writing src/index-o.html from ./src/index.html (liquid)
[11ty] Writing src/individual-article/index.html from ./src/individual-article.html (liquid)
[11ty] Writing src/all-articles/index-o/index.html from ./src/all-articles/index-o.html (liquid)
[11ty] Writing src/all-articles/index-o.html from ./src/all-articles/index.html (liquid)
[11ty] Writing src/individual-article/index-o/index.html from ./src/individual-article/index-o.html (liquid)
[11ty] Writing src/individual-article/index-o.html from ./src/individual-article/index.html (liquid)
[11ty] Writing src/index.html from ./src/index.njk
[11ty] Wrote 24 files in 0.14 seconds (5.8ms each, v1.0.1)`
