### ISSUE TITLE
YAMLException: can not read a block mapping entry; a multiline key may not be an implicit key

### ISSUE THREAD

**Issue by davidrhoden** [11ty/eleventy#1156]
I'm getting this error repeatedly, and I'm not sure how to read the debug output so I can squash it.
I tried removing line breaks from my front matter, and checked that the tags were formatted correctly.

It doesn't seem to happen on the same file every time. Here's one example:

``` Eleventy:Template getMappedDate: using a date in the data for './pages/web.md' of 2020-04-12T00:00:00.000Z +1ms
  Eleventy:Template getMappedDate: YAML parsed it: 2020-04-12T00:00:00.000Z +0ms
  Eleventy:TemplateWriter ./pages/web.md added to map. +1ms
  Eleventy:Template getMappedDate: using a date in the data for './pages/press.md' of 2020-05-02T00:00:00.000Z +5ms
  Eleventy:Template getMappedDate: YAML parsed it: 2020-05-02T00:00:00.000Z +8ms
  Eleventy:TemplateWriter ./pages/press.md added to map. +13ms
  Eleventy:EleventyErrorHandler Problem writing Eleventy templates: +2m
  Eleventy:EleventyErrorHandler can not read a block mapping entry; a multiline key may not be an implicit key at line 6, column 5:
  Eleventy:EleventyErrorHandler     tags:
  Eleventy:EleventyErrorHandler         ^
  Eleventy:EleventyErrorHandler 
  Eleventy:EleventyErrorHandler `YAMLException` was thrown: +0ms
  Eleventy:EleventyErrorHandler (error stack): YAMLException: can not read a block mapping entry; a multiline key may not be an implicit key at line 6, column 5:
  Eleventy:EleventyErrorHandler     tags:
  Eleventy:EleventyErrorHandler         ^
  Eleventy:EleventyErrorHandler     at generateError (/Users/davidrhoden/Sites/davidrhoden-basic-netlify/node_modules/js-yaml/lib/js-yaml/loader.js:167:10)
  Eleventy:EleventyErrorHandler     at throwError (/Users/davidrhoden/Sites/davidrhoden-basic-netlify/node_modules/js-yaml/lib/js-yaml/loader.js:173:9)
  Eleventy:EleventyErrorHandler     at readBlockMapping (/Users/davidrhoden/Sites/davidrhoden-basic-netlify/node_modules/js-yaml/lib/js-yaml/loader.js:1073:9)
  Eleventy:EleventyErrorHandler     at composeNode (/Users/davidrhoden/Sites/davidrhoden-basic-netlify/node_modules/js-yaml/lib/js-yaml/loader.js:1359:12)
  Eleventy:EleventyErrorHandler     at readDocument (/Users/davidrhoden/Sites/davidrhoden-basic-netlify/node_modules/js-yaml/lib/js-yaml/loader.js:1519:3)
  Eleventy:EleventyErrorHandler     at loadDocuments (/Users/davidrhoden/Sites/davidrhoden-basic-netlify/node_modules/js-yaml/lib/js-yaml/loader.js:1575:5)
  Eleventy:EleventyErrorHandler     at load (/Users/davidrhoden/Sites/davidrhoden-basic-netlify/node_modules/js-yaml/lib/js-yaml/loader.js:1596:19)
  Eleventy:EleventyErrorHandler     at Object.safeLoad (/Users/davidrhoden/Sites/davidrhoden-basic-netlify/node_modules/js-yaml/lib/js-yaml/loader.js:1618:10)
  Eleventy:EleventyErrorHandler     at module.exports (/Users/davidrhoden/Sites/davidrhoden-basic-netlify/node_modules/gray-matter/lib/parse.js:12:17)
  Eleventy:EleventyErrorHandler     at parseMatter (/Users/davidrhoden/Sites/davidrhoden-basic-netlify/node_modules/gray-matter/index.js:109:17) +1ms
Wrote 0 files in 0.62 seconds (v0.11.0-beta.3)
  Eleventy Finished writing templates. +604ms```

The site is hosted on Netlify.
https://github.com/davidrhoden/davidrhoden-basic-netlify
https://davidrhoden.com

**Comment by davidrhoden** [comment]
I was able to make this stop by cleaning up my front matter, there was a hard-to-see indent in a page summary. If this is helpful for anyone, great, but feel free to remove.

**Comment by nicknoop** [comment]
Thanks David,
For me I had the front matter, for example,
`title: 'Too Long, Didn't Read'`
Because I had the title wrapped in single ' this caused issue with the apostrophe, rewriting as `title: "Too Long, Didn't Read"` with the double " works fine.

**Comment by rahxuls** [comment]
Haha. Faced it too.

**Comment by lucasnantonio** [comment]
Got stuck on the same thing, but since it doesn't specify which file is broken, I can't debug it...any tips for finding the right file?
```
lucasn@tw-mbp-lucasn notes-11y % npx eleventy --serve
Problem writing Eleventy templates: (more in DEBUG output)
> can not read a block mapping entry; a multiline key may not be an implicit key at line 4, column 1:
    
    ^

`YAMLException` was thrown:
    YAMLException: can not read a block mapping entry; a multiline key may not be an implicit key at line 4, column 1:
        
        ^
        at generateError (/Users/lucasn/Code/notes-11y/node_modules/js-yaml/lib/js-yaml/loader.js:167:10)
        at throwError (/Users/lucasn/Code/notes-11y/node_modules/js-yaml/lib/js-yaml/loader.js:173:9)
        at readBlockMapping (/Users/lucasn/Code/notes-11y/node_modules/js-yaml/lib/js-yaml/loader.js:1073:9)
        at composeNode (/Users/lucasn/Code/notes-11y/node_modules/js-yaml/lib/js-yaml/loader.js:1359:12)
        at readDocument (/Users/lucasn/Code/notes-11y/node_modules/js-yaml/lib/js-yaml/loader.js:1525:3)
        at loadDocuments (/Users/lucasn/Code/notes-11y/node_modules/js-yaml/lib/js-yaml/loader.js:1588:5)
        at load (/Users/lucasn/Code/notes-11y/node_modules/js-yaml/lib/js-yaml/loader.js:1614:19)
        at Object.safeLoad (/Users/lucasn/Code/notes-11y/node_modules/js-yaml/lib/js-yaml/loader.js:1637:10)
        at module.exports (/Users/lucasn/Code/notes-11y/node_modules/gray-matter/lib/parse.js:12:17)
        at parseMatter (/Users/lucasn/Code/notes-11y/node_modules/gray-matter/index.js:109:17)
```

**Comment by davidrhoden** [comment]
@lucasnantonio : I've found that it's often little mistakes in front matter, like too many spaces before the `---` that indicates the start of the front matter. I can't say how to debug it, but look for a file you edited around the time the problem started.

**Comment by lucasnantonio** [comment]
Yeah I'm looking, unfortunately I have hundreds of posts. They're more like personal notes so I edit many a day. Ideally, eleventy would point at the file that is causing trouble in the log...

**Comment by pdehaan** [comment]
@lucasnantonio If you have a public repo, I can take a look.

**Comment by xplosionmind** [comment]
I am having the following issue. How can I possibly fix the invalid YAML front matter if the file where it is wrong is not specified?

Is this an Eleventy bug or my problem?

```
npx @11ty/eleventy --serve
Problem writing Eleventy templates: (more in DEBUG output)
> duplicated mapping key at line 7, column 1:
    tags: geek
    ^

`YAMLException` was thrown:
    YAMLException: duplicated mapping key at line 7, column 1:
        tags: geek
        ^
        at generateError (/Users/tommi/tommi.space/node_modules/js-yaml/lib/js-yaml/loader.js:167:10)
        at throwError (/Users/tommi/tommi.space/node_modules/js-yaml/lib/js-yaml/loader.js:173:9)
        at storeMappingPair (/Users/tommi/tommi.space/node_modules/js-yaml/lib/js-yaml/loader.js:335:7)
        at readBlockMapping (/Users/tommi/tommi.space/node_modules/js-yaml/lib/js-yaml/loader.js:1098:9)
        at composeNode (/Users/tommi/tommi.space/node_modules/js-yaml/lib/js-yaml/loader.js:1359:12)
        at readDocument (/Users/tommi/tommi.space/node_modules/js-yaml/lib/js-yaml/loader.js:1525:3)
        at loadDocuments (/Users/tommi/tommi.space/node_modules/js-yaml/lib/js-yaml/loader.js:1588:5)
        at load (/Users/tommi/tommi.space/node_modules/js-yaml/lib/js-yaml/loader.js:1614:19)
        at Object.safeLoad (/Users/tommi/tommi.space/node_modules/js-yaml/lib/js-yaml/loader.js:1637:10)
        at module.exports (/Users/tommi/tommi.space/node_modules/gray-matter/lib/parse.js:12:17)
Wrote 0 files in 0.87 seconds (v0.12.1)
Benchmark (Watch): Start up --watch took 611ms
Benchmark (Watch): Watching JavaScript Dependencies (disable with `eleventyConfig.setWatchJavaScriptDependencies(false)`) took 507ms
Watching…
[Browsersync] Access URLs:
 ---------------------------------------
       Local: http://localhost:8080
    External: http://157.138.176.63:8080
 ---------------------------------------
          UI: http://localhost:3001
 UI External: http://localhost:3001
 ---------------------------------------
[Browsersync] Serving files from: _site
```

**Comment by pdehaan** [comment]
@xplosionmind Not the exact answer you want, but you might be able to find files w/ multiple "tags: geek" strings using some classy grep commands:

```sh
# count all instances of "tags: geek" in each file, then ignore files with only one instance.
git grep -Ec "tags: geek$" . | grep -Ev ":1$"
```

I tried the command in your https://github.com/xplosionmind/tommi.space repo, but that doesn't look like an Eleventy blog and didn't see any duplicate tags (but happy to help you troubleshoot if you want to push a repo somewhere).

**Comment by xplosionmind** [comment]
Thank you very much, @pdehaan, you have been very kind. That was a question I posed because I was still trying to figure out Eleventy locally. I now opened [a new branch](https://github.com/xplosionmind/tommi.space/tree/11ty '“11ty” branch of tommi.space on GitHub'), which is still broken, but for other problems, and I am working on it.

Thanks again.

Best,
Tommi

**Comment by Cais** [comment]
> @davidrhoden @lucasnantonio got burned by this too. the way I found to help me figure out which files are problematic is by editing the installed dependency `js-yaml` in `node_modules/` to print out the contents of the files so it is easy to discover which have an issue.
> 
> Specifically, I made the following change in `node_modules/js-yaml/lib/js-yaml/loader.js` line 166, function `generateError(state, message)` and added a `console.log(state.input)` to help me figure things out.
> 
> Hope it helps you 🙏🏼

Thank you very much for this idea. It did help with finding where I broke my install.

**Comment by OGreeni** [comment]
[nicknoop](https://github.com/nicknoop) Thanks for that, this was my exact issue and I completely overlooked it.

**Comment by jamienorthman** [comment]
I got this error because I had too many spaces and the spaces were being confused for possible keys in the markdown files. An oversight from copying and pasting text into markdown files. Removed spaces and problem solved!
