### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by DanCanetti** [11ty/eleventy#1180]
Since the 0.11.0 update I've been having the below issue when trying to render templates and I'm not sure what the cause is, any help would be appreciated.

```
> Having trouble rendering liquid (and markdown) template ./node_modules/decode-uri-component/readme.md

`TemplateContentRenderError` was thrown
> Having trouble compiling template ./node_modules/decode-uri-component/readme.md

`TemplateContentCompileError` was thrown
> tag ab not found, file:./node_modules/decode-uri-component/readme.md, line:44

`ParseError` was thrown
> tag ab not found

`AssertionError` was thrown:
    AssertionError: tag ab not found
        at assert (/usr/local/lib/node_modules/@11ty/eleventy/node_modules/liquidjs/dist/liquid.common.js:1062:11)
        at Object.parse (/usr/local/lib/node_modules/@11ty/eleventy/node_modules/liquidjs/dist/liquid.common.js:1873:7)
        at Object.construct (/usr/local/lib/node_modules/@11ty/eleventy/node_modules/liquidjs/dist/liquid.common.js:1887:14)
        at parseTag (/usr/local/lib/node_modules/@11ty/eleventy/node_modules/liquidjs/dist/liquid.common.js:2037:16)
        at parseToken (/usr/local/lib/node_modules/@11ty/eleventy/node_modules/liquidjs/dist/liquid.common.js:2021:15)
        at Object.parse (/usr/local/lib/node_modules/@11ty/eleventy/node_modules/liquidjs/dist/liquid.common.js:2012:22)
        at Object.parse$$1 [as parse] (/usr/local/lib/node_modules/@11ty/eleventy/node_modules/liquidjs/dist/liquid.common.js:3420:24)
        at Liquid.compile (/usr/local/lib/node_modules/@11ty/eleventy/src/Engines/Liquid.js:181:29)
        at Markdown.compile (/usr/local/lib/node_modules/@11ty/eleventy/src/Engines/Markdown.js:63:25)
        at TemplateRender.getCompiledTemplate (/usr/local/lib/node_modules/@11ty/eleventy/src/TemplateRender.js:192:26)
```
To make sure that I haven't done anything to break it on another 11ty site I've created a new site from scratch and I'm still having this issue. Hopefully it's just something simple I'm missing.

**Comment by DanCanetti** [comment]
Ah! I was having a conflict with the global package. Uninstalling the local package has worked for me.
