### ISSUE TITLE
Include creation date in the post permalink

### ISSUE THREAD

**Issue by hughbagan** [11ty/eleventy#1202]
**Describe the bug**
I'm trying to make my posts include their date of creation in the permalink. Here is my `posts.json`:
```
{
  "layout": "layouts/post.njk",
  "permalink": "posts/{{ page.date | date: '%Y%m%d%H%M%S' }}/index.html",
  "tags": [
    "posts"
  ]
}
```
For example: `site.com/posts/20200519210258` would be the URL for a post created on May 19 2020 at 21:02:58.

For each post, the YAML looks like this:
```
---
tags:
  - music
---
```
Of course, this is making use of [Eleventy's default setting for `page.date` to be the date of creation.](https://www.11ty.dev/docs/dates/)

This works just fine when I'm doing `eleventy --serve` on my local machine. But when I push it and run a Github Action to build it for Github Pages, it causes a duplicate permalink error:

```
> hughbagan.ca@4.2.0 build /home/runner/work/hughbagan.ca/hughbagan.ca
> eleventy

Problem writing Eleventy templates: (more in DEBUG output)
> Output conflict: multiple input files are writing to `_site/posts/20200521212345/index.html`. Use distinct `permalink` values to resolve this conflict.
  1. ./posts/lifeparty.md
  2. ./posts/greenonions.md
  3. ./posts/hothand.md

`DuplicatePermalinkOutputError` was thrown:
    (Repeated output has been truncated…)
        at TemplateMap.checkForDuplicatePermalinks (/home/runner/work/hughbagan.ca/hughbagan.ca/node_modules/@11ty/eleventy/src/TemplateMap.js:533:13)
        at TemplateMap.cache (/home/runner/work/hughbagan.ca/hughbagan.ca/node_modules/@11ty/eleventy/src/TemplateMap.js:306:10)
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:189:7)
Benchmark (Configuration): "htmlDateString" Nunjucks Filter took 298ms (41.6%)
Copied 2 items / Wrote 0 files in 0.58 seconds (v0.10.0)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hughbagan.ca@4.2.0 build: `eleventy`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hughbagan.ca@4.2.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2020-05-21T21_24_03_771Z-debug.log
##[error]Process completed with exit code 1.
```
[This is the Github workflow that I'm using to publish the site to Github Pages.](https://github.com/hughbagan/hughbagan.ca/blob/c52f96d1e5b5c6556e35315547a5199122d87c6e/.github/workflows/eleventy_build.yml)

It seems to me that the posts' creation date is just whenever eleventy builds the site. Doesn't this defeat the purpose of having a creation date? Except it works perfectly when served locally. 

**To Reproduce**
[Here is the repository and commit.](https://github.com/hughbagan/hughbagan.ca/tree/c52f96d1e5b5c6556e35315547a5199122d87c6e) If you serve it locally, `eleventy --serve`, it will build the site just fine. 

**Expected behavior**
I would like a way to include a date in the post permalink, down to the minute and second. If I can't do this, then I would be ok with Unix time. I've seen [others use unix time](https://hankchizljaw.com/wrote/jamstack-ifttt-and-netlify:-a-power-trio/) in the permalink, but I don't know how to do it. 

**Environment:**

- OS and Version: Pop!_OS 20.04 (Ubuntu)
- Eleventy Version: 0.11.0
- Deployment: Github Pages

Thank you very much for any insight you could give.

**Comment by hughbagan** [comment]
I decided to try something instead of keep waiting. My solution is to specify the exact date on each post in its YAML. Here's an example:
```
---
slug: green-onions
date: 2020-05-19 20:56:17 -6
tags:
  - music
---
```
And the posts's url is [`_site/posts/20200520025617/green-onions/`](https://www.hughbagan.ca/posts/20200520025617/green-onions/).

And this is my `posts.json`:
```
{
  "layout": "layouts/post.njk",
  "permalink": "posts/{{ page.date | date: '%Y%m%d%H%M%S' }}/{{ slug }}/index.html",
  "tags": [
    "posts"
  ]
}
```
Note: it's important to specify the `-6`, since that's my timezone. If the timezone isn't specified, 11ty will assume and display it in UTC.

This method requires me to type some YAML on every post, but I suppose that's something I'll just have to live with. It would be nice to have a post-editing page that pulls the current date automatically, like [this one by Andy Bell.](https://post.hankchizljaw.com/)

References:
- https://www.11ty.dev/docs/dates/
- https://www.11ty.dev/docs/dates/#collections-out-of-order-when-you-run-eleventy-on-your-server
- https://yaml.org/type/timestamp.html
- My blog is based on [eleventy-base-blog](https://github.com/11ty/eleventy-base-blog)
