### ISSUE TITLE
Problems writing templates

### ISSUE THREAD

**Issue by alexcarpenter** [11ty/eleventy#132]
Updated to `0.3.5` and started getting this error 

```
> alexcarpenter-me@4.0.0 build:files /Users/mighty/personal/alexcarpenter.github.io
> eleventy --config config/eleventy.config.js --quiet


Problem writing eleventy templates:
Error: TemplateLayout directory does not exist for layouts/index: ./_includes
    at TemplateLayout.findFileName (/Users/mighty/personal/alexcarpenter.github.io/node_modules/@11ty/eleventy/src/TemplateLayout.js:74:11)
    at TemplateLayout.init (/Users/mighty/personal/alexcarpenter.github.io/node_modules/@11ty/eleventy/src/TemplateLayout.js:39:26)
    at new TemplateLayout (/Users/mighty/personal/alexcarpenter.github.io/node_modules/@11ty/eleventy/src/TemplateLayout.js:13:8)
    at Template.getLayoutTemplateFilePath (/Users/mighty/personal/alexcarpenter.github.io/node_modules/@11ty/eleventy/src/Template.js:189:12)
    at Template.getAllLayoutFrontMatterData (/Users/mighty/personal/alexcarpenter.github.io/node_modules/@11ty/eleventy/src/Template.js:212:33)
    at Template.getData (/Users/mighty/personal/alexcarpenter.github.io/node_modules/@11ty/eleventy/src/Template.js:273:41)
    at <anonymous>
```

It doesn't seem to be working off of custom config setting?

```
alexcarpenter.github.io git:master ❯ eleventy --config config/eleventy.config.js                                                           ✹ ✭
Writing _site/src/_includes/components/footer/index.html from ./src/_includes/components/footer.liquid

Problem writing eleventy templates:
 * Error: Having trouble writing template: ./src/_includes/components/header.liquid
 * RenderError: ENOENT: Failed to lookup 'components/navigation.liquid' in: _includes, line:6
Error: Having trouble writing template: ./src/_includes/components/header.liquid
    at TemplateWriter._writeTemplate (/usr/local/lib/node_modules/eleventy-cli/src/TemplateWriter.js:145:7)
    at <anonymous>
{    4|     <span>Front-end Web Developer</span>
   5|   </div>
>> 6|   {%- include 'components/navigation.liquid' -%}
   7| </header>
   8|
RenderError
    at renderTemplate.call.then.catch.e (/usr/local/lib/node_modules/eleventy-cli/node_modules/liquidjs/src/render.js:22:17)
    at <anonymous>
From Error: ENOENT: Failed to lookup 'components/navigation.liquid' in: _includes
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: '/Users/mighty/personal/alexcarpenter.github.io/_includes/\'components/navigation.liquid\'',
  originalError:
   { Error: ENOENT: Failed to lookup 'components/navigation.liquid' in: _includes
     errno: -2,
     code: 'ENOENT',
     syscall: 'stat',
     path: '/Users/mighty/personal/alexcarpenter.github.io/_includes/\'components/navigation.liquid\'' },
  name: 'RenderError',
  input: '<header class="c-header">\n  <div class="c-header__lockup">\n    <a rel="home" href="/">Alex Carpenter</a>\n    <span>Front-end Web Developer</span>\n  </div>\n  {%- include \'components/navigation.liquid\' -%}\n</header>\n',
  line: 6,
  file: undefined,
  message: 'ENOENT: Failed to lookup \'components/navigation.liquid\' in: _includes, line:6' }

undefined
Wrote 1 file in 7.67 seconds
```

**Comment by zachleat** [comment]
Shouldn’t it be `eleventy --config=config/eleventy.config.js --quiet`?

**Comment by alexcarpenter** [comment]
That still doesn't seem to be picking up the custom config. The path is missing `src` before the `_includes`

`path: '/Users/mighty/personal/alexcarpenter.github.io/_includes/\'components/navigation.liquid\'',`

**Comment by zachleat** [comment]
Hmm, this worked for me. I PR’d changes to https://github.com/alexcarpenter/alexcarpenter.me/pull/34

**Comment by zachleat** [comment]
Great! I’ve reopened #127.
