### ISSUE TITLE
Error writing template when upgrade to 0.11 from 0.10

### ISSUE THREAD

**Issue by jalberto** [11ty/eleventy#1347]
**Describe the bug**

Upgrading from 0.10 to 0.11 adn build as usual give sme this error

```
  Eleventy:EleventyErrorHandler Error writing templates: +0ms                                                                                                                
  Eleventy:EleventyErrorHandler Having trouble writing template: ./site/index.html                                                                                           
  Eleventy:EleventyErrorHandler                                                                                                                                              
  Eleventy:EleventyErrorHandler `TemplateWriterWriteError` was thrown +0ms                                                                                                   
  Eleventy:EleventyErrorHandler (error stack): TemplateWriterWriteError: Having trouble writing template: ./site/index.html                                                  
  Eleventy:EleventyErrorHandler     at /home/ja/Project/VL/landing/node_modules/@11ty/eleventy/src/TemplateWriter.js:216:15                                                  
  Eleventy:EleventyErrorHandler     at async Promise.all (index 3)                                                                                                           
  Eleventy:EleventyErrorHandler     at async Eleventy.write (/home/ja/Project/VL/landing/node_modules/@11ty/eleventy/src/Eleventy.js:741:13)                                 
  Eleventy:EleventyErrorHandler     at async Eleventy.watch (/home/ja/Project/VL/landing/node_modules/@11ty/eleventy/src/Eleventy.js:650:5) +0ms                             
  Eleventy:EleventyErrorHandler Input file is missing                                                                                                                        
  Eleventy:EleventyErrorHandler                                                                                                                                              
  Eleventy:EleventyErrorHandler `Error` was thrown: +0ms                                                                                                                     
  Eleventy:EleventyErrorHandler (error stack): Error: Input file is missing +0ms                                                                                             
  Eleventy:EleventyErrorHandler Problem writing Eleventy templates: +0ms                                                                                                     
  Eleventy:EleventyErrorHandler Having trouble writing template: ./site/index.html                                                                                           
  Eleventy:EleventyErrorHandler                                                                                                                                              
  Eleventy:EleventyErrorHandler `TemplateWriterWriteError` was thrown +0ms                                                                                                   
  Eleventy:EleventyErrorHandler (error stack): TemplateWriterWriteError: Having trouble writing template: ./site/index.html                                                  
  Eleventy:EleventyErrorHandler     at /home/ja/Project/VL/landing/node_modules/@11ty/eleventy/src/TemplateWriter.js:216:15                                                  
  Eleventy:EleventyErrorHandler     at async Promise.all (index 3)                                                                                                           
  Eleventy:EleventyErrorHandler     at async Eleventy.write (/home/ja/Project/VL/landing/node_modules/@11ty/eleventy/src/Eleventy.js:741:13)                                 
  Eleventy:EleventyErrorHandler     at async Eleventy.watch (/home/ja/Project/VL/landing/node_modules/@11ty/eleventy/src/Eleventy.js:650:5) +0ms                             
  Eleventy:EleventyErrorHandler Input file is missing                                                                                                                        
  Eleventy:EleventyErrorHandler                                                                                                                                              
  Eleventy:EleventyErrorHandler `Error` was thrown: +0ms                                                                                                                     
  Eleventy:EleventyErrorHandler (error stack): Error: Input file is missing +0ms
```
**Environment:**

- Linux
- 0.11

**Additional context**
The input files exists (liquid) I use just liquid and md files

**Comment by samuelpath** [comment]
Is your repo public? If so, can you provide the link so the issue could be reproduced?
Otherwise, it's pretty difficult to help you.

**Comment by samuelpath** [comment]
Or at least can you provide you index file?

**Comment by jalberto** [comment]
sorry for the delay, I was trying to reproduce in a clean project but I am
not able to, it seems related to the use of more than one template language
in same project
