### ISSUE TITLE
Intermittent Partial not Found Error when Writing Templates

### ISSUE THREAD

**Issue by shaunrashid** [11ty/eleventy#1562]
**Describe the bug**
When using Handlebars and writing the templates, an error occurs that says:
```
Error writing templates: (more in DEBUG output)
> Having trouble writing template: dist/index.html

`TemplateWriterWriteError` was thrown
> The partial [partial name] could not be found

`Error` was thrown:
    Error: The partial [partial name] could not be found
        at Object.invokePartial (C:\Users\Developer\Eleventy\MyProject\node_modules\handlebars\dist\cjs\handlebars\runtime.js:332:11)
        at Object.invokePartialWrapper [as invokePartial] (C:\Users\Developer\Eleventy\MyProject\node_modules\handlebars\dist\cjs\handlebars\runtime.js:84:39)
        at Object.eval [as main] (eval at createFunctionContext (C:\Users\Developer\Eleventy\MyProject\node_modules\handlebars\dist\cjs\handlebars\compiler\javascript-compiler.js:262:23), <anonymous>:13:28)
        at main (C:\Users\Developer\Eleventy\MyProject\node_modules\handlebars\dist\cjs\handlebars\runtime.js:208:32)
        at ret (C:\Users\Developer\Eleventy\MyProject\node_modules\handlebars\dist\cjs\handlebars\runtime.js:212:12)
        at ret (C:\Users\Developer\Eleventy\MyProject\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:519:21)
        at C:\Users\Developer\Eleventy\MyProject\node_modules\@11ty\eleventy\src\Engines\Handlebars.js:61:14
        at TemplateLayout.render (C:\Users\Developer\Eleventy\MyProject\node_modules\@11ty\eleventy\src\TemplateLayout.js:152:31)
        at async Template.renderPageEntry (C:\Users\Developer\Eleventy\MyProject\node_modules\@11ty\eleventy\src\Template.js:603:17)
        at async Template.writeMapEntry (C:\Users\Developer\Eleventy\MyProject\node_modules\@11ty\eleventy\src\Template.js:616:21)
```
Moving the partial in question to a different location and then back to it's original location seems to temporarily resolve the issue. 

**To Reproduce**
With an Eleventy project configured to use hbs as the htmlTemplateEngine in .eleventy.js

1. Create a partial in a subfolder of the _includes folder.
2. Refer to the partial in your layout file.
3. Run npx @11ty/eleventy --serve

The partials themselves work as expected when located in the _includes folder as well as a subfolder of the _includes folder.

**Expected behavior**
Partial files should be found in _includes folder and it's subfolders and Eleventy should be able to generate the static HTML files

**Screenshots**

**Environment:**

- OS and Version: [e.g. Windows/Mac/Linux]
- Windows 10 w/ Visual Studio Code
- Eleventy 0.11.1

**Additional context**
Response from the @eleventy_ty Twitter account: https://twitter.com/eleven_ty/status/1341947148896776192?s=20

Contents of .eleventy.js
```
module.exports = function(eleventyConfig) {
    eleventyConfig.addPassthroughCopy("src/images");
    eleventyConfig.addPassthroughCopy("src/css");

    return {
        dir: {
            input: "src",
            output: "dist"
        },
        htmlTemplateEngine: "hbs"
    }
}
```

**Comment by shaunrashid** [comment]
Looking at this after a few days, I realize there's no bug here. I just didn't put the subfolder in the path when referring to the partial. I was confused because the server was loading the previously compiled HTML files (before the error) and I thought it was some intermittent issue.
