### ISSUE TITLE
Parse Error in .hbs Template when Using Filters in Permalinks

### ISSUE THREAD

**Issue by shaunrashid** [11ty/eleventy#1563]
**Describe the bug**
Exception when trying to use a filter in the permalink front-matter in an .hbs template. In my example, I am generating multiple pages based on a global data JSON file. If I don't try to define a permalink using a filter, then the pages are generated successfully.

I used the following documentation as my example: https://www.11ty.dev/docs/pages-from-data/

**To Reproduce**

Create an .hbs page using front-matter similar to the example below and run npx @11ty/eleventy --serve 
```
layout: layout-default.hbs
pagination: 
    data: possums
    size: 1
    alias: possum
permalink: "possums/{{ possum.name | slug }}"
```

**Expected behavior**
Pages should be generated with the filename generated by the permalink when using the slug filter.

**Screenshots**

**Environment:**

- OS and Version: Mac OS
- Eleventy Version 0.11.1
- Handlebars templating engine.

**Additional context**

It appears that the hbs parser is choking on the | in the template token in the permalink.

```
> npx @llty/eleventy --serve

Problem writing Eleventy templates: (more in DEBUG output)
> Having trouble rendering hbs template ./src/possums/possum.hbs

`TemplateContentRenderError` was thrown
> Parse error on line 1:
possums/{{ possum.name | slug }}
-----------------------^
Expecting 'CLOSE_RAW_BLOCK', 'CLOSE', 'CLOSE_UNESCAPED', 'OPEN_SEXPR', 'CLOSE_SEXPR', 'ID', 'OPEN_BLOCK_PARAMS', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', 'SEP', got 'CLOSE_BLOCK_PARAMS'

`Error` was thrown:
    Error: Parse error on line 1:
    possums/{{ possum.model | slug }}
    ------------------------^
    Expecting 'CLOSE_RAW_BLOCK', 'CLOSE', 'CLOSE_UNESCAPED', 'OPEN_SEXPR', 'CLOSE_SEXPR', 'ID', 'OPEN_BLOCK_PARAMS', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', 'SEP', got 'CLOSE_BLOCK_PARAMS'
        at Parser.parseError (my-11ty-project/node_modules/handlebars/dist/cjs/handlebars/compiler/parser.js:267:19)
        at Parser.parse (my-11ty-project/node_modules/handlebars/dist/cjs/handlebars/compiler/parser.js:336:30)
        at parseWithoutProcessing (my-11ty-project/node_modules/handlebars/dist/cjs/handlebars/compiler/base.js:46:33)
        at HandlebarsEnvironment.parse (my-11ty-project/node_modules/handlebars/dist/cjs/handlebars/compiler/base.js:52:13)
        at compileInput (my-11ty-project/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:508:19)
        at ret (my-11ty-project/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:517:18)
        at my-11ty-project/node_modules/@11ty/eleventy/src/Engines/Handlebars.js:61:14
        at Template.render (my-11ty-project/node_modules/@11ty/eleventy/src/TemplateContent.js:199:28)
```

**Comment by gobeli** [comment]
If I'm not mistaken, the permalink gets parsed with the same engine as the template. Since handlebars uses a different syntax for filters, your page data should look something like this:
```
pagination:
    data: possums
    size: 1
    alias: possum
permalink: "possums/{{{ slug possum.name }}}/"
```

**Comment by shaunrashid** [comment]
Really late with a reply but thanks, @gobeli. Your comment gave me the solution I needed.
