### ISSUE TITLE
Eleventy build error because of Netlify Identity generated emails

### ISSUE THREAD

**Issue by kylesloper** [11ty/eleventy#1575]
##### Error
    Template render error: (./email/Email-change.html) [Line 133, Column 139]
          unexpected token: .
            at Object._prettifyError (C:\Users\kyles\Desktop\moonface\node_modules\nunjucks\src\lib.js:36:11)
            at Template.render (C:\Users\kyles\Desktop\moonface\node_modules\nunjucks\src\environment.js:536:21)
            at C:\Users\kyles\Desktop\moonface\node_modules\@11ty\eleventy\src\Engines\Nunjucks.js:236:14
            at new Promise (<anonymous>)
            at C:\Users\kyles\Desktop\moonface\node_modules\@11ty\eleventy\src\Engines\Nunjucks.js:235:14
            at C:\Users\kyles\Desktop\moonface\node_modules\@11ty\eleventy\src\Engines\Html.js:14:16
            at Template.render (C:\Users\kyles\Desktop\moonface\node_modules\@11ty\eleventy\src\TemplateContent.js:199:28)
            at runMicrotasks (<anonymous>)
            at processTicksAndRejections (internal/process/task_queues.js:93:5)
            at async Template._getContent (C:\Users\kyles\Desktop\moonface\node_modules\@11ty\eleventy\src\Template.js:547:12)

##### Cause of error (template)

```
<p>Follow this link to confirm the update of your email from {{ .Email }} to {{ .NewEmail }}:</p>
<p><a href="{{ .ConfirmationURL }}">Change Email</a></p>
```

Windows 10

**Comment by zachleat** [comment]
Add maybe just add the `email` folder to your `.eleventyignore`? Or use a different file extension for it?

**Comment by zachleat** [comment]
https://www.11ty.dev/docs/ignores/

**Comment by zachleat** [comment]
> This is an automated message to let you know that a helpful response was posted to your issue and for the health of the repository issue tracker the issue will be closed. This is to help alleviate issues hanging open waiting for a response from the original poster.

> If the response works to solve your problem—great! But if you’re still having problems, do not let the issue’s closing deter you if you have additional questions! Post another comment and I will reopen the issue. Thanks!
