### ISSUE TITLE
TemplateContentRenderError when using nunjucks in markdown

### ISSUE THREAD

**Issue by blueblots** [11ty/eleventy#1673]
**Describe the bug**
TemplateContentRenderError when trying to use a nunjucks macro in a markdown document. See 'Additional context' for further info.

**Expected behavior**
For the template to compile successfully.

**Environment:**

- OS and Version: Linux
- Eleventy Version: 0.11.1

**Additional context**
Hi, I'm new to Eleventy and have been having some problems getting a template to work that uses Nunjucks/Markdown at the same time.

I have a macro that I am trying to import into a template to generate content from a data file. The macro is this:

```njk
{% macro picture-gallery(items, cols=5) %}
<section class='container'>
  <div class='row'>
    {%- for item in items -%}
    <div class='col-{{- cols -}}'>
      <picture>
        {%- for image in item.variants -%}
        <source media='{{ image.media }}' srcset='{{ image.src }}'/>
        {%- endfor -%}
        <img src='{{ item.src }}' alt='{{ item.alt }}'/>
      </picture>
    </div>
    {%- endfor -%}
  </div>
</section>
{% endmacro %}
```

The markdown file is this:

```markdown
---
title: GalleryAll
layout: "page.njk"
---

{% import "picture-gallery.njk" as gallerymacro %}

This is a gallery, lorum ipsum et sit dolor quit iaosjfdjlksad.

{{ gallerymacro.picture-gallery(gallery, cols=5) }}
```

When I try to build, I get this error:

```
Problem writing Eleventy templates: (more in DEBUG output)
> Having trouble rendering njk (and markdown) template ./dev/gallery/index.md

`TemplateContentRenderError` was thrown
> (./dev/gallery/index.md) [Line 1, Column 17]
  expected arguments

`Template render error` was thrown:
    Template render error: (./dev/gallery/index.md) [Line 1, Column 17]
      expected arguments
        at Object._prettifyError (../portfolio/node_modules/nunjucks/src/lib.js:36:11)
        at ../portfolio/node_modules/nunjucks/src/environment.js:563:19
        at eval (eval at _compile (../portfolio/node_modules/nunjucks/src/environment.js:633:18), <anonymous>:13:11)
        at Template.getExported (../portfolio/node_modules/nunjucks/src/environment.js:601:16)
        at eval (eval at _compile (../portfolio/node_modules/nunjucks/src/environment.js:633:18), <anonymous>:12:5)
        at createTemplate (../portfolio/node_modules/nunjucks/src/environment.js:315:9)
        at handle (../portfolio/node_modules/nunjucks/src/environment.js:327:11)
        at ../portfolio/node_modules/nunjucks/src/environment.js:339:9
        at next (../portfolio/node_modules/nunjucks/src/lib.js:328:7)
        at Object.asyncIter (../portfolio/node_modules/nunjucks/src/lib.js:334:3)
Wrote 0 files in 0.32 seconds (v0.11.1)
```

Is it not possible to use nunjucks imports in a markdown file, or am I missing something?

Thank you for any help.

**Comment by hendotcat** [comment]
Ooh I've got good news for you! This is an easy fix! Nunjucks macro names can't have hyphens in them, and that's what's causing your error there. Rename your macro from `picture-gallery` to `pictureGallery` or anything else you want without a hyphen in it and it'll work fine!

**Comment by blueblots** [comment]
Thank you, I will give that a try.
