### ISSUE TITLE
EleventyConfigError: `eleventyConfig.addGlobalData` is not a function

### ISSUE THREAD

**Issue by gluecksmensch** [11ty/eleventy#1682]
**Describe the bug**
```
TypeError: eleventyConfig.addGlobalData is not a function
        at module.exports (/Users/dh/projects/wps/.eleventy.js:9:18)
        at TemplateConfig.mergeConfig (/Users/dh/projects/wps/node_modules/@11ty/eleventy/src/TemplateConfig.js:91:25)
        at new TemplateConfig (/Users/dh/projects/wps/node_modules/@11ty/eleventy/src/TemplateConfig.js:25:24)
        at Object.<anonymous> (/Users/dh/projects/wps/node_modules/@11ty/eleventy/src/Config.js:5:14)
        at Module._compile (internal/modules/cjs/loader.js:1063:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
        at Module.load (internal/modules/cjs/loader.js:928:32)
        at Function.Module._load (internal/modules/cjs/loader.js:769:14)
        at Module.require (internal/modules/cjs/loader.js:952:19)
        at require (internal/modules/cjs/helpers.js:88:18)
```

**To Reproduce**
Add a global data property to the `.eleventy.js` (eg. `eleventyConfig.addGlobalData("myStatic", "static");`) and run `npx @11ty/eleventy`.

**Expected behavior**
No error occurs, the global variable is available in 11ty templates.

**Environment:**

- OS and Version: Mac Big Sur 11.2.2
- Eleventy Version: 0.11.1

**Additional context**
It looks like this function isn't implemented in the current release yet, but the docs already contain this new feature.

**Comment by pdehaan** [comment]
https://www.11ty.dev/docs/data-global-custom/#global-data-from-the-configuration-api

The top of the page has a “Coming soon in v1.0.0”, but the current release is v0.11.1. So you either need to wait for the official v1 release, or install from GitHub (`npm i github:11ty/eleventy`), or install a “canary” build from npm (`npm i @11ty/eleventy@canary`).

**Comment by gluecksmensch** [comment]
Thanks for the hint, I'm sorry, I missed that label and was a bit confused. Will close this issue.
