### ISSUE TITLE
TemplateLayoutPathResolver directory does not exist 

### ISSUE THREAD

**Issue by iammelvin** [11ty/eleventy#1766]
I am getting the below error while serving my 11ty app in local using npm start. Also while accessing the port 8080 I get

`cannot GET / `

```
"scripts": {
    "start": "npx eleventy --serve"
  },

```
```
Problem writing Eleventy templates: (more in DEBUG output)
> TemplateLayoutPathResolver directory does not exist for layouts/home.html: _includes

`Error` was thrown:
    Error: TemplateLayoutPathResolver directory does not exist for layouts/home.html: _includes
        at TemplateLayoutPathResolver.findFileName (C:\Users\864004\Documents\11ty\11ty-iam-blog\node_modules\@11ty\eleventy\src\TemplateLayoutPathResolver.js:101:13)
        at TemplateLayoutPathResolver.init (C:\Users\864004\Documents\11ty\11ty-iam-blog\node_modules\@11ty\eleventy\src\TemplateLayoutPathResolver.js:68:28)
        at new TemplateLayoutPathResolver (C:\Users\864004\Documents\11ty\11ty-iam-blog\node_modules\@11ty\eleventy\src\TemplateLayoutPathResolver.js:21:10)
        at new TemplateLayout (C:\Users\864004\Documents\11ty\11ty-iam-blog\node_modules\@11ty\eleventy\src\TemplateLayout.js:16:24)
        at Function.getTemplate (C:\Users\864004\Documents\11ty\11ty-iam-blog\node_modules\@11ty\eleventy\src\TemplateLayout.js:44:16)
        at Template.getLayout (C:\Users\864004\Documents\11ty\11ty-iam-blog\node_modules\@11ty\eleventy\src\Template.js:86:37)
        at Template.getData (C:\Users\864004\Documents\11ty\11ty-iam-blog\node_modules\@11ty\eleventy\src\Template.js:242:27)
        at async Template.getTemplateMapEntries (C:\Users\864004\Documents\11ty\11ty-iam-blog\node_modules\@11ty\eleventy\src\Template.js:744:16)
        at async TemplateMap.add (C:\Users\864004\Documents\11ty\11ty-iam-blog\node_modules\@11ty\eleventy\src\TemplateMap.js:32:21)
        at async Promise.all (index 0)
```

OS : Windows 10
11ty Version :  "@11ty/eleventy": "^0.12.1"

**Comment by pdehaan** [comment]
Sounds like maybe an invalid config.
What does your .eleventy.js config file look like (and your directory tree too, if it’s maybe something to do with your `dir.input` vs `dir.includes` maybe).

I assume you get the same error without `--serve`?

**Comment by iammelvin** [comment]
This is the eleventy config file & yes get the same error without --serve
```
module.exports = config => {
  return {
    markdownTemplateEngine: 'njk',
    dataTemplateEngine: 'njk',
    htmlTemplateEngine: 'njk',
    dir: {
      input: 'src',
      output: 'dist'
    }
  };
};

```

**Comment by pdehaan** [comment]
Interesting, this works for me on macOS...

```sh
tree -a -I node_modules
.
├── .eleventy.js
├── dist
│   └── index.html
├── package-lock.json
├── package.json
└── src
    ├── _includes
    │   └── layouts
    │       └── home.html
    └── home.njk

4 directories, 6 files
```

Where my .eleventy.js file looks like this:

```js
module.exports = (config) => {
  return {
    dir: {
      input: "src",
      output: "dist"
    }
  };
};
```

&hellip; and my ./src/home.njk file looks like this:

```nunjucks
---
title: HOME
layout: layouts/home.html
permalink: /
---

<h1>{{ title }}</h1>
```

**Comment by pdehaan** [comment]
@iammelvin Do you have a public repo somewhere that I can try cloning and debug locally?
Now I'm wondering if its a macOS-vs-Windows thing.

**Comment by iammelvin** [comment]
Sorry I was just getting started with 11ty by following a course. Here you go [Repo](https://github.com/iammelvin/11ty-iam-blog/tree/master)

**Comment by iammelvin** [comment]
Thanks a lot will continue learning :)
