### ISSUE TITLE
Includes won't work with Pug templates

### ISSUE THREAD

**Issue by Baregamyan** [11ty/eleventy#1780]
**Describe the bug**
Hi! Could you help me to figure out how to make my project template work =) 

So my project structure:

```
└─ src/
   └─ data/
   └─ includes/
      │  ├─ header.pug
      │  ├─ footer.pug
   └─ layouts/
      │  ├─ page.pug
   └─ pages/
      │  ├─ index.pug

```

My **src/layouts/layout.pug** file:
```
doctype html
html(lang="en")
  head
    meta(charset="UTF-8")
    meta(http-equiv="X-UA-Compatible", content="IE=edge")
    meta(name="viewport", content="width=device-width, initial-scale=1.0")
    title #{title}
  body
    include ../includes/header.pug
    main
      
      | !{content}
```

My **src/pages/index.pug** file:
```
---
title: Index
layout: page.pug
---
section.home
  h1.title.home__title #{title}
```

My **src/includes/header.pug** file:
```
---
title: Header include
---
header.header
  h2.title.header__title #{title}
```
During compile I always got this error:
```
Error writing templates: (more in DEBUG output)
> Having trouble writing template: dirs/pages/index.html

`TemplateWriterWriteError` was thrown
> Having trouble compiling template ./src/layouts/page.pug

`TemplateContentCompileError` was thrown
> Error parsing body of the with expression

`Error` was thrown:
    Error: Error parsing body of the with expression
        at addWith (/home/arsen/GitHub/eleventy-pug/node_modules/with/lib/index.js:50:29)
        at Compiler.compile (/home/arsen/GitHub/eleventy-pug/node_modules/pug-code-gen/index.js:139:12)
        at generateCode (/home/arsen/GitHub/eleventy-pug/node_modules/pug-code-gen/index.js:32:37)
        at compileBody (/home/arsen/GitHub/eleventy-pug/node_modules/pug/lib/index.js:199:74)
        at Object.exports.compile (/home/arsen/GitHub/eleventy-pug/node_modules/pug/lib/index.js:269:16)
        at Pug.compile (/home/arsen/GitHub/eleventy-pug/node_modules/@11ty/eleventy/src/Engines/Pug.js:44:24)
        at TemplateRender.getCompiledTemplate (/home/arsen/GitHub/eleventy-pug/node_modules/@11ty/eleventy/src/TemplateRender.js:212:26)
        at TemplateLayout.compile (/home/arsen/GitHub/eleventy-pug/node_modules/@11ty/eleventy/src/TemplateContent.js:181:42)
        at async TemplateLayout.getCompiledLayoutFunctions (/home/arsen/GitHub/eleventy-pug/node_modules/@11ty/eleventy/src/TemplateLayout.js:122:9)
        at async TemplateLayout.render (/home/arsen/GitHub/eleventy-pug/node_modules/@11ty/eleventy/src/TemplateLayout.js:150:15)
Problem writing Eleventy templates: (more in DEBUG output)
> Having trouble writing template: dirs/pages/index.html

`TemplateWriterWriteError` was thrown
> Having trouble compiling template ./src/layouts/page.pug

`TemplateContentCompileError` was thrown
> Error parsing body of the with expression

`Error` was thrown:
    Error: Error parsing body of the with expression
        at addWith (/home/arsen/GitHub/eleventy-pug/node_modules/with/lib/index.js:50:29)
        at Compiler.compile (/home/arsen/GitHub/eleventy-pug/node_modules/pug-code-gen/index.js:139:12)
        at generateCode (/home/arsen/GitHub/eleventy-pug/node_modules/pug-code-gen/index.js:32:37)
        at compileBody (/home/arsen/GitHub/eleventy-pug/node_modules/pug/lib/index.js:199:74)
        at Object.exports.compile (/home/arsen/GitHub/eleventy-pug/node_modules/pug/lib/index.js:269:16)
        at Pug.compile (/home/arsen/GitHub/eleventy-pug/node_modules/@11ty/eleventy/src/Engines/Pug.js:44:24)
        at TemplateRender.getCompiledTemplate (/home/arsen/GitHub/eleventy-pug/node_modules/@11ty/eleventy/src/TemplateRender.js:212:26)
        at TemplateLayout.compile (/home/arsen/GitHub/eleventy-pug/node_modules/@11ty/eleventy/src/TemplateContent.js:181:42)
        at async TemplateLayout.getCompiledLayoutFunctions (/home/arsen/GitHub/eleventy-pug/node_modules/@11ty/eleventy/src/TemplateLayout.js:122:9)
        at async TemplateLayout.render (/home/arsen/GitHub/eleventy-pug/node_modules/@11ty/eleventy/src/TemplateLayout.js:150:15)
Wrote 0 files in 0.17 seconds (v0.12.1)

```

My **.eleventy.js** file:
```
module.exports = function(config) {
  config.setPugOptions({ debug: true })
  return {
    dir: {
      input: "src",
      includes: "includes",
      layouts: "layouts",
      data: "data",
      output: "dirs"
    }
  }
}
```

When I take away includes from the layout file everything is good. I have no idea what am I doing wrong. Will be happy for any help with my problem.

**To Reproduce**

Just start the Eleventy locally 

**Expected behavior**
Work with my includes `header.pug` and `footer.pug`

**Screenshots**

**Environment:**

- OS and Version: [Linux Ubuntu 20.04]
- Eleventy Version [0.12.1]

**Additional context**

**Comment by taniki** [comment]
You need to remove the frontmatter metadata from `header.pug`. I guess you coming from jekkyl :)

**Comment by Baregamyan** [comment]
> You need to remove the frontmatter metadata from `header.pug`. I guess you coming from jekyll :)

Thank you! =)
