### ISSUE TITLE
Latest canary doesn't ignore node_modules by default

### ISSUE THREAD

**Issue by arcxyz** [11ty/eleventy#1837]
**Describe the bug**
Related to #383. It seems that latest canary is not ignoring `node_modules` by default. 

**To Reproduce**

1. Initialize an empty npm project with `@11ty/eleventy@1.0.0-canary.36` installed and try to run eleventy. Just for clarification the directory doesn't contain a `.gitignore` file.
```
$ npm init -y && npm install -D @11ty/eleventy@1.0.0-canary.36 && npx eleventy --serve
```

2. It throws an error trying to render markdown files found in node_modules
```
Problem writing Eleventy templates: (more in DEBUG output)
> Having trouble rendering liquid template ./node_modules/balanced-match/README.md

`TemplateContentRenderError` was thrown
> unexpected token at "}` will match...", file:./node_modules/balanced-match/README.md, line:50, col:130

`ParseError` was thrown
> unexpected token at "}` will match..."

`AssertionError` was thrown:
    AssertionError: unexpected token at "}` will match..."
        at assert (/private/tmp/11ty-ignore-node-modules/node_modules/liquidjs/dist/liquid.node.cjs.js:949:15)
        at Tokenizer.readFilter (/private/tmp/11ty-ignore-node-modules/node_modules/liquidjs/dist/liquid.node.cjs.js:1195:9)
        at Tokenizer.readFilters (/private/tmp/11ty-ignore-node-modules/node_modules/liquidjs/dist/liquid.node.cjs.js:1185:33)
        at new Value (/private/tmp/11ty-ignore-node-modules/node_modules/liquidjs/dist/liquid.node.cjs.js:1639:34)
        at new Output (/private/tmp/11ty-ignore-node-modules/node_modules/liquidjs/dist/liquid.node.cjs.js:1745:22)
        at Parser.parseToken (/private/tmp/11ty-ignore-node-modules/node_modules/liquidjs/dist/liquid.node.cjs.js:1781:24)
        at Parser.parse (/private/tmp/11ty-ignore-node-modules/node_modules/liquidjs/dist/liquid.node.cjs.js:1771:33)
        at Liquid.parse (/private/tmp/11ty-ignore-node-modules/node_modules/liquidjs/dist/liquid.node.cjs.js:2956:28)
        at Liquid.compile (/private/tmp/11ty-ignore-node-modules/node_modules/@11ty/eleventy/src/Engines/Liquid.js:223:28)
        at Markdown.compile (/private/tmp/11ty-ignore-node-modules/node_modules/@11ty/eleventy/src/Engines/Markdown.js:63:28)
Wrote 0 files in 0.98 seconds (v1.0.0-canary.36)
```

**Environment:**

- OS and Version: MacOS
- Eleventy Version: 1.0.0-canary.36
- Node: 14.17.1
- Npm: 6.14.13

**Additional context**
After some investigation it could be related with the following code that changes the relative path of `./node_modules/**` to an absolute path. Using an absolute path here should work without any problems so it could be related with how the `fast-glob` package handles absolute paths when ignoring files.
https://github.com/11ty/eleventy/blob/3344c8e054c59ea4bdb8385f9e51ce90f2d94fe5/src/EleventyFiles.js#L284-L290

**Comment by zachleat** [comment]
Confirmed!

**Comment by zachleat** [comment]
Canary 32 was the last working version.

**Comment by zachleat** [comment]
Broken in 6e20f63b20562d97c3a2b40ae911d1820f5bd584

**Comment by zachleat** [comment]
Fixed in Canary 37.

**Comment by zachleat** [comment]
Really appreciate the issue, thanks!
