### ISSUE TITLE
eleventy-plugin-error-overlay crashes 1.0.0-beta.1

### ISSUE THREAD

**Issue by brycewray** [11ty/eleventy#1999]
If an existing Eleventy site (or clone thereof in my case) already had the `eleventy-plugin-error-overlay` plugin installed, running Eleventy will result in the following console error message (substituting `my-computer` below for actual computer name):

```bash
[11ty] Uncaught exception: (more in DEBUG output)
[11ty] > Cannot read property '__original' of undefined

`TypeError` was thrown:
[11ty]     TypeError: Cannot read property '__original' of undefined
        at overrideStatic (/Users/my-computer/eleventy_site_beta/node_modules/eleventy-plugin-error-overlay/index.js:84:35)
        at Immediate.<anonymous> (/Users/my-computer/eleventy_site_beta/node_modules/eleventy-plugin-error-overlay/index.js:45:7)
        at processImmediate (internal/timers.js:461:21)
```

Removing that plugin resolves the problem, so this is mainly an FYI that this plugin and 1.0.0-beta.1 don't seem to like each other. :)

Environment where used:
- macOS 11.6
- Eleventy version 1.0.0-beta.1

**Comment by zachleat** [comment]
If you think this is a regression in the plugin API, please let me know! I don’t think `__original` is an Eleventy thing, though.

> This is an automated message to let you know that a helpful response was posted to your issue and for the health of the repository issue tracker the issue will be closed. This is to help alleviate issues hanging open waiting for a response from the original poster.

> If the response works to solve your problem—great! But if you’re still having problems, do not let the issue’s closing deter you if you have additional questions! Post another comment and we will reopen the issue. Thanks!
