### ISSUE TITLE
node_modules exclusion no longer working quite as expected

### ISSUE THREAD

**Issue by phil-w** [11ty/eleventy#2093]
(I'm confused by eleventy's version numbering - there's talk of 0.* also 1.*, but my version is the latest I can get which is 1.0.0 in package.json but quite possibly something completely different like @11ty/eleventy@0.12.1. It's all very confusing.). 

Anyway, sometime after November 3 a change to eleventy's latest production version made my Azure pipeline builds no longer ignore node_modules. Looking at it (see below), I'd guess it's because a simple `node_modules ` in git ignore no longer works if Azure stitches that into the middle of its working directory path.

My "fix" was to add a second line to my .gitignore with: `**/node_modules`. That change fixes it.

```
> eleventy@1.0.0 build /working_dir
> npx @11ty/eleventy

Problem writing Eleventy templates: (more in DEBUG output)
    Template render error: (./.oryx_prod_node_modules/node_modules/balanced-match/README.md) [Line 50, Column 133]
      expected variable end
        at Object._prettifyError (/working_dir/node_modules/nunjucks/src/lib.js:36:11)
        at Template.render (/working_dir/node_modules/nunjucks/src/environment.js:538:21)
        at /working_dir/node_modules/@11ty/eleventy/src/Engines/Nunjucks.js:236:14
        at new Promise (<anonymous>)
        at /working_dir/node_modules/@11ty/eleventy/src/Engines/Nunjucks.js:235:14
        at /working_dir/node_modules/@11ty/eleventy/src/Engines/Markdown.js:71:47
        at Template.render (/working_dir/node_modules/@11ty/eleventy/src/TemplateContent.js:199:28)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
        at async Template._getContent (/working_dir/node_modules/@11ty/eleventy/src/Template.js:547:12)
        at async Template.getTemplateMapContent (/working_dir/node_modules/@11ty/eleventy/src/Template.js:732:19)
Copied 141 files / Wrote 0 files in 1.23 seconds (v0.12.1)

```

**Comment by zachleat** [comment]
Yeah, sorry 1.0 is _very_ close to a stable release right now (Beta). After 1.0 goes stable, we won’t be in this weird limbo between 1.x and 0.x.

The error message you’ve reported there is using `v0.12.1` which was released 8 months ago.

![image](https://user-images.githubusercontent.com/39355/142013020-aab3fe00-2d37-4e8c-a8c1-0326e41d3ef9.png)
via https://www.npmjs.com/package/@11ty/eleventy

That said, we did make a subtle change in the default ignores behavior in 1.x (although that doesn’t seem to apply here) at #383. It is documented on https://www.11ty.dev/docs/ignores/

**Comment by zachleat** [comment]
The follow up here is that something about this report is not quite right—are you sure you copied the right console output? My hunch is that this is a 1.0 bug report but some piece is missing?

**Comment by zachleat** [comment]
> This is an automated message to let you know that this issue requires additional input from the original poster and for the health of the repository issue tracker the issue will be closed. This is to help alleviate issues hanging open waiting for a response from the original poster.

> Do not let the issue’s closing deter you. After you’ve supplied the required information, the issue will be reopened. Thanks!
