### ISSUE TITLE
Issue with Liquid’s `renderTemplate`

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#2098]
Beta.7 parses the content when it should be treated as plaintext—same as the `{% raw %}` tag.

```
{% renderTemplate "njk" %}
{% set bye = "abldskjfl" %}
{% endrenderTemplate %}
```

you can see liquid is nosing in on the syntax here:

```
`AssertionError` was thrown:
[11ty]     AssertionError: tag "set" not found
        at new AssertionError (/Users/zachleat/Code/eleventy/node_modules/liquidjs/dist/liquid.node.cjs.js:653:28)
        at assert (/Users/zachleat/Code/eleventy/node_modules/liquidjs/dist/liquid.node.cjs.js:800:15)
        at TagMap.get (/Users/zachleat/Code/eleventy/node_modules/liquidjs/dist/liquid.node.cjs.js:4048:9)
        at new Tag (/Users/zachleat/Code/eleventy/node_modules/liquidjs/dist/liquid.node.cjs.js:2389:32)
        at Parser.parseToken (/Users/zachleat/Code/eleventy/node_modules/liquidjs/dist/liquid.node.cjs.js:2477:24)
        at ParseStream.parseToken (/Users/zachleat/Code/eleventy/node_modules/liquidjs/dist/liquid.node.cjs.js:2490:80)
        at ParseStream.start (/Users/zachleat/Code/eleventy/node_modules/liquidjs/dist/liquid.node.cjs.js:1235:33)
        at Object.parse (/Users/zachleat/Code/eleventy/src/Plugins/RenderPlugin.js:102:16)
        at new Tag (/Users/zachleat/Code/eleventy/node_modules/liquidjs/dist/liquid.node.cjs.js:2393:24)
        at Parser.parseToken (/Users/zachleat/Code/eleventy/node_modules/liquidjs/dist/liquid.node.cjs.js:2477:24)
```

**Comment by zachleat** [comment]
Will ship with 1.0.0-beta.8
