### ISSUE TITLE
Write to a file using the eleventy.before event

### ISSUE THREAD

**Issue by mark-reason** [11ty/eleventy#2206]
I want to use the eleventy.before event to call an API to receive data and then write the response to a file in the _data folder, this is what I've got so far but it doesn't seem to be waiting for it to finish before eleventy starts to build the pages

```javascript
eleventyConfig.on("eleventy.before", async () => {
    try {
      const pageEndpoints = [
        'endpoint_url_1',
        'endpoint_url_2',
      ];

      const types = await Promise.all(
        pageEndpoints.map(async (url) => {
          const resp = await fetch(url);
          return resp.json();
        })
      );

      // Concatinate all pages
      let allTypes = [];
      for (let i = 0; i < types.length; i++) {
        allTypes = allTypes.concat(types[i]);
      }

      fs.writeFileSync(
        "src/_data/pages.json",
        JSON.stringify(allTypes),
        function (err) {
          if (err) {
            console.log(err);
            process.exit(1);
          }
        }
      );

      return;
    } catch (ex) {
      console.log(ex);
      process.exit(1);
    }
  });

  return {
    markdownTemplateEngine: "njk",
    dataTemplateEngine: "njk",
    htmlTemplateEngine: "njk",
    dir: {
      input: "src",
      output: "dist",
    },
  };
```

**Comment by pdehaan** [comment]
This seems to be working for me w/ my simplified test case w/ an absurd ~15 second pause in the middle of my "eleventy.before" event hook (was trying to simulate a slow network API request).

```js
// .eleventy.js
module.exports = (eleventyConfig) => {
  const nowTime = () => new Date().toLocaleTimeString();

  eleventyConfig.on("eleventy.before", async function (aaa) {
    console.log(`[${nowTime()}] eleventy.before start`, { aaa });
    await wait(15000);
    console.log(`[${nowTime()}] eleventy.before end`, { aaa });
  });
  eleventyConfig.on("eleventy.after", async (aaa) => {
    console.log(`[${nowTime()}] eleventy.after`, { aaa });
  });

  eleventyConfig.addCollection("pages2", (collectionApi) => {
    console.log(`[${nowTime()}] Creating pages2 collection...`);
    return collectionApi.getFilteredByGlob("src/pages/*.njk");
  });

  console.log(`[${nowTime()}] init complete`);
  return {
    dir: {
      input: "src",
      output: "www",
    },
  };
};

async function wait(delay = 2000) {
  return new Promise((resolve) => setTimeout(resolve, delay));
}
```

### OUTPUT
```sh
> Executing task: npm run build <

> 11ty-before-build@1.0.0 build
> eleventy

[8:31:31 a.m.] init complete
[8:31:31 a.m.] eleventy.before start { aaa: { inputDir: 'src' } }
[8:31:46 a.m.] eleventy.before end { aaa: { inputDir: 'src' } }
[8:31:47 a.m.] Creating pages2 collection...
[11ty] Writing www/index.html from ./src/index.njk
[11ty] Writing www/pages/index.html from ./src/pages/index.njk
[8:31:47 a.m.] eleventy.after { aaa: { inputDir: 'src' } }
[11ty] Wrote 2 files in 15.03 seconds (v1.0.0)
```

So my `eleventy.before` function has a 15 second pause in the middle of it, and we can see from the debug logging that it seems to wait in the `eleventy.before` function from 8:31:31am to 8:31:46am before trying to access other collections in my .eleventy.js file.

It's a bit unclear from the [`eleventy.before` docs](https://www.11ty.dev/docs/events/#eleventy.before), but it seems like it's added in 1.0.0, or it became "Async-friendly in 1.0+"; per the example comment. I'm guessing the "async-friendly" comment might be referring to the deprecated v0.11.1+ `beforeBuild` event.

Are you're using the latest Eleventy 1.0.0 build, or are you using a beta/canary build?

**Comment by mark-reason** [comment]
Hi @pdehaan 

Yes I am using v1.0.0. I get an error referring to the pages data being missing with my example above.

**Comment by mark-reason** [comment]
Yes so the pages.json is generated and the output is what I'm expecting to see. 

This is the error I get:
```
[11ty] > Could not find pagination data, went looking for: pages

`Error` was thrown:
[11ty]     Error: Could not find pagination data, went looking for: pages
        at Pagination._get ({PATH}/node_modules/@11ty/eleventy/src/Plugins/Pagination.js:150:13)
        at Pagination.setData ({PATH}/node_modules/@11ty/eleventy/src/Plugins/Pagination.js:71:29)
        at new Pagination ({PATH}/node_modules/@11ty/eleventy/src/Plugins/Pagination.js:19:10)
        at Template.getTemplates ({PATH}/node_modules/@11ty/eleventy/src/Template.js:713:21)
        at TemplateMap.initDependencyMap ({PATH}/node_modules/@11ty/eleventy/src/TemplateMap.js:288:41)
        at TemplateMap.cache ({PATH}/node_modules/@11ty/eleventy/src/TemplateMap.js:333:16)
        at TemplateWriter._createTemplateMap ({PATH}/node_modules/@11ty/eleventy/src/TemplateWriter.js:242:28)
        at async TemplateWriter.generateTemplates ({PATH}/node_modules/@11ty/eleventy/src/TemplateWriter.js:275:5)
        at async TemplateWriter.write ({PATH}/node_modules/@11ty/eleventy/src/TemplateWriter.js:321:23)
        at async Eleventy.executeBuild ({PATH}/node_modules/@11ty/eleventy/src/Eleventy.js:986:13)
```

**Comment by mark-reason** [comment]
I might actually be going about this the wrong way, what I'm trying to do is make dynamic data (currently by creating a pages.json file with an API response) available in the eleventy.js config file (and make sure it also re-fetches at the start of the watch task), is that possible?

**Comment by pdehaan** [comment]
> `Error: Could not find pagination data, went looking for: pages`

That seems like a very suspicious error.
I'd almost assume it's not generating the src/_data/pages.json file, or not saving the file in the correct place (hence it not being able to find the expected pages.json pagination data).

**Comment by pdehaan** [comment]
> I might actually be going about this the wrong way, what I'm trying to do is make dynamic data (currently by creating a pages.json file with an API response) available in the eleventy.js config file (and make sure it also re-fetches at the start of the watch task), is that possible?

🤷 
I generally avoid `--watch` and haven't played too much w/ `eleventyConfig.on("eleventy.before")` event hooks yet to understand what exactly causes them to retrigger. Usually when I fetch data, I put it in the .eleventy.js function directly or in a separate script and fetch it manually to avoid rate limiting, etc. But my simple "https://httpbin.org/uuid" use case above worked, so it should be possible on some level.

But from the sounds of that error, something else is happening. What's the contents of your ./src/_data/pages.json file, and is it valid JSON?
Or possibly there is a bug in the async flows for "eleventy.before". I tried using some slow https://httpbin.org/delay/5 request to simulate a slow network connection, so not sure why your code isn't working as expected.

**Comment by zachleat** [comment]
If we might be able to take a step back here, I wonder if using https://www.11ty.dev/docs/plugins/cache/ inside of a global data file is a more idiomatic/standard approach here.

**Comment by zachleat** [comment]
Note also that you can use `duration: "*"` to always use the cache after the first request.

**Comment by zachleat** [comment]
Suddenly realized that `duration: "*"` wasn’t on the docs so I added that too—oops 😬

https://www.11ty.dev/docs/plugins/cache/

**Comment by zachleat** [comment]
> This is an automated message to let you know that a helpful response was posted to your issue and for the health of the repository issue tracker the issue will be closed. This is to help alleviate issues hanging open waiting for a response from the original poster.

> If the response works to solve your problem—great! But if you’re still having problems, do not let the issue’s closing deter you if you have additional questions! Post another comment and we will reopen the issue. Thanks!

**Comment by mark-reason** [comment]
Thanks @zachleat.

From my experience using that plugin (and I may be wrong/have the incorrect configuration), it doesn't make the data available to be used in the eleventy.js file. I am creating collections using data fetched from an API, the way I'm doing it currently is by fetching the data first in a node script before running everything else but obviously this doesn't work with eleventy watch while developing (if the data changes).
