### ISSUE TITLE
Serverless not working with Netlify esbuild

### ISSUE THREAD

**Issue by 5t3ph** [11ty/eleventy#2235]
**Describe the bug**
Deploying an 11ty site on Netlify with the esbuild function bundling does not successfully retain the serverless functionality, so serverless pages are inaccessible.

**To Reproduce**
1. Clone this repo with the reduced test case of a very basic serverless setup including the esbuild parts for Netlify: https://github.com/5t3ph/11ty-serverless-esbuild-test
2. Deploy to Netlify
3. Observe that the serverless page does not load, but displays an error similar to the following

```json
{"errorType":"Error","errorMessage":"Cannot find module '/var/task/netlify/functions/possum/eleventy-serverless-map.json'\nRequire stack:\n- /var/task/node_modules/@11ty/eleventy/src/Serverless.js\n- /var/task/node_modules/@11ty/eleventy/src/Eleventy.js\n- /var/task/netlify/functions/possum/index.js\n- /var/task/possum.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js","trace":["Error: Cannot find module '/var/task/netlify/functions/possum/eleventy-serverless-map.json'","Require stack:","- /var/task/node_modules/@11ty/eleventy/src/Serverless.js","- /var/task/node_modules/@11ty/eleventy/src/Eleventy.js","- /var/task/netlify/functions/possum/index.js","- /var/task/possum.js","- /var/runtime/UserFunction.js","- /var/runtime/index.js","    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)","    at Function.Module._load (internal/modules/cjs/loader.js:746:27)","    at Module.require (internal/modules/cjs/loader.js:974:19)","    at require (internal/modules/cjs/helpers.js:93:18)","    at Serverless.getContentMap (/var/task/node_modules/@11ty/eleventy/src/Serverless.js:102:22)","    at Serverless.isServerlessUrl (/var/task/node_modules/@11ty/eleventy/src/Serverless.js:117:27)","    at Runtime.handler (/var/task/netlify/functions/possum/index.js:45:14)"]}
```

[live page link](https://11ty-serverless-esbuild-test.netlify.app/possum/)

**Expected behavior**
The serverless page loads successfully.

**Environment:**

- New Netlify build (focal)
- Eleventy Version: ^1.0.0

**Additional context**
Discovered esbuild was needed to deploy a site that was going to use [the prismic plugin](https://github.com/prismicio-community/eleventy-plugin-prismic/blob/master/DOCUMENTATION.md). Then the serverless component that allows live previewing from Prismic CMS wouldn't function on deploy. The same issue was repro'd in the demo repo with a basic serverless setup.

**Comment by zachleat** [comment]
Agree that there is something to fix here but in the mean time here’s some `netlify.toml` addition that I’ve used to “make it work” now with `esbuild`:

```toml
[functions]
node_bundler = "esbuild"

[functions.possum]
  included_files = [
  "./netlify/functions/possum/**/*",
  "./netlify/functions/possum/.cache/**/*"
]
```

**Comment by zachleat** [comment]
I did test this on your test case here: https://github.com/5t3ph/11ty-serverless-esbuild-test/compare/main...zachleat:main

https://main--peppy-lebkuchen-2767ab.netlify.app/

**Comment by zachleat** [comment]
> This is an automated message to let you know that a helpful response was posted to your issue and for the health of the repository issue tracker the issue will be closed. This is to help alleviate issues hanging open waiting for a response from the original poster.

> If the response works to solve your problem—great! But if you’re still having problems, do not let the issue’s closing deter you if you have additional questions! Post another comment and we will reopen the issue. Thanks!
