### ISSUE TITLE
Unable to install via npm

### ISSUE THREAD

**Issue by jrrdnx** [11ty/eleventy#2262]
**Describe the bug**
I'm walking through the [Getting Started](https://www.11ty.dev/docs/getting-started/) documentation, and when running `npm install @11ty/eleventy --save-dev` I'm receiving the following error:
```
npm ERR! Unexpected end of JSON input while parsing near '...UF7WlqkflPiuyzKXgZBn4'
```

**Expected behavior**
Except `@11ty/eleventy` to be installed.

**Environment:**

- OS and Version: MacOS 12.2.1
- Eleventy Version: N/A
- npm: v6.14.11
- node: v12.20.2

**Additional context**
Full npm debug log:
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '<redacted>/.nvm/versions/node/v12.20.2/bin/node',
1 verbose cli   '<redacted>/.nvm/versions/node/v12.20.2/bin/npm',
1 verbose cli   'install',
1 verbose cli   '@11ty/eleventy',
1 verbose cli   '--save-dev'
1 verbose cli ]
2 info using npm@6.14.11
3 info using node@v12.20.2
4 verbose npm-session 60558c8c685dc360
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/@11ty%2feleventy 1042ms (from cache)
8 silly pacote tag manifest for @11ty/eleventy@latest fetched in 1058ms
9 timing stage:loadCurrentTree Completed in 1092ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 1ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule @11ty/eleventy@1.0.0 checking installable status
17 http fetch GET 200 https://registry.npmjs.org/@11ty%2fdependency-tree 39ms (from cache)
18 http fetch GET 200 https://registry.npmjs.org/@iarna%2ftoml 40ms (from cache)
19 http fetch GET 200 https://registry.npmjs.org/graceful-fs 33ms (from cache)
20 http fetch GET 200 https://registry.npmjs.org/browser-sync 41ms (from cache)
21 silly pacote range manifest for @11ty/dependency-tree@^2.0.0 fetched in 51ms
22 silly resolveWithNewModule @11ty/dependency-tree@2.0.0 checking installable status
23 silly pacote range manifest for browser-sync@^2.27.7 fetched in 50ms
24 silly resolveWithNewModule browser-sync@2.27.7 checking installable status
25 silly pacote range manifest for graceful-fs@^4.2.9 fetched in 45ms
26 silly resolveWithNewModule graceful-fs@4.2.9 checking installable status
27 silly pacote range manifest for @iarna/toml@^2.2.5 fetched in 54ms
28 silly resolveWithNewModule @iarna/toml@2.2.5 checking installable status
29 http fetch GET 200 https://registry.npmjs.org/hamljs 11ms (from cache)
30 http fetch GET 200 https://registry.npmjs.org/gray-matter 13ms (from cache)
31 http fetch GET 200 https://registry.npmjs.org/handlebars 11ms (from cache)
32 http fetch GET 200 https://registry.npmjs.org/is-glob 13ms (from cache)
33 silly pacote range manifest for gray-matter@^4.0.3 fetched in 20ms
34 silly resolveWithNewModule gray-matter@4.0.3 checking installable status
35 silly pacote range manifest for hamljs@^0.6.2 fetched in 20ms
36 silly resolveWithNewModule hamljs@0.6.2 checking installable status
37 silly pacote range manifest for handlebars@^4.7.7 fetched in 20ms
38 silly resolveWithNewModule handlebars@4.7.7 checking installable status
39 silly pacote range manifest for is-glob@^4.0.3 fetched in 23ms
40 silly resolveWithNewModule is-glob@4.0.3 checking installable status
41 http fetch GET 200 https://registry.npmjs.org/liquidjs 19ms (from cache)
42 silly pacote range manifest for liquidjs@^9.32.0 fetched in 24ms
43 silly resolveWithNewModule liquidjs@9.35.2 checking installable status
44 http fetch GET 304 https://registry.npmjs.org/chokidar 131ms (from cache)
45 silly pacote range manifest for chokidar@^3.5.2 fetched in 134ms
46 silly resolveWithNewModule chokidar@3.5.3 checking installable status
47 http fetch GET 304 https://registry.npmjs.org/minimist 136ms (from cache)
48 silly pacote range manifest for minimist@^1.2.5 fetched in 139ms
49 silly resolveWithNewModule minimist@1.2.5 checking installable status
50 http fetch GET 304 https://registry.npmjs.org/ejs 279ms (from cache)
51 silly pacote range manifest for ejs@^3.1.6 fetched in 280ms
52 silly resolveWithNewModule ejs@3.1.6 checking installable status
53 http fetch GET 200 https://registry.npmjs.org/multimatch 3ms (from cache)
54 silly pacote range manifest for multimatch@^5.0.0 fetched in 4ms
55 silly resolveWithNewModule multimatch@5.0.0 checking installable status
56 http fetch GET 304 https://registry.npmjs.org/fast-glob 309ms (from cache)
57 http fetch GET 304 https://registry.npmjs.org/debug 312ms (from cache)
58 silly pacote range manifest for fast-glob@^3.2.9 fetched in 314ms
59 silly resolveWithNewModule fast-glob@3.2.11 checking installable status
60 silly pacote range manifest for debug@^4.3.3 fetched in 317ms
61 silly resolveWithNewModule debug@4.3.3 checking installable status
62 http fetch GET 200 https://registry.npmjs.org/normalize-path 6ms (from cache)
63 http fetch GET 200 https://registry.npmjs.org/nunjucks 7ms (from cache)
64 silly pacote range manifest for normalize-path@^3.0.0 fetched in 9ms
65 silly resolveWithNewModule normalize-path@3.0.0 checking installable status
66 silly pacote range manifest for nunjucks@^3.2.3 fetched in 10ms
67 silly resolveWithNewModule nunjucks@3.2.3 checking installable status
68 http fetch GET 304 https://registry.npmjs.org/lodash 258ms (from cache)
69 http fetch GET 200 https://registry.npmjs.org/please-upgrade-node 5ms (from cache)
70 silly pacote range manifest for lodash@^4.17.21 fetched in 260ms
71 silly resolveWithNewModule lodash@4.17.21 checking installable status
72 http fetch GET 200 https://registry.npmjs.org/path-to-regexp 8ms (from cache)
73 silly pacote range manifest for please-upgrade-node@^3.2.0 fetched in 11ms
74 silly resolveWithNewModule please-upgrade-node@3.2.0 checking installable status
75 silly pacote range manifest for path-to-regexp@^6.2.0 fetched in 14ms
76 silly resolveWithNewModule path-to-regexp@6.2.0 checking installable status
77 http fetch GET 200 https://registry.npmjs.org/pretty 9ms (from cache)
78 silly pacote range manifest for pretty@^2.0.0 fetched in 12ms
79 silly resolveWithNewModule pretty@2.0.0 checking installable status
80 http fetch GET 200 https://registry.npmjs.org/pug 10ms (from cache)
81 http fetch GET 200 https://registry.npmjs.org/recursive-copy 8ms (from cache)
82 silly pacote range manifest for pug@^3.0.2 fetched in 19ms
83 silly resolveWithNewModule pug@3.0.2 checking installable status
84 silly pacote range manifest for recursive-copy@^2.0.13 fetched in 18ms
85 silly resolveWithNewModule recursive-copy@2.0.14 checking installable status
86 http fetch GET 200 https://registry.npmjs.org/semver 15ms (from cache)
87 silly pacote range manifest for semver@^7.3.5 fetched in 21ms
88 silly resolveWithNewModule semver@7.3.5 checking installable status
89 http fetch GET 200 https://registry.npmjs.org/slugify 12ms (from cache)
90 http fetch GET 304 https://registry.npmjs.org/kleur 306ms (from cache)
91 silly pacote range manifest for slugify@^1.6.5 fetched in 17ms
92 silly resolveWithNewModule slugify@1.6.5 checking installable status
93 silly pacote range manifest for kleur@^4.1.4  fetched in 310ms
94 silly resolveWithNewModule kleur@4.1.4 checking installable status
95 http fetch GET 304 https://registry.npmjs.org/markdown-it 287ms (from cache)
96 silly pacote range manifest for markdown-it@^12.3.2 fetched in 292ms
97 silly resolveWithNewModule markdown-it@12.3.2 checking installable status
98 http fetch GET 304 https://registry.npmjs.org/moo 115ms (from cache)
99 silly pacote range manifest for moo@^0.5.1 fetched in 118ms
100 silly resolveWithNewModule moo@0.5.1 checking installable status
101 http fetch GET 304 https://registry.npmjs.org/mustache 101ms (from cache)
102 silly pacote range manifest for mustache@^4.2.0 fetched in 103ms
103 silly resolveWithNewModule mustache@4.2.0 checking installable status
104 http fetch GET 304 https://registry.npmjs.org/dependency-graph 571ms (from cache)
105 silly pacote range manifest for dependency-graph@^0.11.0 fetched in 572ms
106 silly resolveWithNewModule dependency-graph@0.11.0 checking installable status
107 http fetch GET 304 https://registry.npmjs.org/luxon 517ms (from cache)
108 silly pacote range manifest for luxon@^2.3.0 fetched in 521ms
109 silly resolveWithNewModule luxon@2.3.1 checking installable status
110 http fetch GET 304 https://registry.npmjs.org/@sindresorhus%2fslugify 831ms (from cache)
111 silly pacote range manifest for @sindresorhus/slugify@^1.1.2 fetched in 832ms
112 silly resolveWithNewModule @sindresorhus/slugify@1.1.2 checking installable status
113 http fetch GET 200 https://registry.npmjs.org/@sindresorhus%2ftransliterate 9ms (from cache)
114 silly fetchPackageMetaData error for @sindresorhus/transliterate@^0.1.1 Unexpected end of JSON input while parsing near '...UF7WlqkflPiuyzKXgZBn4'
115 http fetch GET 304 https://registry.npmjs.org/escape-string-regexp 101ms (from cache)
116 silly pacote range manifest for escape-string-regexp@^4.0.0 fetched in 102ms
117 silly resolveWithNewModule escape-string-regexp@4.0.0 checking installable status
118 timing stage:rollbackFailedOptional Completed in 1ms
119 timing stage:runTopLevelLifecycles Completed in 2049ms
120 silly saveTree <redacted>
120 silly saveTree └─┬ @11ty/eleventy@1.0.0
120 silly saveTree   ├── @11ty/dependency-tree@2.0.0
120 silly saveTree   ├── @iarna/toml@2.2.5
120 silly saveTree   ├─┬ @sindresorhus/slugify@1.1.2
120 silly saveTree   │ └── escape-string-regexp@4.0.0
120 silly saveTree   ├─┬ browser-sync@2.27.7
120 silly saveTree   │ └─┬ chokidar@3.5.3
120 silly saveTree   │   ├── is-glob@4.0.3
120 silly saveTree   │   └── normalize-path@3.0.0
120 silly saveTree   ├── chokidar@3.5.3
120 silly saveTree   ├── debug@4.3.3
120 silly saveTree   ├── dependency-graph@0.11.0
120 silly saveTree   ├── ejs@3.1.6
120 silly saveTree   ├── fast-glob@3.2.11
120 silly saveTree   ├── graceful-fs@4.2.9
120 silly saveTree   ├── gray-matter@4.0.3
120 silly saveTree   ├── hamljs@0.6.2
120 silly saveTree   ├─┬ handlebars@4.7.7
120 silly saveTree   │ └── minimist@1.2.5
120 silly saveTree   ├── is-glob@4.0.3
120 silly saveTree   ├── kleur@4.1.4
120 silly saveTree   ├── liquidjs@9.35.2
120 silly saveTree   ├── lodash@4.17.21
120 silly saveTree   ├── luxon@2.3.1
120 silly saveTree   ├── markdown-it@12.3.2
120 silly saveTree   ├── minimist@1.2.5
120 silly saveTree   ├── moo@0.5.1
120 silly saveTree   ├── multimatch@5.0.0
120 silly saveTree   ├── mustache@4.2.0
120 silly saveTree   ├── normalize-path@3.0.0
120 silly saveTree   ├── nunjucks@3.2.3
120 silly saveTree   ├── path-to-regexp@6.2.0
120 silly saveTree   ├── please-upgrade-node@3.2.0
120 silly saveTree   ├── pretty@2.0.0
120 silly saveTree   ├── pug@3.0.2
120 silly saveTree   ├── recursive-copy@2.0.14
120 silly saveTree   ├── semver@7.3.5
120 silly saveTree   └── slugify@1.6.5
121 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...UF7WlqkflPiuyzKXgZBn4'
121 verbose stack     at JSON.parse (<anonymous>)
121 verbose stack     at parseJson (<redacted>/.nvm/versions/node/v12.20.2/lib/node_modules/npm/node_modules/json-parse-better-errors/index.js:7:17)
121 verbose stack     at <redacted>/.nvm/versions/node/v12.20.2/lib/node_modules/npm/node_modules/node-fetch-npm/src/body.js:96:50
121 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:97:5)
122 verbose cwd <redacted>
123 verbose Darwin 21.3.0
124 verbose argv "<redacted>/.nvm/versions/node/v12.20.2/bin/node" "<redacted>/.nvm/versions/node/v12.20.2/bin/npm" "install" "@11ty/eleventy" "--save-dev"
125 verbose node v12.20.2
126 verbose npm  v6.14.11
127 error Unexpected end of JSON input while parsing near '...UF7WlqkflPiuyzKXgZBn4'
128 verbose exit [ 1, true ]
```

**Comment by zachleat** [comment]
huh—I just went through the getting started on Mac OS 12.2.1 and came out the other side okay

<img width="680" alt="image" src="https://user-images.githubusercontent.com/39355/156870404-31101d13-3ec1-4c48-9049-7f7744a49b96.png">

At what step is that JSON parsing happening? Looks like an npm error to me?

**Comment by zachleat** [comment]
npm install was a little rocky but also came out okay

```
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN eleventy-2262@1.0.0 No description
npm WARN eleventy-2262@1.0.0 No repository field.

added 348 packages from 357 contributors and audited 348 packages in 5.659s

25 packages are looking for funding
  run `npm fund` for details

found 1 high severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
```

**Comment by jrrdnx** [comment]
It does look to be an issue with my local node/npm. Running `npm cache clear --force` and trying again I'm getting either similar errors ("Unexpected end of JSON input while parsing...") or even "integrity checksum failed...", but with various packages.
