### ISSUE TITLE
Compilation crash with customFilter and json default layout

### ISSUE THREAD

**Issue by jaymoulin** [11ty/eleventy#2277]
**Describe the bug**

Eleventy seems to crash when a custom filter is called in a layout and this layout is called in a json file.

**To Reproduce**

.eleventy.js
```js
module.exports = function(eleventyConfig) {
    eleventyConfig.addFilter('hasTag', (arr, str) => arr.includes(str));
};
```

test/test.json
```json
{
  "layout": "layout/layout.njk",
  "title": "Test"
}
```

_includes/layout/layout.njk

```njk
...
{% if item.data.tags | hasTag('test') %}
here
{% endif %}
...
```

test/index.md
```md
Hello World
````

**Expected behavior**
Expected layout to be loaded with the page /test/ but this crash on compilation on test/index.md

**Environment:**

- OS and Version: Ubuntu 20.04
- Eleventy Version : 1.0.0

**Additional context**

Compiles if I remove the layout from test/test.json and add it to test/index.md. Hope this helpstest/index.md

test/index.md
```md
layout: layout/layout.njk
---
Hello World
````

test/test.json
```json
{
  "title": "Test"
}
```

**Comment by pdehaan** [comment]
I can reproduce the error locally, but&hellip; I'm a bit confused and not sure where the bug is (or _if_ it is a bug).

This is the error message that I see when I compile locally on macOS 12.2:

```
> 11ty-2277@1.0.0 build
> eleventy

[11ty] Problem writing Eleventy templates: (more in DEBUG output)
[11ty] > Having trouble writing template: _site/test/index.html

`TemplateWriterWriteError` was thrown
[11ty] > (./_includes/layout/layout.njk)
  TypeError: Cannot read properties of undefined (reading 'includes')

`Template render error` was thrown:
[11ty]     Template render error: (./_includes/layout/layout.njk)
      TypeError: Cannot read properties of undefined (reading 'includes')
        at Object._prettifyError (/private/tmp/11ty-2277/node_modules/nunjucks/src/lib.js:36:11)
        at /private/tmp/11ty-2277/node_modules/nunjucks/src/environment.js:563:19
        at Template.root [as rootRenderFunc] (eval at _compile (/private/tmp/11ty-2277/node_modules/nunjucks/src/environment.js:633:18), <anonymous>:27:3)
        at Template.render (/private/tmp/11ty-2277/node_modules/nunjucks/src/environment.js:552:10)
        at /private/tmp/11ty-2277/node_modules/@11ty/eleventy/src/Engines/Nunjucks.js:484:14
        at new Promise (<anonymous>)
        at /private/tmp/11ty-2277/node_modules/@11ty/eleventy/src/Engines/Nunjucks.js:483:14
        at TemplateLayout.render (/private/tmp/11ty-2277/node_modules/@11ty/eleventy/src/TemplateLayout.js:160:31)
        at async Template.renderPageEntry (/private/tmp/11ty-2277/node_modules/@11ty/eleventy/src/Template.js:842:17)
        at async /private/tmp/11ty-2277/node_modules/@11ty/eleventy/src/Template.js:872:21
[11ty] Wrote 0 files in 0.04 seconds (v1.0.0)
The terminal process "/bin/zsh '-c', 'npm run build'" terminated with exit code: 1.
```

Or more specifically:
> _TypeError: Cannot read properties of undefined (reading 'includes')_

If you're seeing different errors, I might need some more code and/or context.

I believe this is the core issue of the error right here:
```njk
{% if item.data.tags | hasTag('test') %}
here
{% endif %}
```

First, I'm not sure what `item` is referring to here. It isn't defined above anywhere, so it'd be `undefined` for me locally which might explain the error, but I'm not sure if it's defined elsewhere in your layout or main template. But the error I'm seeing locally makes sense since `item.data.tags` would therefore be falsy and the `hasTag` would fail as written since it's trying to call `.includes()` on an `undefined` object.

If I change the _includes/layout/layout.njk file to just use `tags` directly&hellip;:
```njk
{% if tags | hasTag('test') %}
```

And then define the `tags` in my test/index.md front matter, it seems to work:
```yaml
---
tags:
  - page
  - test
---

Hello World
```

And my generated _site/test/index.html will proudly display:

> here

Another small piece of fallback code might be adding default values to your .eleventy.js filter code:

```js
eleventyConfig.addFilter('hasTag', (arr = [], str = "") => arr.includes(str));
```

This defaults the `arr` argument to an empty array, and the `str` argument to an empty string. Apart from this giving me slightly better code hinting in VS Code (a minor win at best), it does give me some safety fallbacks in the case of the `arr` or `str` arguments being falsy/undefined.
PRO: now it wouldn't have build errors.
CON: it might mask some other errors of the `item.data.tags` being invalid and/or `undefined`.

If you have a public repo I can clone, I can try giving it a look tomorrow and we can debug and see if we can reduce it to a smaller test case or see if it's an Ubuntu-vs-macOS issue or something else. Or if it helps I can publish my sample repo, although it's mostly just copy/paste of your code above.

**Comment by pdehaan** [comment]
> I still don't understand this behaviour

I think the gist of it is that `{% if item.data.tags | hasTag('test') %}` will throw these errors if `item.data.tags` isn't defined. So if a page doesn't specify any tags, the `item.data.tags` will be `undefined` and throw the error trying to call `undefined.includes("test")`.
So my workaround was to try setting a default value for `arr` if it isn't defined.
We could probably find another solution if you prefer.
More recent Node versions have an `Array.isArray()` function where we could check if `item.data.tags` is array-like before calling `.includes()`.

**Comment by zachleat** [comment]
I think @pdehaan is right-on here, not every page is guaranteed to have `tags`. So if a template doesn’t define `tags`, you’re basically trying to run `undefined.includes(str)`

> This is an automated message to let you know that a helpful response was posted to your issue and for the health of the repository issue tracker the issue will be closed. This is to help alleviate issues hanging open waiting for a response from the original poster.

> If the response works to solve your problem—great! But if you’re still having problems, do not let the issue’s closing deter you if you have additional questions! Post another comment and we will reopen the issue. Thanks!
