### ISSUE TITLE
“plugin.apply is not a function” error message

### ISSUE THREAD

**Issue by xplosionmind** [11ty/eleventy#2281]
**Describe the bug**
I get this error when building [my website](https://github.com/xplosionmind/tommi.space):

```
❯ DEBUG=Eleventy* npx @11ty/eleventy
  Eleventy:cmd command: eleventy { _: [], quiet: null, version: false, watch: false, dryrun: false, help: false, serve: false, passthroughall: false, incremental: false } +0ms
  Eleventy:EventBus Setting up global EventBus. +0ms
  Eleventy:UserConfig Resetting EleventyConfig to initial values. +0ms
  Eleventy:UserConfig Adding universal filter 'slug' +14ms
  Eleventy:UserConfig Adding universal filter 'slugify' +0ms
  Eleventy:UserConfig Adding universal filter 'url' +1ms
  Eleventy:UserConfig Adding universal filter 'log' +0ms
  Eleventy:UserConfig Adding universal filter 'serverlessUrl' +0ms
  Eleventy:UserConfig Adding universal filter 'getCollectionItem' +0ms
  Eleventy:UserConfig Adding universal filter 'getPreviousCollectionItem' +0ms
  Eleventy:UserConfig Adding universal filter 'getNextCollectionItem' +0ms
  Eleventy:TemplateConfig rootConfig { templateFormats: [ 'liquid',   'ejs', 'md',       'hbs', 'mustache', 'haml', 'pug',      'njk', 'html',     '11ty.js' ], pathPrefix: '/', markdownTemplateEngine: 'liquid', htmlTemplateEngine: 'liquid', dataTemplateEngine: false, htmlOutputSuffix: '-o', jsDataFileSuffix: '.11tydata', keys: { package: 'pkg', layout: 'layout', permalink: 'permalink', permalinkRoot: 'permalinkBypassOutputDir', engineOverride: 'templateEngineOverride', computed: 'eleventyComputed' }, dir: { input: '.', includes: '_includes', data: '_data', output: '_site' }, handlebarsHelpers: {}, nunjucksFilters: {} } +0ms
  Eleventy Setting process.env.ELEVENTY_ROOT: '/Users/tommi/tommi.space' +0ms
  Eleventy:TemplateConfig Merging config with /Users/tommi/tommi.space/.eleventy.js +2ms
[11ty] Eleventy CLI Fatal Error:
[11ty] Error in your Eleventy config file '/Users/tommi/tommi.space/.eleventy.js'.

`EleventyConfigError` was thrown
  Eleventy:EleventyErrorHandler (error stack): EleventyConfigError: Error in your Eleventy config file '/Users/tommi/tommi.space/.eleventy.js'.
  Eleventy:EleventyErrorHandler     at TemplateConfig.mergeConfig (/Users/tommi/tommi.space/node_modules/@11ty/eleventy/src/TemplateConfig.js:238:15)
  Eleventy:EleventyErrorHandler     at TemplateConfig.getConfig (/Users/tommi/tommi.space/node_modules/@11ty/eleventy/src/TemplateConfig.js:117:26)
  Eleventy:EleventyErrorHandler     at new Eleventy (/Users/tommi/tommi.space/node_modules/@11ty/eleventy/src/Eleventy.js:74:39)
  Eleventy:EleventyErrorHandler     at Object.<anonymous> (/Users/tommi/tommi.space/node_modules/@11ty/eleventy/cmd.js:65:14)
  Eleventy:EleventyErrorHandler     at Module._compile (node:internal/modules/cjs/loader:1099:14)
  Eleventy:EleventyErrorHandler     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
  Eleventy:EleventyErrorHandler     at Module.load (node:internal/modules/cjs/loader:975:32)
  Eleventy:EleventyErrorHandler     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
  Eleventy:EleventyErrorHandler     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
  Eleventy:EleventyErrorHandler     at node:internal/main/run_main_module:17:47 +0ms
[11ty] plugin.apply is not a function

`TypeError` was thrown:
  Eleventy:EleventyErrorHandler (error stack): TypeError: plugin.apply is not a function
  Eleventy:EleventyErrorHandler     at MarkdownIt.use (/Users/tommi/tommi.space/node_modules/markdown-it/lib/index.js:497:10)
  Eleventy:EleventyErrorHandler     at Object.<anonymous> (/Users/tommi/tommi.space/.eleventy.js:31:2)
  Eleventy:EleventyErrorHandler     at Module._compile (node:internal/modules/cjs/loader:1099:14)
  Eleventy:EleventyErrorHandler     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
  Eleventy:EleventyErrorHandler     at Module.load (node:internal/modules/cjs/loader:975:32)
  Eleventy:EleventyErrorHandler     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
  Eleventy:EleventyErrorHandler     at Module.require (node:internal/modules/cjs/loader:999:19)
  Eleventy:EleventyErrorHandler     at require (node:internal/modules/cjs/helpers:102:18)
  Eleventy:EleventyErrorHandler     at TemplateConfig.mergeConfig (/Users/tommi/tommi.space/node_modules/@11ty/eleventy/src/TemplateConfig.js:210:23)
  Eleventy:EleventyErrorHandler     at TemplateConfig.getConfig (/Users/tommi/tommi.space/node_modules/@11ty/eleventy/src/TemplateConfig.js:117:26) +0ms
```

**To Reproduce**

1. run `DEBUG=Eleventy* npx @11ty/eleventy`

**Expected behavior**
The website should compile normally

**Environment:**

- OS and Version: MacOS 12.3
- Eleventy Version: 1.0.0

**Comment by pdehaan** [comment]
This looks promising&hellip;

```
`TypeError` was thrown:
  Eleventy:EleventyErrorHandler (error stack): TypeError: plugin.apply is not a function
  Eleventy:EleventyErrorHandler     at MarkdownIt.use (/Users/tommi/tommi.space/node_modules/markdown-it/lib/index.js:497:10)
  Eleventy:EleventyErrorHandler     at Object.<anonymous> (/Users/tommi/tommi.space/.eleventy.js:31:2)
```

That [.eleventy.js:31](https://github.com/xplosionmind/tommi.space/blob/651181faf454e5d1d3129560a0854939c0ace787/.eleventy.js#L31) reference might be pointing to something in the markdown-it config 

```js
.use(require('markdown-it-html5-media'))
```

Otherwise, maybe try disabling your Eleventy plugins one at a time and seeing if its coming from a specific Eleventy plugin (or comment them all out and add them back one at a time).

**Comment by xplosionmind** [comment]
Unfortunately, the build still fails, but there is a new error being thrown:

```
❯ DEBUG=Eleventy* npx @11ty/eleventy
  Eleventy:cmd command: eleventy { _: [], quiet: null, version: false, watch: false, dryrun: false, help: false, serve: false, passthroughall: false, incremental: false } +0ms
  Eleventy:EventBus Setting up global EventBus. +0ms
  Eleventy:UserConfig Resetting EleventyConfig to initial values. +0ms
  Eleventy:UserConfig Adding universal filter 'slug' +12ms
  Eleventy:UserConfig Adding universal filter 'slugify' +0ms
  Eleventy:UserConfig Adding universal filter 'url' +1ms
  Eleventy:UserConfig Adding universal filter 'log' +0ms
  Eleventy:UserConfig Adding universal filter 'serverlessUrl' +0ms
  Eleventy:UserConfig Adding universal filter 'getCollectionItem' +0ms
  Eleventy:UserConfig Adding universal filter 'getPreviousCollectionItem' +0ms
  Eleventy:UserConfig Adding universal filter 'getNextCollectionItem' +0ms
  Eleventy:TemplateConfig rootConfig { templateFormats: [ 'liquid',   'ejs', 'md',       'hbs', 'mustache', 'haml', 'pug',      'njk', 'html',     '11ty.js' ], pathPrefix: '/', markdownTemplateEngine: 'liquid', htmlTemplateEngine: 'liquid', dataTemplateEngine: false, htmlOutputSuffix: '-o', jsDataFileSuffix: '.11tydata', keys: { package: 'pkg', layout: 'layout', permalink: 'permalink', permalinkRoot: 'permalinkBypassOutputDir', engineOverride: 'templateEngineOverride', computed: 'eleventyComputed' }, dir: { input: '.', includes: '_includes', data: '_data', output: '_site' }, handlebarsHelpers: {}, nunjucksFilters: {} } +0ms
  Eleventy Setting process.env.ELEVENTY_ROOT: '/Users/tommi/tommi.space' +0ms
  Eleventy:TemplateConfig Merging config with /Users/tommi/tommi.space/.eleventy.js +2ms
[11ty] Eleventy CLI Fatal Error:
[11ty] Error in your Eleventy config file '/Users/tommi/tommi.space/.eleventy.js'.

`EleventyConfigError` was thrown
  Eleventy:EleventyErrorHandler (error stack): EleventyConfigError: Error in your Eleventy config file '/Users/tommi/tommi.space/.eleventy.js'.
  Eleventy:EleventyErrorHandler     at TemplateConfig.mergeConfig (/Users/tommi/tommi.space/node_modules/@11ty/eleventy/src/TemplateConfig.js:238:15)
  Eleventy:EleventyErrorHandler     at TemplateConfig.getConfig (/Users/tommi/tommi.space/node_modules/@11ty/eleventy/src/TemplateConfig.js:117:26)
  Eleventy:EleventyErrorHandler     at new Eleventy (/Users/tommi/tommi.space/node_modules/@11ty/eleventy/src/Eleventy.js:74:39)
  Eleventy:EleventyErrorHandler     at Object.<anonymous> (/Users/tommi/tommi.space/node_modules/@11ty/eleventy/cmd.js:65:14)
  Eleventy:EleventyErrorHandler     at Module._compile (node:internal/modules/cjs/loader:1099:14)
  Eleventy:EleventyErrorHandler     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
  Eleventy:EleventyErrorHandler     at Module.load (node:internal/modules/cjs/loader:975:32)
  Eleventy:EleventyErrorHandler     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
  Eleventy:EleventyErrorHandler     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
  Eleventy:EleventyErrorHandler     at node:internal/main/run_main_module:17:47 +0ms
[11ty] md is not a constructor

`TypeError` was thrown:
  Eleventy:EleventyErrorHandler (error stack): TypeError: md is not a constructor
  Eleventy:EleventyErrorHandler     at Object.<anonymous> (/Users/tommi/tommi.space/.eleventy.js:32:18)
  Eleventy:EleventyErrorHandler     at Module._compile (node:internal/modules/cjs/loader:1099:14)
  Eleventy:EleventyErrorHandler     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
  Eleventy:EleventyErrorHandler     at Module.load (node:internal/modules/cjs/loader:975:32)
  Eleventy:EleventyErrorHandler     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
  Eleventy:EleventyErrorHandler     at Module.require (node:internal/modules/cjs/loader:999:19)
  Eleventy:EleventyErrorHandler     at require (node:internal/modules/cjs/helpers:102:18)
  Eleventy:EleventyErrorHandler     at TemplateConfig.mergeConfig (/Users/tommi/tommi.space/node_modules/@11ty/eleventy/src/TemplateConfig.js:210:23)
  Eleventy:EleventyErrorHandler     at TemplateConfig.getConfig (/Users/tommi/tommi.space/node_modules/@11ty/eleventy/src/TemplateConfig.js:117:26)
  Eleventy:EleventyErrorHandler     at new Eleventy (/Users/tommi/tommi.space/node_modules/@11ty/eleventy/src/Eleventy.js:74:39) +1ms
```

**Comment by pdehaan** [comment]
> `TypeError` was thrown:
> &nbsp;&nbsp; Eleventy:EleventyErrorHandler (error stack): TypeError: md is not a constructor
> &nbsp;&nbsp; Eleventy:EleventyErrorHandler     at Object.<anonymous> (/Users/tommi/tommi.space/[.eleventy.js:32:18](https://github.com/xplosionmind/tommi.space/blob/045db948b3024f009453d93c4e70380a8c5c63e3/.eleventy.js#L32))
> &nbsp;&nbsp; &hellip;

```js
const markdownIt = require(https://github.com/markdown-it/markdown-it)
const md = markdownIt({
  html: true,
  fence: false
}).disable('fence')
  .use(require(https://github.com/arve0/markdown-it-attrs))
  ...
  .use(require(https://github.com/nzt/markdown-it-mathjax3));
const mdRender = new md();
```

I don't think it's saying `md` isn't a constructor that you initialize w/ `new md()`. You seem to be using this below on [L63](https://github.com/xplosionmind/tommi.space/blob/045db948b3024f009453d93c4e70380a8c5c63e3/.eleventy.js#L62-L64):
```js
  eleventyConfig.addFilter('markdownify', (str) => {
    return mdRender.renderInline(str)
  });
```

Try deleting the L32's `const mdRender = new md();` code and changing L63 above to something like `return md.renderInline(str);` and see if that does the trick.

**Comment by xplosionmind** [comment]
> Try deleting the L32's `const mdRender = new md();` code and changing L63 above to something like `return md.renderInline(str);` and see if that does the trick.

It did the trick indeed! Thanks a lot!
