### ISSUE TITLE
Creating a new JSON file should not throw error when empty (or crash)

### ISSUE THREAD

**Issue by andy-bond** [11ty/eleventy#2299]
**Describe the bug**
While the 11ty-dev-server is running, if you create a new JSON file in the `_data` directory, the server will crash with the following error.

```
[11ty] Watching…
[11ty] File added: src/_data/test.json
[11ty] Eleventy fatal watch error: (more in DEBUG output)
[11ty] /Users/bondandy/Projects/11ty/design-system/src/_data/test.json: Unexpected end of JSON input (via SyntaxError)
[11ty] 
[11ty] Original error stack trace: SyntaxError: /Users/bondandy/Projects/11ty/design-system/src/_data/test.json: Unexpected end of JSON input
[11ty]     at parse (<anonymous>)
[11ty]     at Object.Module._extensions..json (node:internal/modules/cjs/loader:1167:22)
[11ty]     at Module.load (node:internal/modules/cjs/loader:981:32)
[11ty]     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
[11ty]     at Module.require (node:internal/modules/cjs/loader:1005:19)
[11ty]     at require (node:internal/modules/cjs/helpers:102:18)
[11ty]     at TemplateData.getDataValue (/Users/bondandy/Projects/11ty/design-system/node_modules/@11ty/eleventy/src/TemplateData.js:483:25)
[11ty]     at TemplateData.getAllGlobalData (/Users/bondandy/Projects/11ty/design-system/node_modules/@11ty/eleventy/src/TemplateData.js:273:29)
[11ty]     at async TemplateData.getData (/Users/bondandy/Projects/11ty/design-system/node_modules/@11ty/eleventy/src/TemplateData.js:332:24)
[11ty]     at async Eleventy.restart (/Users/bondandy/Projects/11ty/design-system/node_modules/@11ty/eleventy/src/Eleventy.js:270:5)
ERROR: "watch:eleventy" exited with 1.
The terminal process "/bin/zsh '-c', 'npm run start'" terminated with exit code: 1.
```

If you create a JSON file in a different directory, say a file called `docs.json` in a directory called `docs` (to add tags to all files in folder) you will receive the same error but will be able to continue. That being said, I would rather it not show an error at all and simply ignore empty JSON files (error if they are malformed, sure).

```
[11ty] Watching…
[11ty] File added: src/docs/docs.json
[11ty] Problem writing Eleventy templates: (more in DEBUG output)
[11ty] /Users/bondandy/Projects/11ty/design-system/src/docs/docs.json: Unexpected end of JSON input (via SyntaxError)
[11ty] 
[11ty] Original error stack trace: SyntaxError: /Users/bondandy/Projects/11ty/design-system/src/docs/docs.json: Unexpected end of JSON input
[11ty]     at parse (<anonymous>)
[11ty]     at Object.Module._extensions..json (node:internal/modules/cjs/loader:1167:22)
[11ty]     at Module.load (node:internal/modules/cjs/loader:981:32)
[11ty]     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
[11ty]     at Module.require (node:internal/modules/cjs/loader:1005:19)
[11ty]     at require (node:internal/modules/cjs/helpers:102:18)
[11ty]     at TemplateData.getDataValue (/Users/bondandy/Projects/11ty/design-system/node_modules/@11ty/eleventy/src/TemplateData.js:483:25)
[11ty]     at TemplateData.combineLocalData (/Users/bondandy/Projects/11ty/design-system/node_modules/@11ty/eleventy/src/TemplateData.js:362:36)
[11ty]     at TemplateData.getTemplateDirectoryData (/Users/bondandy/Projects/11ty/design-system/node_modules/@11ty/eleventy/src/TemplateData.js:373:37)
[11ty]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[11ty] Wrote 0 files in 0.01 seconds (v2.0.0-canary.4)
```

**To Reproduce**

1. Using 11ty 2.0.0-canary.4, run server with `eleventy --serve`
2. Create a new file in the data directory `_data/test.json`
3. Crash
4. Repeat in a different folder and see error but no crash

**Expected behavior**
No error for empty JSON file - error for malformed JSON (ideally no crashing)

**Environment:**

- OS and Version: Mac, MacOS 12.3
- Eleventy Version: 2.0.0-canary-4

**Comment by pdehaan** [comment]
But isn't an empty JSON file technically malformed JSON?

I ran some quick tests using `require()`, `fs-extra.readJsonSync()`, and `json5` and they all seemed to throw errors if I tried to read an empty JSON file (ie: <kbd>touch empty.json</kbd>).

```js
require("json5/lib/register");

const fse = require("fs-extra");

try {
  // SyntaxError: /private/tmp/json-test/empty.json: Unexpected end of JSON input
  const emptyRequire = require("./empty.json");
  console.log({emptyRequire});
} catch (err) {
  console.error("1.", err.message);
}

try {
  // SyntaxError: ./empty.json: Unexpected end of JSON input
  const emptyFse = fse.readJsonSync("./empty.json");
  console.log(emptyFse);
} catch (err) {
  console.error("2.", err.message);
}

try {
  // SyntaxError: /private/tmp/json-test/empty.json5: JSON5: invalid end of input at 1:1
  const emptyJson5 = require("./empty.json5");
  console.log({emptyJson5});
} catch (err) {
  console.error("3.", err.message);
}

try {
  const emptyJson = safeLoad("./empty.json");
  // { emptyJson: {} }
  console.log({emptyJson});
} catch (err) {
  console.error("4.", err.message);
}

function safeLoad(p) {
  try {
    return require(p);
  } catch (err) {
    return {};
  }
}
```

```sh
1. /private/tmp/json-test/empty.json: Unexpected end of JSON input
2. ./empty.json: Unexpected end of JSON input
3. /private/tmp/json-test/empty.json5: JSON5: invalid end of input at 1:1
{ emptyJson: {} }
```

I'm not too familiar w/ the internals of 11ty's global data files vs directory data files, but it sounds like directory data files might have a slightly better developer experience. Wrapping the JSON loading in a `try..catch` and returning an empty object on error might be safer.

**Comment by pdehaan** [comment]
Baby steps... 
Might have a solution, but it isn't super great.

```js
const json5 = require("json5");

module.exports = eleventyConfig => {
  eleventyConfig.addDataExtension("json5", contents => json5.parse(contents));
  ...
};
```

It seems if I use json5 as a [custom data file format](https://www.11ty.dev/docs/data-custom/#custom-data-file-formats) (also see https://www.npmjs.com/package/json5 for details). It seems to handle empty files a bit better when I use `json5.parse()`, plus you can add comments to your JSON files, unquoted keys, etc&hellip;
But the downside is that you'd have to rename your data files to .json5 (or whatever). I tried overriding the .json extension, but that didn't work out for me; see #2300.

Anyways, not sure if it helps or not, but I learned something today, so it was a good day.

**Comment by andy-bond** [comment]
I totally understand if it this isn't something that is fixable - just thought it might trip others up the first time they create a global data file.

I'm not familiar with 11ty internals, but before trying to read as JSON, could you first use `fse.readFileSync` if the filetype is `.json` and then check for empty / no content? If there is content, proceed with JSON processing however it normally works. If there is no content, throw warning and skip loading the file as JSON? 

Definitely adds a step when processing which might not be ideal though. Thanks for investigating regardless!

**Comment by zachleat** [comment]
I agree that this change would be a DX improvement! 👍🏻 I think it makes the most sense to add this to the enhancement queue

> This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

> View [the enhancement backlog here](https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+). Don’t forget to upvote the top comment with 👍!

**Comment by zachleat** [comment]
This is shipping with 2.0.0-canary.19, thank you!

Fixed by https://github.com/11ty/eleventy/commit/7c03471742d650d79e60343bea07c9dfb8ecff1f
