### ISSUE TITLE
Getting an error when using a overriding an existing template language

### ISSUE THREAD

**Issue by StarfallProjects** [11ty/eleventy#2385]
**Describe the bug**

I am trying to use [Markdoc](https://markdoc.io/) with Eleventy. I _think_ I have set up the override correctly - at [this point](https://github.com/StarfallProjects/eleventy-markdoc/blob/main/.eleventy.js#L19) I'm seeing the expected HTML output. 

Overriding an existing template language seems to result in an error: 

```
 Having trouble rendering liquid template ./src/index.md (via TemplateContentRenderError)
[11ty] 2. Having trouble compiling template ./src/index.md (via TemplateContentCompileError)
[11ty] 3. Cannot use 'in' operator to search for 'then' in <article><h1>Homepage</h1><p>Some very <strong>normal</strong> 
markdown</p></article> (via TypeError)
[11ty]
[11ty] Original error stack trace: TypeError: Cannot use 'in' operator to search for 'then' in <article><h1>Homepage</h1><p>Some very <strong>normal</strong> markdown</p></article>
[11ty]     at CustomEngine.compile (C:\Users\debor\Desktop\code\eleventy-markdoc\node_modules\@11ty\eleventy\src\Engines\Custom.js:171:18)
```

According to [the docs](https://www.11ty.dev/docs/languages/custom/#overriding-an-existing-template-language), 'overriding md opts-out of the default pre-processing by another template language', which I assumed meant it opts out of processing with Liquid/njk etc.? However, even when I try explicitly setting `markdownTemplateEngine: false`, I still get an error:

```
[11ty] 1. Having trouble rendering md template ./src/index.md (via TemplateContentRenderError)
[11ty] 2. Having trouble compiling template ./src/index.md (via TemplateContentCompileError)
[11ty] 3. Cannot use 'in' operator to search for 'then' in <article><h1>Homepage</h1><p>Some very <strong>normal</strong> 
markdown</p></article> (via TypeError)
[11ty]
[11ty] Original error stack trace: TypeError: Cannot use 'in' operator to search for 'then' in <article><h1>Homepage</h1><p>Some very <strong>normal</strong> markdown</p></article>
[11ty]     at CustomEngine.compile (C:\Users\debor\Desktop\code\eleventy-markdoc\node_modules\@11ty\eleventy\src\Engines\Custom.js:171:18)
```

**To Reproduce**

1. Clone my example repo: https://github.com/StarfallProjects/eleventy-markdoc
2. `npm i`
3. `npm start` (runs `dev`, uses cross-env to ensure Windows behaves itself) or `npm run build`

**Expected behavior**
Output a simple built site, with a single HTML file

**Screenshots**

**Environment:**

- OS and Version: Windows 10
- Eleventy Version: 1.0.1
- Node.js Version: 16.13.2

**Comment by AleksandrHovhannisyan** [comment]
[Here's the relevant line of code in Custom.js](https://github.com/11ty/eleventy/blob/5def7d8c101f66b2c3bb7c0ff77b4cb9cde9bcbd/src/Engines/Custom.js#L171), in case it helps folks debug this.

I believe `compile` is supposed to return a function rather than the compiled result directly. This would explain why the erroring code tries to treat your compiled HTML as a function. Try changing your return statement to `return () => html` and see if that works.

**Comment by StarfallProjects** [comment]
You legend! I misunderstood the docs - I thought the function was just there because the example is checking a data setting for which parser to use, and so ditched it as I just want to always use Markdoc. Thank you!
