### ISSUE TITLE
Edge shortcode with njk templating

### ISSUE THREAD

**Issue by ryangittings** [11ty/eleventy#2390]
**Describe the bug**
When using the following:

```
{% edge "njk,md" %}
<form action="{{ page.url }}#all" method="GET" class="measure-short">
<input type="search" name="q" placeholder="Search" value="">
</form>
{% endedge %}
```

I seem to keep getting the error:

```
RenderError: (unknown path)
  TypeError: Cannot read properties of undefined (reading 'length'), file:liquid, line:798, col:19
    at RenderError2.LiquidError2 [as constructor] (https://cdn.11ty.dev/edge@1.0.1/eleventy-edge.js:32221:28)
    at new RenderError2 (https://cdn.11ty.dev/edge@1.0.1/eleventy-edge.js:32259:28)
    at Render2.<anonymous> (https://cdn.11ty.dev/edge@1.0.1/eleventy-edge.js:35402:49)
    at step (https://cdn.11ty.dev/edge@1.0.1/eleventy-edge.js:31222:23)
    at Object.throw (https://cdn.11ty.dev/edge@1.0.1/eleventy-edge.js:31169:18)
    at https://cdn.11ty.dev/edge@1.0.1/eleventy-edge.js:33816:31
    at async EleventyEdge.handleResponse (https://cdn.11ty.dev/edge@1.0.1/eleventy-edge.js:37199:19)
    at async Object.default [as function] (file:///Users/ryangittings/Builds/netacea/netlify/edge-functions/eleventy-edge.js:27:12)
    at async FunctionChain.runFunction (https://6270f39aacac8b000a2f84f4--edge-bootstrap.netlify.app/bootstrap/function_chain.ts:152:24)
    at async FunctionChain.run (https://6270f39aacac8b000a2f84f4--edge-bootstrap.netlify.app/bootstrap/function_chain.ts:131:22)
```

**To Reproduce**

1. Use templating above

**Expected behavior**
No error

**Screenshots**

**Environment:**

- OS and Version: `Mac 12.3.1`
- Eleventy Version: `2.0.0-canary.11`
- Netlify CLI Version: `netlify-cli/10.3.1 darwin-arm64 node-v17.5.0`

**Comment by zachleat** [comment]
What’s the file extension of the original file? Having trouble reproducing this one

**Comment by ryangittings** [comment]
It's a nunjucks file 🙂

**Comment by zachleat** [comment]
Unfortunately with the information provided I can’t reproduce

![image](https://user-images.githubusercontent.com/39355/168872311-e165ee4d-9673-4df5-8fc7-c46738636af5.png)

![image](https://user-images.githubusercontent.com/39355/168872379-f1c9e48c-1684-46ec-be1e-90f7d67cf152.png)

![image](https://user-images.githubusercontent.com/39355/168872415-4a49d90f-0289-4712-a26c-0b94cbd550d8.png)

Can you attach a reduced test case?

**Comment by ryangittings** [comment]
How strange - can't recreate now... Will close for now! :)

**Comment by mark-reason** [comment]
I was experiencing the same issue when I had an include within my {% edge %} tags.

**Comment by TixieBorg** [comment]
@mark-reason I'm facing the same issue when including a njk file or importing a macro. Did you find a solution in the mean time?
