### ISSUE TITLE
this.defaultRenderer is not a function (via TypeError)

### ISSUE THREAD

**Issue by sebthom** [11ty/eleventy#2408]
**Describe the bug**
I am trying to follow https://www.11ty.dev/docs/languages/custom/#overriding-an-existing-template-language but I am getting `this.defaultRenderer is not a function`

**To Reproduce**
```js
module.exports = function(eleventyConfig) {
    const config = {
        dir: {
            output: "dist",
            input: "site",
            includes: "_includes",
            data: "data"
        },
        passthrougFileCopy: true,
        dataTemplateEngine: "njk",
        htmlTemplateEngine: "njk",
        markdownTemplateEngine: "njk",
        templateFormats: ["css", "html", "md", "njk"]
    }
    eleventyConfig.addExtension("css", {
        outputFileExtension: "css",
        compile: function(inputContent, inputPath) {
            const cssContent = this.defaultRenderer(inputContent) // results in: this.defaultRenderer is not a function
            const modifiedContent = cssContent; // modify CSS here...
            return (data) => {
                return modifiedContent 
            }
        }
    })
    return config
}
```
**Expected behavior**
this.defaultRenderer is accessible in the compile function.

**Screenshots**
```
> npm run build

> website@1.0.0 build
> rimraf dist && npx @11ty/eleventy

[11ty] Problem writing Eleventy templates: (more in DEBUG output)
[11ty] 1. Having trouble rendering css template ./site/css/base.css (via TemplateContentRenderError)
[11ty] 2. Having trouble compiling template ./site/css/base.css (via TemplateContentCompileError)
[11ty] 3. this.defaultRenderer is not a function (via TypeError)
[11ty]
[11ty] Original error stack trace: TypeError: this.defaultRenderer is not a function
[11ty]     at Object.compile (D:\website\.eleventy.js:78:42)
[11ty]     at CustomEngine.compile (D:\website\node_modules\@11ty\eleventy\src\Engines\Custom.js:166:7)
[11ty]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[11ty] Copied 9 files / Wrote 0 files in 0.15 seconds (v2.0.0-canary.11)
```
**Environment:**

- OS and Version: Windows 10
- Eleventy Version 2.0.0-canary.11

**Additional context**

**Comment by zachleat** [comment]
I don’t think `defaultRenderer` is available to the outer compile function, only in the inner function.

```
    eleventyConfig.addExtension("css", {
        outputFileExtension: "css",
        compile: function(inputContent, inputPath) {
            return function(data) {
                const cssContent = this.defaultRenderer(inputContent);
                const modifiedContent = cssContent; // modify CSS here...
                return modifiedContent;
            }
        }
    })
```

Now, that being said—should it be? 😅

**Comment by zachleat** [comment]
> This is an automated message to let you know that a helpful response was posted to your issue and for the health of the repository issue tracker the issue will be closed. This is to help alleviate issues hanging open waiting for a response from the original poster.

> If the response works to solve your problem—great! But if you’re still having problems, do not let the issue’s closing deter you if you have additional questions! Post another comment and we will reopen the issue. Thanks!
