### ISSUE TITLE
The "path" argument must be of type string. Received null (via TypeError)

### ISSUE THREAD

**Issue by xplosionmind** [11ty/eleventy#2419]
**Describe the bug**
Build fails because of this error, and it is not specified in which page it occurs.

**To Reproduce**

1. run `DEBUG=Eleventy* npx @11ty/eleventy` in [quitsocialmedia.club](https://codeberg.org/tommi/quitsocialmedia.club)

**Expected behavior**
Build should be successful or at least tell me where the problem is.

**Environment:**

- OS and Version: MacOS 12.4
- Eleventy Version: 1.0.1

[**Logs**](https://paste.yunohost.org/raw/faqebayufi)

**Comment by pdehaan** [comment]
Q: Did this ever work and broke recently? Or is this a brand new site?
I got past one error, but am not getting a handful of other errors w/ 404.html (possibly because it's the first template Eleventy tries to write).

**Comment by xplosionmind** [comment]
> is this a brand new site?

Yes, sorry I did not mention that. I am gradually debugging the website, transitioning from Jekyll.

**Comment by pdehaan** [comment]
Here's my git diff so far. 

```diff
diff --git a/.eleventy.js b/.eleventy.js
index b65bbd9..3c96fc9 100644
--- a/.eleventy.js
+++ b/.eleventy.js
@@ -81,6 +81,11 @@ module.exports = function(eleventyConfig) {
 			});
 	});
 
+		eleventyConfig.addShortcode("seo", (content) => "<!-- seo here -->");
+		eleventyConfig.addFilter("date_to_xmlschema", (date) => `<!-- date_to_xmlschema:${date}-->`)
+		eleventyConfig.addFilter("encode_email", (email) => `<!-- encode_email:${email}-->`)
+		eleventyConfig.addFilter("uri_encode", uri => `<!--uri_encode:${uri}-->`)
+		eleventyConfig.addFilter("date_to_long_string", date => `<!--date_to_long_string:${date}-->`)
 
 	// Scss //
 	eleventyConfig.addWatchTarget('styles');
diff --git a/404.html b/404.html
index d5dd4fb..2b70e38 100644
--- a/404.html
+++ b/404.html
@@ -1,6 +1,6 @@
 ---
 permalink: /404.html
-layout: full
+layout: full.html
 sitemap: false
 title: 404
 link: 'javascript:history.go(-1)'
diff --git a/layouts/full.html b/layouts/full.html
index a5e88ea..89affaf 100644
--- a/layouts/full.html
+++ b/layouts/full.html
@@ -1,9 +1,6 @@
----
-layout: ~
----
 <!DOCTYPE html>
 <html>
-{% include head.html %}
+{% include "head.html" %}
 	<style>
 		body {
 			background: var(--primary);
diff --git a/pages/Home.html b/pages/Home.html
index fca7e82..2ae2e70 100644
--- a/pages/Home.html
+++ b/pages/Home.html
@@ -69,7 +69,7 @@ toc: false
 		<h2 class='title'>Website pages</h2>
 		<p>An overview of all the pages in the website:</p>
 		<ul>
-			{% for p in  %}
+			{% for p in collections.all %}
 				{% if p.lang == page.lang %}
 					{% unless p.url contains '.json' or p.url contains '.csv' or p.url contains '.css' or p.url contains '.txt' or p.title contains '404' or p.url contains '.xml' or p.title == nil or p.title == 'Home' %}
 						<li><a href='{{ p.url }}' title='{{ p.title }}'>{{ p.title }}</a> - {{ p.description }}</li>
diff --git a/pages/index.html b/pages/index.html
index 1696f73..3dccdfe 100644
--- a/pages/index.html
+++ b/pages/index.html
@@ -1,9 +1,9 @@
 ---
-layout: ~
+layout: ""
 permalink: /
 title: Quit Social Media
 ---
-<html lang='en'>{% include head.html %}<body>
+<html lang='en'>{% include "head.html" %}<body>
 	<div class='landing vertical flex'>
 		<h1>Quit Social Media</h1>
 		<div class='flex'>
```

It's still not building, but maybe gets you closer. Here's the error I'm currently seeing:

```
[11ty] Problem writing Eleventy templates:
[11ty] Output conflict: multiple input files are writing to `www/l-1000/index.html`. Use distinct `permalink` values to resolve this conflict.
[11ty]   1. ./redirect.njk
[11ty]   2. ./redirect.njk (via DuplicatePermalinkOutputError)
  Eleventy:EleventyErrorHandler (error stack): DuplicatePermalinkOutputError: Output conflict: multiple input files are writing to `www/l-1000/index.html`. Use distinct `permalink` values to resolve this conflict.
  Eleventy:EleventyErrorHandler   1. ./redirect.njk
  Eleventy:EleventyErrorHandler   2. ./redirect.njk
  Eleventy:EleventyErrorHandler
  Eleventy:EleventyErrorHandler
  Eleventy:EleventyErrorHandler     at TemplateMap.checkForDuplicatePermalinks (/private/tmp/quitsocialmedia.club/node_modules/@11ty/eleventy/src/TemplateMap.js:656:13)
  Eleventy:EleventyErrorHandler     at TemplateMap.cache (/private/tmp/quitsocialmedia.club/node_modules/@11ty/eleventy/src/TemplateMap.js:365:10)
  Eleventy:EleventyErrorHandler     at processTicksAndRejections (node:internal/process/task_queues:96:5)
  Eleventy:EleventyErrorHandler     at async TemplateWriter._createTemplateMap (/private/tmp/quitsocialmedia.club/node_modules/@11ty/eleventy/src/TemplateWriter.js:244:5)
  Eleventy:EleventyErrorHandler     at async TemplateWriter.generateTemplates (/private/tmp/quitsocialmedia.club/node_modules/@11ty/eleventy/src/TemplateWriter.js:277:5)
  Eleventy:EleventyErrorHandler     at async TemplateWriter.write (/private/tmp/quitsocialmedia.club/node_modules/@11ty/eleventy/src/TemplateWriter.js:323:23)
  Eleventy:EleventyErrorHandler     at async Eleventy.executeBuild (/private/tmp/quitsocialmedia.club/node_modules/@11ty/eleventy/src/Eleventy.js:1003:13) +0ms
```

**Comment by xplosionmind** [comment]
Thank you, I managed to go through and fix most of the errors. The website now builds.

I am closing the issue even though it was not figured out the specific error generating the error message in the issue subject.
