### ISSUE TITLE
EleventyEdgePlugin failing on Netlify Build with 2.0.0-canary.11

### ISSUE THREAD

**Issue by stevenmilstein** [11ty/eleventy#2426]
**Describe the bug**
EleventyEdgePlugin recently started failing on Netlify Build. 
```
4:13:54 PM: ​
4:13:54 PM: ────────────────────────────────────────────────────────────────
4:13:54 PM:   2. Edge Functions bundling                                    
4:13:54 PM: ────────────────────────────────────────────────────────────────
4:13:54 PM: ​
4:13:54 PM: Packaging Edge Functions from netlify/edge-functions directory:
4:13:54 PM:  - eleventy-edge
4:14:00 PM: error: Uncaught (in promise) Error: Module not found "eleventy:edge".
4:14:00 PM:       var ret = new Error(getStringFromWasm0(arg0, arg1));
4:14:00 PM:                 ^
4:14:00 PM:     at __wbg_new_55259b13834a484c (https://deno.land/x/eszip@v0.18.0/eszip_wasm.generated.js:389:17)
4:14:00 PM:     at <anonymous> (https://deno.land/x/eszip@v0.18.0/eszip_wasm_bg.wasm:1:64387)
4:14:00 PM:     at <anonymous> (https://deno.land/x/eszip@v0.18.0/eszip_wasm_bg.wasm:1:1546059)
4:14:00 PM:     at <anonymous> (https://deno.land/x/eszip@v0.18.0/eszip_wasm_bg.wasm:1:1978661)
4:14:00 PM:     at __wbg_adapter_24 (https://deno.land/x/eszip@v0.18.0/eszip_wasm.generated.js:213:6)
4:14:00 PM:     at real (https://deno.land/x/eszip@v0.18.0/eszip_wasm.generated.js:197:14)
4:14:00 PM: ​
4:14:00 PM: ────────────────────────────────────────────────────────────────
4:14:00 PM:   Bundling of Function "undefined" failed                       
4:14:00 PM: ────────────────────────────────────────────────────────────────
4:14:00 PM: ​
4:14:00 PM:   Error message
4:14:00 PM:   Command failed with exit code 1: /opt/build/repo/.netlify/plugins/deno-cli/deno run --allow-all --quiet /opt/buildhome/node-deps/node_modules/@netlify/edge-bundler/deno/bundle.ts {"basePath":"/opt/build/repo/","destPath":"/tmp/edge-62a102c79a1057006cfc1668/047e43a6-0bb9-496d-8ee9-3f5a9ea97f37.eszip","functions":[{"name":"eleventy-edge","path":"/opt/build/repo/netlify/edge-functions/eleventy-edge.js"}]} (https://ntl.fyi/exit-code-1)
4:14:00 PM:   error: Uncaught (in promise) Error: Module not found "eleventy:edge".
4:14:00 PM:         var ret = new Error(getStringFromWasm0(arg0, arg1));
4:14:00 PM:                   ^
4:14:00 PM:       at __wbg_new_55259b13834a484c (https://deno.land/x/eszip@v0.18.0/eszip_wasm.generated.js:389:17)
4:14:00 PM:       at <anonymous> (https://deno.land/x/eszip@v0.18.0/eszip_wasm_bg.wasm:1:64387)
4:14:00 PM:       at <anonymous> (https://deno.land/x/eszip@v0.18.0/eszip_wasm_bg.wasm:1:1546059)
4:14:00 PM:       at <anonymous> (https://deno.land/x/eszip@v0.18.0/eszip_wasm_bg.wasm:1:1978661)
4:14:00 PM:       at __wbg_adapter_24 (https://deno.land/x/eszip@v0.18.0/eszip_wasm.generated.js:213:6)
4:14:00 PM:       at real (https://deno.land/x/eszip@v0.18.0/eszip_wasm.generated.js:197:14)
4:14:00 PM: ​
4:14:00 PM:   Error location
4:14:00 PM:   While bundling Function "undefined"
4:14:00 PM: ​
4:14:00 PM:   Resolved config
4:14:00 PM:   build:
4:14:00 PM:     command: npx @11ty/eleventy --input=src
4:14:00 PM:     commandOrigin: config
4:14:00 PM:     edge_functions: /opt/build/repo/netlify/edge-functions
```

**To Reproduce**
Deploy https://github.com/11ty/demo-eleventy-edge to Netlify

**Comment by stevenmilstein** [comment]
Thanks to @saneef on Discord for the timely reply and **workaround**!

![image](https://user-images.githubusercontent.com/66161/173202963-f49dc593-a5b3-4260-aa7a-bd9f6fa60a2f.png)

https://discord.com/channels/741017160297611315/985202827867598868/985214847685914736

**netlify/edge-functions/eleventy-edge.js**
```
//import { EleventyEdge } from "eleventy:edge";
import { EleventyEdge } from "https://cdn.11ty.dev/edge@1.0.1/eleventy-edge.js";
```

**Comment by zachleat** [comment]
Reproduced 😳 looking!

**Comment by zachleat** [comment]
There might have been a regression with import maps. We use them in Eleventy Edge like this: https://docs.netlify.com/netlify-labs/experimental-features/edge-functions/create-integration/#generate-declarations

Still investigating!

**Comment by zachleat** [comment]
Unfortunately, I wasn’t able to get to the bottom of this one but the regression seems to be fixed now—can you confirm?

**Comment by stevenmilstein** [comment]
The regression is fixed.
`import { EleventyEdge } from "eleventy:edge";` is working again

Thank you!
