### ISSUE TITLE
Edge plugin causing Netlify dev CLI to fail

### ISSUE THREAD

**Issue by mark-reason** [11ty/eleventy#2666]
Hi, I have a problem when trying to use the Edge plugin, when I add the plugin like this:

```
const { EleventyEdgePlugin } = require("@11ty/eleventy");

module.exports = (config) => {
  config.addPlugin(EleventyEdgePlugin);

  return {
    markdownTemplateEngine: "njk",
    dataTemplateEngine: "njk",
    htmlTemplateEngine: "njk",
    dir: {
      input: "src",
      output: "dist",
    },
  };
};
```

and then run 'netlify dev' i get the following error:

```
TypeError: Expected a string
    at module.exports (/Users/username/.nvm/versions/node/v18.12.1/lib/node_modules/netlify-cli/node_modules/@netlify/edge-bundler/node_modules/glob-to-regexp/index.js:3:11)
    at getRegularExpression (file:///Users/username/.nvm/versions/node/v18.12.1/lib/node_modules/netlify-cli/node_modules/@netlify/edge-bundler/dist/node/manifest.js:47:31)
    at file:///Users/username/.nvm/versions/node/v18.12.1/lib/node_modules/netlify-cli/node_modules/@netlify/edge-bundler/dist/node/manifest.js:14:25
    at Array.forEach (<anonymous>)
    at Module.generateManifest (file:///Users/username/.nvm/versions/node/v18.12.1/lib/node_modules/netlify-cli/node_modules/@netlify/edge-bundler/dist/node/manifest.js:9:18)
    at EdgeFunctionsRegistry.matchURLPath (/Users/username/.nvm/versions/node/v18.12.1/lib/node_modules/netlify-cli/src/lib/edge-functions/registry.cjs:284:41)
    at /Users/username/.nvm/versions/node/v18.12.1/lib/node_modules/netlify-cli/src/lib/edge-functions/proxy.cjs:112:68
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async onRequest (/Users/username/.nvm/versions/node/v18.12.1/lib/node_modules/netlify-cli/src/utils/proxy.cjs:476:33)

Node.js v18.12.1
```

I'm running Eleventy version 2.0.0-canary.16 and netlify-cli version 12.2.7

**Comment by AleksandrHovhannisyan** [comment]
I was getting this the other day too, but I don't recall how I fixed it. I think it may have been one of two issues:

1. I forgot to add at least one source file to my project (e.g., `index.html`), or
2. I was trying to set a cookie value to something other than a string.

I suspect it may be the first one in this case. What does your project structure look like?

**Comment by mark-reason** [comment]
Thanks @AleksandrHovhannisyan, that led me to resolving the issue. It was because I had a non-eleventy edge function in the 'edge-functions' folder.
