### ISSUE TITLE
Using permalink: false generates error message in build log

### ISSUE THREAD

**Issue by paulrobertlloyd** [11ty/eleventy#282]
I am using the following directory data:

```json
{
  "permalink": false,
  "tags": ["testimonial"],
  "type": "testimonial",
  "vocab": "review"
}
```

correctly prevents files in this directory being written to disk. However, it also produces an error in the console:

```
Error writing templates: (full stack in DEBUG output)
> Having trouble writing template: false (TemplateWriterWriteError)
> outputPath.includes is not a function (TypeError)
```

The full debug output:

```
  Eleventy:EleventyErrorHandler Problem writing Eleventy templates: +0ms
  Eleventy:EleventyErrorHandler TemplateLayoutPathResolver directory does not exist for layout/page: ./_includes (Error) +0ms
  Eleventy:EleventyErrorHandler (log stack): Error: TemplateLayoutPathResolver directory does not exist for layout/page: ./_includes
  Eleventy:EleventyErrorHandler     at TemplateLayoutPathResolver.findFileName (/Users/paulrobertlloyd/Sites/v4.paulrobertlloyd.com/node_modules/@11ty/eleventy/src/TemplateLayoutPathResolver.js:75:13)
  Eleventy:EleventyErrorHandler     at TemplateLayoutPathResolver.init (/Users/paulrobertlloyd/Sites/v4.paulrobertlloyd.com/node_modules/@11ty/eleventy/src/TemplateLayoutPathResolver.js:40:28)
  Eleventy:EleventyErrorHandler     at new TemplateLayoutPathResolver (/Users/paulrobertlloyd/Sites/v4.paulrobertlloyd.com/node_modules/@11ty/eleventy/src/TemplateLayoutPathResolver.js:14:10)
  Eleventy:EleventyErrorHandler     at new TemplateLayout (/Users/paulrobertlloyd/Sites/v4.paulrobertlloyd.com/node_modules/@11ty/eleventy/src/TemplateLayout.js:14:24)
  Eleventy:EleventyErrorHandler     at Function.getTemplate (/Users/paulrobertlloyd/Sites/v4.paulrobertlloyd.com/node_modules/@11ty/eleventy/src/TemplateLayout.js:37:16)
  Eleventy:EleventyErrorHandler     at Template.getData (/Users/paulrobertlloyd/Sites/v4.paulrobertlloyd.com/node_modules/@11ty/eleventy/src/Template.js:198:37) +1ms
Processed 0 files in 1.29 seconds
```

Not quite sure why it’s complaining about templates and layouts, as none are set (that I know of) or required. 🤔

**Comment by paulrobertlloyd** [comment]
Closing duplicate of #283 (summited multiple times during GitHub’s October 22nd downtime).
