### ISSUE TITLE
permalink: false generates error in build log

### ISSUE THREAD

**Issue by paulrobertlloyd** [11ty/eleventy#283]
Using the following directory data:

```json
{
  "permalink": false,
  "tags": ["testimonial"]
}
```

correctly prevents content in this directory being written to disk. However, the following error is shown in the build log:

```
Error writing templates: (full stack in DEBUG output)
> Having trouble writing template: false (TemplateWriterWriteError)
> outputPath.includes is not a function (TypeError)
Copied 3 items and Processed 0 files in 5.07 seconds
``` 

The relevant portion of the debug log reports the following:

```
  Eleventy:EleventyErrorHandler Problem writing Eleventy templates: +0ms
  Eleventy:EleventyErrorHandler TemplateLayoutPathResolver directory does not exist for layout/page: ./_includes (Error) +0ms
  Eleventy:EleventyErrorHandler (log stack): Error: TemplateLayoutPathResolver directory does not exist for layout/page: ./_includes
  Eleventy:EleventyErrorHandler     at TemplateLayoutPathResolver.findFileName (/Users/paulrobertlloyd/Sites/v4.paulrobertlloyd.com/node_modules/@11ty/eleventy/src/TemplateLayoutPathResolver.js:75:13)
  Eleventy:EleventyErrorHandler     at TemplateLayoutPathResolver.init (/Users/paulrobertlloyd/Sites/v4.paulrobertlloyd.com/node_modules/@11ty/eleventy/src/TemplateLayoutPathResolver.js:40:28)
  Eleventy:EleventyErrorHandler     at new TemplateLayoutPathResolver (/Users/paulrobertlloyd/Sites/v4.paulrobertlloyd.com/node_modules/@11ty/eleventy/src/TemplateLayoutPathResolver.js:14:10)
  Eleventy:EleventyErrorHandler     at new TemplateLayout (/Users/paulrobertlloyd/Sites/v4.paulrobertlloyd.com/node_modules/@11ty/eleventy/src/TemplateLayout.js:14:24)
  Eleventy:EleventyErrorHandler     at Function.getTemplate (/Users/paulrobertlloyd/Sites/v4.paulrobertlloyd.com/node_modules/@11ty/eleventy/src/TemplateLayout.js:37:16)
  Eleventy:EleventyErrorHandler     at Template.getData (/Users/paulrobertlloyd/Sites/v4.paulrobertlloyd.com/node_modules/@11ty/eleventy/src/Template.js:198:37) +0ms
Processed 0 files in 1.66 seconds
```

Not entirely sure why its complaining about templates and layouts, as none are required given these files are not being generated. Adding a layout value however results in the same error. 🤔

Note also how its reported that no files have been processed, but in fact these errors are ignored, and all files go on to be generated correctly.

**Comment by paulrobertlloyd** [comment]
So, it would seem we can probably file this one under ’user error’!

The culprit was to be found in my config file, where I was defining this linter:

```js
eleventy.addLinter('json-feed', (content, inputPath, outputPath) => {
  if (outputPath.includes('feed.json')) {
    ...
  }
});
```

That the template mentioned above didn’t write any files to disk meant outputPath wouldn’t always return a value. Rewriting the condition as `if (outputPath && outputPath.includes('feed.json'))` fixed the issue. Closing!
