### ISSUE TITLE
Hashtag in markdown code element makes deploy fail

### ISSUE THREAD

**Issue by Yetenol** [11ty/eleventy#2894]
### Operating system

Linux

### Eleventy

2.0.0

### Describe the bug

When any of my notes contains a certain valid markdown code element, the deploy fails at this file.

Valid markdown code element:

```
`\textbf{#1}`
```

11ty Error message:
```
[11ty] Problem writing Eleventy templates: (more in DEBUG output)
[11ty] 1. Having trouble rendering njk template ./src/site/notes/README.md (via TemplateContentRenderError)
[11ty] 2. (./src/site/notes/README.md)
[11ty]   Error: expected end of comment, got end of file (via Template render error)
[11ty]
[11ty] Original error stack trace: Template render error: (./src/site/notes/README.md)
[11ty]   Error: expected end of comment, got end of file
[11ty]     at Object._prettifyError (/opt/build/repo/node_modules/nunjucks/src/lib.js:36:11)
[11ty]     at Template.init (/opt/build/repo/node_modules/nunjucks/src/environment.js:511:19)
[11ty]     at Template.Obj (/opt/build/repo/node_modules/nunjucks/src/object.js:62:15)
[11ty]     at new Template (/opt/build/repo/node_modules/nunjucks/src/environment.js:478:18)
[11ty]     at Nunjucks.compile (/opt/build/repo/node_modules/@11ty/eleventy/src/Engines/Nunjucks.js:429:14)
[11ty]     at Markdown.compile (/opt/build/repo/node_modules/@11ty/eleventy/src/Engines/Markdown.js:68:28)
[11ty]     at TemplateRender.getCompiledTemplate (/opt/build/repo/node_modules/@11ty/eleventy/src/TemplateRender.js:269:26)
[11ty]     at Template.compile (/opt/build/repo/node_modules/@11ty/eleventy/src/TemplateContent.js:355:42)
[11ty]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[11ty]     at async Template._render (/opt/build/repo/node_modules/@11ty/eleventy/src/TemplateContent.js:479:16)
```

Complete Netlify error message:
- see personal workflow in Reproduction steps

<details>
  <summary>Click to expand</summary>

```
12:32:33 AM: Waiting for other deploys from your team to complete. Check the queue: https://app.netlify.com/teams/netlify-f3jzcuw/builds
12:32:49 AM: build-image version: f14e228ec2dbb3d6f5ee2f499343e1468b859b97 (focal)
12:32:49 AM: buildbot version: f14e228ec2dbb3d6f5ee2f499343e1468b859b97
12:32:49 AM: Fetching cached dependencies
12:32:49 AM: Starting to download cache of 142.7MB
12:32:50 AM: Finished downloading cache in 403ms
12:32:50 AM: Starting to extract cache
12:32:51 AM: Finished extracting cache in 816ms
12:32:51 AM: Finished fetching cache in 1.281s
12:32:51 AM: Starting to prepare the repo for build
12:32:51 AM: Preparing Git Reference refs/heads/main
12:32:52 AM: Parsing package.json dependencies
12:32:53 AM: Starting build script
12:32:53 AM: Installing dependencies
12:32:53 AM: Python version set to 2.7
12:32:53 AM: Started restoring cached Node.js version
12:32:54 AM: Finished restoring cached Node.js version
12:32:54 AM: v16.19.1 is already installed.
12:32:54 AM: Now using node v16.19.1 (npm v8.19.3)
12:32:54 AM: Enabling Node.js Corepack
12:32:54 AM: Started restoring cached build plugins
12:32:54 AM: Finished restoring cached build plugins
12:32:54 AM: Attempting Ruby version 2.7.2, read from environment
12:32:55 AM: Using Ruby version 2.7.2
12:32:55 AM: Using PHP version 8.0
12:32:55 AM: Started restoring cached corepack dependencies
12:32:55 AM: Finished restoring cached corepack dependencies
12:32:55 AM: No npm workspaces detected
12:32:55 AM: Started restoring cached node modules
12:32:55 AM: Finished restoring cached node modules
12:32:56 AM: Installing npm packages using npm version 8.19.3
12:32:57 AM: up to date, audited 512 packages in 976ms
12:32:57 AM: 85 packages are looking for funding
12:32:57 AM:   run `npm fund` for details
12:32:57 AM: 8 vulnerabilities (5 high, 3 critical)
12:32:57 AM: Some issues need review, and may require choosing
12:32:57 AM: a different dependency.
12:32:57 AM: Run `npm audit` for details.
12:32:57 AM: npm packages installed
12:32:57 AM: Started restoring cached go cache
12:32:57 AM: Finished restoring cached go cache
12:32:57 AM: go version go1.19.7 linux/amd64
12:32:57 AM: Detected 1 framework(s)
12:32:57 AM: "eleventy" at version "2.0.0"
12:32:57 AM: Section completed: initializing
12:32:59 AM: ​
12:32:59 AM:   Netlify Build                                                 
12:32:59 AM: ────────────────────────────────────────────────────────────────
12:32:59 AM: ​
12:32:59 AM: ❯ Version
12:32:59 AM:   @netlify/build 29.6.4
12:32:59 AM: ​
12:32:59 AM: ❯ Flags
12:32:59 AM:   baseRelDir: true
12:32:59 AM:   buildId: 64091b11d21e2b0008fdf25a
12:32:59 AM:   deployId: 64091b11d21e2b0008fdf25c
12:32:59 AM: ​
12:32:59 AM: ❯ Current directory
12:32:59 AM:   /opt/build/repo
12:32:59 AM: ​
12:32:59 AM: ❯ Config file
12:32:59 AM:   /opt/build/repo/netlify.toml
12:32:59 AM: ​
12:32:59 AM: ❯ Context
12:32:59 AM:   production
12:32:59 AM: ​
12:32:59 AM:   1. build.command from netlify.toml                            
12:32:59 AM: ────────────────────────────────────────────────────────────────
12:32:59 AM: ​
12:32:59 AM: $ npm install && npm run build
12:33:00 AM: up to date, audited 512 packages in 647ms
12:33:00 AM: 85 packages are looking for funding
12:33:00 AM:   run `npm fund` for details
12:33:00 AM: 8 vulnerabilities (5 high, 3 critical)
12:33:00 AM: Some issues need review, and may require choosing
12:33:00 AM: a different dependency.
12:33:00 AM: Run `npm audit` for details.
12:33:00 AM: > web@1.0.0 build
12:33:00 AM: > npm-run-all get-theme build:*
12:33:00 AM: > web@1.0.0 get-theme
12:33:00 AM: > node src/site/get-theme.js
12:33:00 AM: > web@1.0.0 build:eleventy
12:33:00 AM: > cross-env ELEVENTY_ENV=prod NODE_OPTIONS=--max-old-space-size=4096 eleventy
12:33:04 AM: [11ty] Problem writing Eleventy templates: (more in DEBUG output)
12:33:04 AM: [11ty] 1. Having trouble rendering njk template ./src/site/notes/README.md (via TemplateContentRenderError)
12:33:04 AM: [11ty] 2. (./src/site/notes/README.md)
12:33:04 AM: [11ty]   Error: expected end of comment, got end of file (via Template render error)
12:33:04 AM: [11ty]
12:33:04 AM: [11ty] Original error stack trace: Template render error: (./src/site/notes/README.md)
12:33:04 AM: [11ty]   Error: expected end of comment, got end of file
12:33:04 AM: [11ty]     at Object._prettifyError (/opt/build/repo/node_modules/nunjucks/src/lib.js:36:11)
12:33:04 AM: [11ty]     at Template.init (/opt/build/repo/node_modules/nunjucks/src/environment.js:511:19)
12:33:04 AM: [11ty]     at Template.Obj (/opt/build/repo/node_modules/nunjucks/src/object.js:62:15)
12:33:04 AM: [11ty]     at new Template (/opt/build/repo/node_modules/nunjucks/src/environment.js:478:18)
12:33:04 AM: [11ty]     at Nunjucks.compile (/opt/build/repo/node_modules/@11ty/eleventy/src/Engines/Nunjucks.js:429:14)
12:33:04 AM: [11ty]     at Markdown.compile (/opt/build/repo/node_modules/@11ty/eleventy/src/Engines/Markdown.js:68:28)
12:33:04 AM: [11ty]     at TemplateRender.getCompiledTemplate (/opt/build/repo/node_modules/@11ty/eleventy/src/TemplateRender.js:269:26)
12:33:04 AM: [11ty]     at Template.compile (/opt/build/repo/node_modules/@11ty/eleventy/src/TemplateContent.js:355:42)
12:33:04 AM: [11ty]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
12:33:04 AM: [11ty]     at async Template._render (/opt/build/repo/node_modules/@11ty/eleventy/src/TemplateContent.js:479:16)
12:33:04 AM: [11ty] Copied 20 files / Wrote 0 files in 3.46 seconds (v2.0.0)
12:33:05 AM: Failed during stage 'building site': Build script returned non-zero exit code: 2 (https://ntl.fyi/exit-code-2)
12:33:04 AM: ERROR: "build:eleventy" exited with 1.
12:33:04 AM: ​
12:33:04 AM:   "build.command" failed                                        
12:33:04 AM: ────────────────────────────────────────────────────────────────
12:33:04 AM: ​
12:33:04 AM:   Error message
12:33:04 AM:   Command failed with exit code 1: npm install && npm run build (https://ntl.fyi/exit-code-1)
12:33:04 AM: ​
12:33:04 AM:   Error location
12:33:04 AM:   In build.command from netlify.toml:
12:33:04 AM:   npm install && npm run build
12:33:04 AM: ​
12:33:04 AM:   Resolved config
12:33:04 AM:   build:
12:33:04 AM:     command: npm install && npm run build
12:33:04 AM:     commandOrigin: config
12:33:04 AM:     publish: /opt/build/repo/dist
12:33:04 AM:     publishOrigin: config
12:33:04 AM:   functionsDirectory: /opt/build/repo/netlify/functions
12:33:04 AM:   redirects:
12:33:05 AM:     - from: /api/*      status: 200      to: /.netlify/functions/:splat    - from: /*      status: 404      to: /404  redirectsOrigin: configCaching artifacts
12:33:05 AM: Started saving node modules
12:33:05 AM: Finished saving node modules
12:33:05 AM: Started saving build plugins
12:33:05 AM: Finished saving build plugins
12:33:05 AM: Started saving corepack cache
12:33:05 AM: Finished saving corepack cache
12:33:05 AM: Started saving pip cache
12:33:05 AM: Finished saving pip cache
12:33:05 AM: Started saving emacs cask dependencies
12:33:05 AM: Finished saving emacs cask dependencies
12:33:05 AM: Started saving maven dependencies
12:33:05 AM: Finished saving maven dependencies
12:33:05 AM: Started saving boot dependencies
12:33:05 AM: Finished saving boot dependencies
12:33:05 AM: Started saving rust rustup cache
12:33:05 AM: Finished saving rust rustup cache
12:33:05 AM: Started saving go dependencies
12:33:05 AM: Finished saving go dependencies
12:33:05 AM: Build failed due to a user error: Build script returned non-zero exit code: 2
12:33:05 AM: Failing build: Failed to build site
12:33:05 AM: Finished processing build request in 15.87s
```

</details>

### Reproduction steps

1. Successfully build your site
2. Add the valid markdown code element shown above to any markdown file
3. Build the site
4. Throws ERROR: expected end of comment, got end of file

Personal workflow:
1. Write some notes in Obsidian
2. Push the notes to Netlify using Obsidian's [Digital Garden](https://github.com/oleeskild/obsidian-digital-garden) plugin
3. Netlify automatically builds the site using the complementing [Eleventy Build Script](https://github.com/oleeskild/digitalgarden)
4. Successful site build is deployed to my personal domain
5. Add the valid markdown code element shown above to any note in Obsidian 
6. Publish this note
7. Netlify deploy fails in Eleventy framework at this file throwing ERROR: expected end of comment, got end of file

### Expected behavior

The site should be able to build successfully even though a markdown file contains 
```
`\textbf{#1}`
```

**Comment by j-f1** [comment]
I believe this is because Eleventy parses Markdown files as Liquid first before interpreting the Markdown syntax. Liquid has `{# ... #}` syntax for comments which is probably what it is expecting here. If you don’t want this, you can [set `markdownTemplateEngine: false`](https://www.11ty.dev/docs/config/#default-template-engine-for-markdown-files) to disable this behavior.

**Comment by zachleat** [comment]
Just for the record here, the offending template is using Nunjucks! So a few corrections:

* Liquid’s comments are `{% comment %}` and not `{# #}`.
* But both Nunjucks and Liquid have `{% raw %}` so I think that’s probably the least intrusive option!

**Comment by Yetenol** [comment]
Isn't it the idea of markdown's code element, the indented code block and the fenced codeblock to render a verbatim listing of source code thus to verbatim every character within,  similar to LaTeX's `\lstinline` and `\begin{lstlisting}` or the as you mentioned Liquid's and Nunjucks's `{% raw %}`. If I put a HTML Unicode code or a HTML tags inside a code element, it isn't passed as HTML either, so I would except any arbitrary comment indicators of another language to be verbatimed/escaped es well. To put a verbatim tag inside another verbatim tag sounds unintuitive and hard to diagnose for me. 

I ran into a similar problem when embedding a markdown file using `![[filename]]` that contained a code element of a single dollar sign <code>`$`</code> which i avoided why writing

```
<code>&#36;</code>
```

but that might not be Eleventy's fault. 

Is it possible to make Eleventy treat the content of markdown code elements as a raw source code listing automatically, since that is it's intended purpose. For instance, I imagine to automatically surround code elements with Liquid's and Nunjucks's raw tags `{% raw %}` while converted markdown to their language.

**Comment by j-f1** [comment]
If eleventy did that, how would it handle this document?

```nunjucks
{% set example = "`" %}
{{ example }}\textbf{#1}{{ example }}
```

(Commenting this because I once tried to implement an auto-formatter for Handlebars that formatted both the HTML and the Handlebars, and it turns out that there really isn’t a good way to parse both the template language and the underlying document at the same time. I don’t think it would make sense for Eleventy to try to handle this behavior, since no matter how hard it tries, it will be unintuitive / wrong in some cases)

**Comment by zachleat** [comment]
Ah to be clear, this has come up before. We don’t want to auto-raw code in markdown because folks rely on it to generate code, too. Just as an example, consider folks that want to store their code samples in a separate folder and include them to be syntax highlighted:

````html
```
{% include "my-code-sample.njk" %}
```
````

I could see a different case for `<code>` I suppose but I’m not sure it’s worth a breaking change for this specifically at this point, given it’s only come up a few times so far.

**Comment by zachleat** [comment]
> This is an automated message to let you know that a helpful response was posted to your issue and for the health of the repository issue tracker the issue will be closed. This is to help alleviate issues hanging open waiting for a response from the original poster.

> If the response works to solve your problem—great! But if you’re still having problems, do not let the issue’s closing deter you if you have additional questions! Post another comment and we will reopen the issue. Thanks!
