### ISSUE TITLE
Support workspaces for passthrough copying

### ISSUE THREAD

**Issue by dougy-fresh** [11ty/eleventy#3017]
### Is your feature request related to a problem? Please describe.

At work, we vend a component library for use on various sites. To make it easier for developers, we host all of the sites we vend, as well as the web components, in a single repository. I'd like to add a new workspace to our monorepo that contains an eleventy static site that consumes these web components. I followed the instructions from the assets documentation here: https://www.11ty.dev/docs/assets/ , including adding this passthroughCopy:

```js
module.exports = function(eleventyConfig) {
	eleventyConfig.addPassthroughCopy("node_modules/@skilljar/web-components/dist/index.js");
};
```

However, that's not where the file is located! Even though I've declared `@skilljar/web-components` as a dependency, the dependency has been hoisted to the root of the monorepo because everyone in the monorepo is using the same version, and workspaces de-dupe dependencies when hoisting them. And, because `addPassthroughCopy` only allows me to serve files from directories that are descendants of my eleventy root, I can't workaround this without setting up a bundler.

### Describe the solution you'd like

I would like to request a new method, something like `eleventyConfig.addRequiredCopy("@skilljar/web-components");` which would use the same logic as `require` -- search each `node_modules` for the package with the matching name, and then copy the script that is listed in the `main` field of `package.json` or `index.js`, as appropriate. We would _not_ attempt to bundle code; the only difference to `addPassthroughCopy` would be how the file is located, not how it is copied.

### Describe alternatives you've considered

Setting up a bundler! It would totally work; I'm just hoping we can introduce a lower-friction solution. If not, and bundlers are the suggested solution, that's totally okay!

### Additional context

Here's the full error I get when I try to start my site

```shell
» npm start

> @skilljar/docs-site@0.0.1 start
> eleventy --serve

[11ty] Error with passthrough copy: (more in DEBUG output)
[11ty] 1. Having trouble copying '../web-components/dist/index.js' (via TemplatePassthroughManagerCopyError)
[11ty] 2. Error copying passthrough files: Destination is not in the site output directory. Check your passthrough paths. (via TemplatePassthroughError)
[11ty] 3. Destination is not in the site output directory. Check your passthrough paths. (via TemplatePassthroughError)
[11ty]
[11ty] Original error stack trace: TemplatePassthroughError: Destination is not in the site output directory. Check your passthrough paths.
[11ty]     at TemplatePassthrough.copy (/Users/dougwade/code/monorepo/node_modules/@11ty/eleventy/src/TemplatePassthrough.js:166:9)
[11ty]     at /Users/dougwade/code/monorepo/node_modules/@11ty/eleventy/src/TemplatePassthrough.js:235:19
[11ty]     at Array.map (<anonymous>)
[11ty]     at TemplatePassthrough.write (/Users/dougwade/code/monorepo/node_modules/@11ty/eleventy/src/TemplatePassthrough.js:222:28)
[11ty] Unhandled rejection in promise: (more in DEBUG output)
[11ty] 1. Having trouble copying (via EleventyPassthroughCopyError)
[11ty] 2. Having trouble copying '../web-components/dist/index.js' (via TemplatePassthroughManagerCopyError)
[11ty] 3. Error copying passthrough files: Destination is not in the site output directory. Check your passthrough paths. (via TemplatePassthroughError)
[11ty] 4. Destination is not in the site output directory. Check your passthrough paths. (via TemplatePassthroughError)
[11ty]
[11ty] Original error stack trace: TemplatePassthroughError: Destination is not in the site output directory. Check your passthrough paths.
[11ty]     at TemplatePassthrough.copy (/Users/dougwade/code/monorepo/node_modules/@11ty/eleventy/src/TemplatePassthrough.js:166:9)
[11ty]     at /Users/dougwade/code/monorepo/node_modules/@11ty/eleventy/src/TemplatePassthrough.js:235:19
[11ty]     at Array.map (<anonymous>)
[11ty]     at TemplatePassthrough.write (/Users/dougwade/code/monorepo/node_modules/@11ty/eleventy/src/TemplatePassthrough.js:222:28)
[11ty] Writing build/index.html from ./index.html (liquid)
[11ty] Problem writing Eleventy templates: (more in DEBUG output)
[11ty] 1. Having trouble copying (via EleventyPassthroughCopyError)
[11ty] 2. Having trouble copying '../web-components/dist/index.js' (via TemplatePassthroughManagerCopyError)
[11ty] 3. Error copying passthrough files: Destination is not in the site output directory. Check your passthrough paths. (via TemplatePassthroughError)
[11ty] 4. Destination is not in the site output directory. Check your passthrough paths. (via TemplatePassthroughError)
[11ty]
[11ty] Original error stack trace: TemplatePassthroughError: Destination is not in the site output directory. Check your passthrough paths.
[11ty]     at TemplatePassthrough.copy (/Users/dougwade/code/monorepo/node_modules/@11ty/eleventy/src/TemplatePassthrough.js:166:9)
[11ty]     at /Users/dougwade/code/monorepo/node_modules/@11ty/eleventy/src/TemplatePassthrough.js:235:19
[11ty]     at Array.map (<anonymous>)
[11ty]     at TemplatePassthrough.write (/Users/dougwade/code/monorepo/node_modules/@11ty/eleventy/src/TemplatePassthrough.js:222:28)
[11ty] Wrote 0 files in 0.03 seconds (v2.0.1)
[11ty] A promise rejection was handled asynchronously: (more in DEBUG output)
[11ty] (No error message provided) (via undefined)
[11ty]
[11ty] Original error stack trace:
npm ERR! Lifecycle script `start` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: @skilljar/docs-site@0.0.1
npm ERR!   at location: /Users/dougwade/code/monorepo/packages/docs-site
```

**Comment by zachleat** [comment]
The home base for this is #4015!
