### ISSUE TITLE
11ty --serve no longer works

### ISSUE THREAD

**Issue by pracplayopen** [11ty/eleventy#3061]
### Operating system

ubuntu 21.2

### Eleventy

1.0.1

### Describe the bug

We can still push changes to our site through our hosting providers, but the 11ty local dev server no longer works.

Depending on where it's run from  (either project root or project-root/src), it will either hang or emit errors.   The errors seem to change depending on when it's run.   Sometimes the errors have to do with parsing pages that use 'inspect', sometimes it's for postDate.   

The strange thing is that we 1) never got these errors before  2) the pages it's complaining about have not changed since we set 11ty up and 3)  we haven't upgraded 11ty since we set it up.

Everything still works well deploying via cloud, but it's a little concerning.

Here's some example output:

```
$ npx @11ty/eleventy --version
1.0.1
$ node --version
v14.21.3
```

postDate ERROR
```
$ npx @11ty/eleventy --serve
[11ty] Problem writing Eleventy templates: (more in DEBUG output)
[11ty] 1. Having trouble rendering liquid template ./pages/news.html (via TemplateContentRenderError)
[11ty] 2. undefined filter: postDate, file:./pages/news.html, line:17, col:36, file:./pages/news.html, line:8, col:1 (via ParseError)
[11ty] 3. undefined filter: postDate, file:./pages/news.html, line:17, col:36 (via ParseError)
[11ty] 4. undefined filter: postDate (via AssertionError)
[11ty] 
[11ty] Original error stack trace: AssertionError: undefined filter: postDate
[11ty]     at new AssertionError (/home/webdev/work/src/11ty/ppcom0/node_modules/liquidjs/dist/liquid.node.cjs.js:1080:28)
[11ty]     at assert (/home/webdev/work/src/11ty/ppcom0/node_modules/liquidjs/dist/liquid.node.cjs.js:1115:15)
[11ty]     at FilterMap.get (/home/webdev/work/src/11ty/ppcom0/node_modules/liquidjs/dist/liquid.node.cjs.js:4346:9)
[11ty]     at /home/webdev/work/src/11ty/ppcom0/node_modules/liquidjs/dist/liquid.node.cjs.js:2506:52
[11ty]     at Array.map (<anonymous>)
[11ty]     at new Value (/home/webdev/work/src/11ty/ppcom0/node_modules/liquidjs/dist/liquid.node.cjs.js:2504:48)
[11ty]     at new Output (/home/webdev/work/src/11ty/ppcom0/node_modules/liquidjs/dist/liquid.node.cjs.js:4189:23)
[11ty]     at Parser.parseToken (/home/webdev/work/src/11ty/ppcom0/node_modules/liquidjs/dist/liquid.node.cjs.js:4258:24)
[11ty]     at ParseStream.parseToken (/home/webdev/work/src/11ty/ppcom0/node_modules/liquidjs/dist/liquid.node.cjs.js:4268:80)
[11ty]     at ParseStream.start (/home/webdev/work/src/11ty/ppcom0/node_modules/liquidjs/dist/liquid.node.cjs.js:2372:33)

```

Content producing the postDate error:

```
$ cat pages/news.html 
---
layout: base.njk
title: news
pagination:
  data: collections.news
  size: 5
  reverse: true
permalink: "news/{% if pagination.pageNumber>0 %}page/{{ pagination.pageNumber }}{% endif %}/index.html"
---
<div class="content blog-page">
<div class="gridContainer gridContainer content">
<div class="row">
<div class="col-xs-12 col-sm-12">
<div class="post-list row">


{%- for post in pagination.items -%}
<div class="post-list-item col-xs-12 space-bottom col-sm-12 {% if forloop.first == true %} col-md-12" data-masonry-width="col-md-12"> {% else %} col-md-6" data-masonry-width="col-md-6"> {% endif %}
<div class="blog-post card post type-post status-publish format-standard hentry">
<div class="post-content">
<div class="col-xs-12 col-padding col-padding-xs">
	<h3 class="post-title">
		<a href="{{ post.url }}">{{ post.data.title }}</a>
	</h3>
	<div class="post-meta small muted space-bottom-small">
                <span class="date">{{ post.date | postDate }}</span>
        </div>
	<div class="post-excerpt">
		{% excerpt post %}
	</div>
</div>
</div>
</div>
</div>
{%- endfor -%}

</div>
</div>
</div>
</div>
</div>
{% if pagination.pageLinks.length > 1 %}
<div class="navigation pagination" role="navigation">
<div class="nav-links">
  {% if pagination.previousPageLink %}
	<div class="prev-navigation"><a href="{{ pagination.previousPageHref | url }}"><i class="fa fa-angle-left" aria-hidden="true"></i></a></div>
  {% endif %}

<div class="numbers-navigation">
{% if pagination.pageNumber >1 %}
	<a class="page-numbers" href="{{ pagination.firstPageHref | url }}">1</a>
{% endif %}
{% assign max_last_page = pagination.pages.length | minus:2 %}
{% assign max_first_page = pagination.pageNumber | minus: 2 %}
{% if pagination.pageNumber > 3 or max_first_page > 0 %}
	<span class="page-numbers dots">...</span>
{% endif %}
{% if pagination.previousPageLink %}
	<a class="page-numbers" href="{{ pagination.previousPageHref | url }}">{{ pagination.pageNumber }}</a>
{% endif %}
        <span aria-current="page" class="page-numbers current">{{ pagination.pageNumber | plus: 1 }}</span>
{% if pagination.nextPageLink %}
        <a class="page-numbers" href="{{ pagination.nextPageHref | url }}">{{ pagination.pageNumber | plus: 2 }}</a>
{% endif %}
{% if pagination.pageNumber < max_last_page %}
	<span class="page-numbers dots">...</span>
{% endif %}
{% if pagination.pageNumber < max_last_page and pagination.pages.length > 3 %}
        <a class="page-numbers" href="{{ pagination.lastPageHref | url }}">{{ pagination.pages.length }}</a>
{% endif %}
</div>

  {% if pagination.nextPageLink %}
	<div class="prev-navigation"><a href="{{ pagination.nextPageHref | url }}"><i class="fa fa-angle-right" aria-hidden="true"></i></a></div>
  {% endif %}

</div>
</div>
{% endif %}
```

here's an undefined inspect filter error:

```
$ npx @11ty/eleventy --serve
[11ty] 2. undefined filter: inspect, file:./pages/testit.html, line:11, col:1 (via ParseError)
  Eleventy:EleventyErrorHandler (error stack): undefined filter: inspect, file:./pages/testit.html, line:11, col:1
  Eleventy:EleventyErrorHandler     9| 
  Eleventy:EleventyErrorHandler    10| <code>
  Eleventy:EleventyErrorHandler >> 11| {{ collections.posts | inspect }}
  Eleventy:EleventyErrorHandler    12| </code>
  Eleventy:EleventyErrorHandler    13| 
  Eleventy:EleventyErrorHandler    14| 
  Eleventy:EleventyErrorHandler ParseError: undefined filter: inspect, file:./pages/testit.html, line:11, col:1
  Eleventy:EleventyErrorHandler     at ParseError.LiquidError [as constructor] (/home/webdev/work/src/11ty/ppcom0/node_modules/liquidjs/dist/liquid.node.cjs.js:1004:28)
  Eleventy:EleventyErrorHandler     at new ParseError (/home/webdev/work/src/11ty/ppcom0/node_modules/liquidjs/dist/liquid.node.cjs.js:1032:28)
  Eleventy:EleventyErrorHandler     at Parser.parseToken (/home/webdev/work/src/11ty/ppcom0/node_modules/liquidjs/dist/liquid.node.cjs.js:4263:19)
  Eleventy:EleventyErrorHandler     at Parser.parseTokens (/home/webdev/work/src/11ty/ppcom0/node_modules/liquidjs/dist/liquid.node.cjs.js:4248:33)
  Eleventy:EleventyErrorHandler     at Parser.parse (/home/webdev/work/src/11ty/ppcom0/node_modules/liquidjs/dist/liquid.node.cjs.js:4242:21)
  Eleventy:EleventyErrorHandler     at Liquid.parse (/home/webdev/work/src/11ty/ppcom0/node_modules/liquidjs/dist/liquid.node.cjs.js:4372:28)
  Eleventy:EleventyErrorHandler     at Liquid.compile (/home/webdev/work/src/11ty/ppcom0/node_modules/@11ty/eleventy/src/Engines/Liquid.js:230:28)
  Eleventy:EleventyErrorHandler     at Html.compile (/home/webdev/work/src/11ty/ppcom0/node_modules/@11ty/eleventy/src/Engines/Html.js:16:28)
  Eleventy:EleventyErrorHandler     at TemplateRender.getCompiledTemplate (/home/webdev/work/src/11ty/ppcom0/node_modules/@11ty/eleventy/src/TemplateRender.js:239:26)
  Eleventy:EleventyErrorHandler     at Template.compile (/home/webdev/work/src/11ty/ppcom0/node_modules/@11ty/eleventy/src/TemplateContent.js:296:42)
  Eleventy:EleventyErrorHandler From AssertionError: undefined filter: inspect
  Eleventy:EleventyErrorHandler     at new AssertionError (/home/webdev/work/src/11ty/ppcom0/node_modules/liquidjs/dist/liquid.node.cjs.js:1080:28)
  Eleventy:EleventyErrorHandler     at assert (/home/webdev/work/src/11ty/ppcom0/node_modules/liquidjs/dist/liquid.node.cjs.js:1115:15)
  Eleventy:EleventyErrorHandler     at FilterMap.get (/home/webdev/work/src/11ty/ppcom0/node_modules/liquidjs/dist/liquid.node.cjs.js:4346:9)
  Eleventy:EleventyErrorHandler     at /home/webdev/work/src/11ty/ppcom0/node_modules/liquidjs/dist/liquid.node.cjs.js:2506:52
  Eleventy:EleventyErrorHandler     at Array.map (<anonymous>)
  Eleventy:EleventyErrorHandler     at new Value (/home/webdev/work/src/11ty/ppcom0/node_modules/liquidjs/dist/liquid.node.cjs.js:2504:48)
  Eleventy:EleventyErrorHandler     at new Output (/home/webdev/work/src/11ty/ppcom0/node_modules/liquidjs/dist/liquid.node.cjs.js:4189:23)
  Eleventy:EleventyErrorHandler     at Parser.parseToken (/home/webdev/work/src/11ty/ppcom0/node_modules/liquidjs/dist/liquid.node.cjs.js:4258:24)
  Eleventy:EleventyErrorHandler     at Parser.parseTokens (/home/webdev/work/src/11ty/ppcom0/node_modules/liquidjs/dist/liquid.node.cjs.js:4248:33)
  Eleventy:EleventyErrorHandler     at Parser.parse (/home/webdev/work/src/11ty/ppcom0/node_modules/liquidjs/dist/liquid.node.cjs.js:4242:21) +0ms
[11ty] 3. undefined filter: inspect (via AssertionError)
  Eleventy:EleventyErrorHandler (error stack): AssertionError: undefined filter: inspect
  Eleventy:EleventyErrorHandler     at new AssertionError (/home/webdev/work/src/11ty/ppcom0/node_modules/liquidjs/dist/liquid.node.cjs.js:1080:28)
  Eleventy:EleventyErrorHandler     at assert (/home/webdev/work/src/11ty/ppcom0/node_modules/liquidjs/dist/liquid.node.cjs.js:1115:15)
  Eleventy:EleventyErrorHandler     at FilterMap.get (/home/webdev/work/src/11ty/ppcom0/node_modules/liquidjs/dist/liquid.node.cjs.js:4346:9)
  Eleventy:EleventyErrorHandler     at /home/webdev/work/src/11ty/ppcom0/node_modules/liquidjs/dist/liquid.node.cjs.js:2506:52
  Eleventy:EleventyErrorHandler     at Array.map (<anonymous>)
  Eleventy:EleventyErrorHandler     at new Value (/home/webdev/work/src/11ty/ppcom0/node_modules/liquidjs/dist/liquid.node.cjs.js:2504:48)
  Eleventy:EleventyErrorHandler     at new Output (/home/webdev/work/src/11ty/ppcom0/node_modules/liquidjs/dist/liquid.node.cjs.js:4189:23)
  Eleventy:EleventyErrorHandler     at Parser.parseToken (/home/webdev/work/src/11ty/ppcom0/node_modules/liquidjs/dist/liquid.node.cjs.js:4258:24)
  Eleventy:EleventyErrorHandler     at Parser.parseTokens (/home/webdev/work/src/11ty/ppcom0/node_modules/liquidjs/dist/liquid.node.cjs.js:4248:33)
  Eleventy:EleventyErrorHandler     at Parser.parse (/home/webdev/work/src/11ty/ppcom0/node_modules/liquidjs/dist/liquid.node.cjs.js:4242:21) +0ms

```

and that comes from this content:

```
$ cat pages/testit.html 

<code>
{% for post in collections.g5 %}
	item: {{ post.data.title }} <br/>
{% endfor %}
</code>

INSPECT

<code>
{{ collections.posts | inspect }}
</code>

```

### Reproduction steps

1. see reproduce commands before output above

### Expected behavior

It should generate a list of pages, and then start serving the site locally w/browsersync.

Instead it's giving above errors (which is very very weird, since the error is not always the same, since the 11ty instance hasn't changed since it was setup, and since it still works fine running through cloud provider).

**Comment by pracplayopen** [comment]
hm, ok... so it is still  generating these errors using method above.

but running this (from same directory as above) WORKS as it did before

```
$ npm run start
[11ty] Copied 120 files / Wrote 63 files in 0.72 seconds (11.4ms each, v1.0.1)
[11ty] Watching…
[Browsersync] Access URLs:
 ------------------------------------
    Local: http://localhost:8080
 External: http://10.116.109.114:8080
 ------------------------------------
[Browsersync] Serving files from: public


```

this is defined in package.json like so:

> "scripts": {
    "start": "npx @11ty/eleventy --serve",
    "build": "npx @11ty/eleventy"
  },

Perhaps this is just not us being node experts... but these these commands that npm is running vs what we typed above... they look like the exact same command?

**Comment by pdehaan** [comment]
I think it all depends on whether `@11ty/eleventy` is installed locally in your project. If it is, it'd use whatever version of Eleventy is specified in your package.json file (looks like 1.0.1).
If `@11ty/eleventy` is NOT in your package.json file or installed locally, <kbd>npx</kbd> would likely be running whatever the latest stable version is in npm's registry (2.0.1, I think).

But even weirder if the results are intermittent and sometimes throw errors about missing filters and other times doesn't. Hard to tell without seeing the source. (although personally I always run my <kbd>npm run build</kbd> command from the same directory as the .eleventy.js config file)

**Comment by pracplayopen** [comment]
here's those two filters

```
$ cat .eleventy.js |grep -E -A3 "inspect|postDate"
  eleventyConfig.addFilter("postDate", (dateObj) => {
    return DateTime.fromJSDate(dateObj).toLocaleString(DateTime.DATE_FULL);
  });
  eleventyConfig.addFilter("inspect", require("util").inspect);
```

Yes local install here.    Feel like I get the basic ideas of how npm works, very little experience with npx.  Looking at the docs it looks like npx is specifically geared towards execution and so I guess it's likely keeping files it's running maybe in a different spot, and hence the different results?

I'm going to close this since I at least found a workaround, for a new user though it might be advisable to have npx and npm run perform similiarly as possible, if there's an easy way to do that.

here's the packages.json being used here:

```
$ cat package.json 
{
  "name": "smol-11ty-starter",
  "version": "1.0.0",
  "description": "Extremely minimal Eleventy starter to kickstart a simple multi-page site / a nearly opinionless foundation to continue building on",
  "main": "index.html",
  "scripts": {
    "start": "npx @11ty/eleventy --serve",
    "build": "npx @11ty/eleventy"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/5t3ph/smol-11ty-starter.git"
  },
  "keywords": [
    "11ty",
    "11ty-starter",
    "eleventy",
    "eleventy-starter",
    "eleventy-sample",
    "11ty-template"
  ],
  "author": "5t3ph",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/5t3ph/smol-11ty-starter/issues"
  },
  "dependencies": {
    "eleventy-plugin-description": "^0.1.4",
    "striptags": "^3.2.0"
  },
  "devDependencies": {
    "@11ty/eleventy": "^1.0.1",
    "luxon": "^2.3.2"
  }
}
```

All examples above were produced running from same directory as .eleventy.js

**Comment by pracplayopen** [comment]
One update to this:   The hangs were produced by an errant symlink- eventually 11ty detected it and errored but I guess it took a couple of minutes.  This was our fault, all errors above were from after removing symlink and again only affected npx.

Thanks for quick response- really a great little tool 11ty is!
