### ISSUE TITLE
Original error stack trace: TypeError: Cannot read properties of undefined (reading 'call')

### ISSUE THREAD

**Issue by njfamirm** [11ty/eleventy#3063]
### Operating system

MacOS venture

### Eleventy

2.0.1

### Describe the bug

Hi

I faced this problem after I changed some things on my website which I don't know exactly because of which part (https://github.com/njfamirm/blog/pull/53)

Before these changes, the site was built without any problems, but after this, the build problem was broken because of this file, and after deleting them, the build problem in the system and also the build workflow was solved.

But this problem has not been solved in the Docker build process yet!: 

```
#17 70.75 [11ty] Original error stack trace: TypeError: Cannot read properties of undefined (reading 'call')
#17 70.75 [11ty]     at Context.<anonymous> (/app/node_modules/@11ty/eleventy/src/UserConfig.js:257:32)
#17 70.75 [11ty]     at Context.<anonymous> (/app/node_modules/@11ty/eleventy/src/BenchmarkGroup.js:32:26)
#17 70.75 [11ty]     at Context.<anonymous> (/app/node_modules/@11ty/eleventy/src/Engines/Nunjucks.js:104:17)
#17 70.75 [11ty]     at eval (eval at _compile (/app/node_modules/nunjucks/src/environment.js:527:18), <anonymous>:31:26)
#17 70.75 [11ty]     at Template.root [as rootRenderFunc] (eval at _compile (/app/node_modules/nunjucks/src/environment.js:527:18), <anonymous>:39:3)
#17 70.75 [11ty]     at Template.render (/app/node_modules/nunjucks/src/environment.js:454:10)
#17 70.75 [11ty]     at eval (eval at _compile (/app/node_modules/nunjucks/src/environment.js:527:18), <anonymous>:109:10)
#17 70.75 [11ty]     at fn (/app/node_modules/a-sync-waterfall/index.js:26:24)
#17 70.75 [11ty]     at /app/node_modules/a-sync-waterfall/index.js:66:22
#17 70.75 [11ty]     at executeSync (/app/node_modules/a-sync-waterfall/index.js:8:15)
```

Docker build workflow logs: https://github.com/njfamirm/blog/actions/runs/6435511409/job/17476927203
removed files: https://github.com/njfamirm/blog/commit/901461350dd5086fb71e7156cbde2a2af3dae6d2

thanks

### Reproduction steps

1. yarn elevnety

**Comment by njfamirm** [comment]
solved
