### ISSUE TITLE
Build crashes with `webc:root="override"` and dynamic attributes

### ISSUE THREAD

**Issue by patrulea** [11ty/eleventy#3070]
### Operating system

macOS 14.0 Sonoma

### Eleventy

2.0.1

### Describe the bug

I have a `global-header.webc` component that contains a `<header>` and a `<style>` tag. I’m trying to scope the styles so WebC adds a unique class to the host element in the rendered HTML. But I don’t want a `<global-header>` tag in it, instead, I want `<header>` to be the host component and get the unique class for style scoping.

**The problem is** that the dynamic `:href` and `:title` attributes are ignored, as they are passed from the outer `<global-header>`. And the build crashes.
```bash
[11ty] 1. Having trouble writing to "_site/page.html" from "./page.webc" (via EleventyTemplateError)
[11ty] 2. Evaluating a dynamic attribute failed: `:href="site.url"`.
[11ty] Original error message: Cannot read properties of undefined (reading 'url') (via Error)
[11ty] Original error stack trace: Error: Evaluating a dynamic attribute failed: `:href="site.url"`.
```

What am I missing?
This is my first WebC project so I’m getting to know the basics.

### Reproduction steps

```html
<!-- page.webc -->
<global-header
  :href="site.url"
  :title="meta.title"
></global-header>
```
```html
<!-- global-header.webc -->
<header webc:root="override">
  <a
    :href="href"
    :title="title"
    @text="title"
  ></a>
</header>
<style webc:scoped>
:host {
  font-weight: bold
}
</style>
```

### Expected behavior

Dynamic attributes are passed properly and the build doesn’t crash.

**Comment by patrulea** [comment]
It looks like it becomes a problem when attempting to pass a dynamic attribute as component data. Looks like a bug.

---

`test-component.webc`
```html
<div webc:root="override">
  <p @text="label"></p>
</div>
<style webc:scoped>
  :host {}
</style>
```

---

`index.webc` (crashing)
```html
<test-component :@label="meta.title"></test-component>
```
```bash
2. Evaluating a dynamic prop failed: `:@label="meta.title"`.
Original error message: Cannot read properties of undefined (reading 'title') (via Error)

Original error stack trace: Error: Evaluating a dynamic prop failed: `:@label="meta.title"`.
Original error message: Cannot read properties of undefined (reading 'title')
    at ModuleScript.evaluateScript ([repo]/node_modules/@11ty/webc/src/moduleScript.cjs:71:10)
    at ModuleScript.evaluateScriptInline ([repo]/node_modules/@11ty/webc/src/moduleScript.cjs:44:23)
    at AttributeSerializer.evaluateAttribute ([repo]/node_modules/@11ty/webc/src/attributeSerializer.js:160:41)
    at AttributeSerializer.evaluateAttributesArray ([repo]/node_modules/@11ty/webc/src/attributeSerializer.js:179:39)
    at AstSerializer.renderStartTag ([repo]/node_modules/@11ty/webc/src/ast.js:447:55)
    at AstSerializer.compileNode ([repo]/node_modules/@11ty/webc/src/ast.js:1132:66)
    at async AstSerializer.getChildContent ([repo]/node_modules/@11ty/webc/src/ast.js:349:56)
    at async AstSerializer.compileNode ([repo]/node_modules/@11ty/webc/src/ast.js:1226:36)
    at async AstSerializer.getChildContent ([repo]/node_modules/@11ty/webc/src/ast.js:349:56)
    at async AstSerializer.compileNode ([repo]/node_modules/@11ty/webc/src/ast.js:1226:36)

Wrote 0 files (skipped 5) in 0.38 seconds (v2.0.1)
```

---

`index.webc` (ok!)
```html
<test-component @label="hello world!"></test-component>
```
```html
<!-- rendered result -->
<div class="w8xg3owjk">
  <p>hello world!</p>
</div>
```

**Comment by patrulea** [comment]
Eleventy Discord member Adam (@\later1234) helped me solve this issue. The key in the dynamic attribute that is being passed as component data should be prefixed with `$data.` so that the host element within the referenced component can access the rest of the data cascade.

---

`index.webc`
```html
<test-component :label="$data.meta.title"></test-component>
```
