### ISSUE TITLE
Incremental builds throw a`TemplateRender` initialization error when `eleventy.config.js` is edited (v3.0.0)

### ISSUE THREAD

**Issue by noelforte** [11ty/eleventy#3170]
### Operating system

macOS Sonoma 14.2.1

### Eleventy

v3.0.0-alpha.4

### Describe the bug

When running `eleventy --serve --incremental` in v3.0.0, I've noticed the process crashes when attempting to save changes to the configuration file, perhaps something related to a race condition or unexpected handling of what I assume should be a graceful restart of the dev server.

<details><summary>Output</summary>

```console
[11ty] File changed: eleventy.config.js
[11ty] Problem writing Eleventy templates: (more in DEBUG output)
[11ty] TemplateRender has not yet initialized. (via Error)
[11ty] 
[11ty] Original error stack trace: Error: TemplateRender has not yet initialized.
[11ty]     at get templateRender [as templateRender] (file:///***/11ty-incremental-esm/node_modules/@11ty/eleventy/src/TemplateContent.js:122:10)
[11ty]     at get engine [as engine] (file:///***/11ty-incremental-esm/node_modules/@11ty/eleventy/src/TemplateContent.js:117:15)
[11ty]     at Template.isFileRelevantToThisTemplate (file:///***/11ty-incremental-esm/node_modules/@11ty/eleventy/src/TemplateContent.js:568:30)
[11ty]     at TemplateWriter._addToTemplateMap (file:///***/11ty-incremental-esm/node_modules/@11ty/eleventy/src/TemplateWriter.js:284:11)
[11ty]     at TemplateWriter._createTemplateMap (file:///***/11ty-incremental-esm/node_modules/@11ty/eleventy/src/TemplateWriter.js:326:14)
[11ty]     at TemplateWriter.generateTemplates (file:///***/11ty-incremental-esm/node_modules/@11ty/eleventy/src/TemplateWriter.js:361:14)
[11ty]     at TemplateWriter.write (file:///***/11ty-incremental-esm/node_modules/@11ty/eleventy/src/TemplateWriter.js:408:32)
[11ty]     at async Eleventy.executeBuild (file:///***/11ty-incremental-esm/node_modules/@11ty/eleventy/src/Eleventy.js:1233:10)
[11ty]     at async Eleventy._watch (file:///***/11ty-incremental-esm/node_modules/@11ty/eleventy/src/Eleventy.js:844:22)
[11ty]     at async watchRun (file:///***/11ty-incremental-esm/node_modules/@11ty/eleventy/src/Eleventy.js:1089:5)
[11ty] Wrote 0 files in 0.00 seconds (v3.0.0-alpha.4)
[11ty] Watching…
```

</details>

<details><summary><b><code>DEBUG</code></b> output</summary>

```console
[11ty] File changed: eleventy.config.js
  Eleventy:UserConfig Resetting EleventyConfig to initial values. +9s
  Eleventy:UserConfig Adding universal filter 'slug' +1ms
  Eleventy:UserConfig Adding universal filter 'slugify' +0ms
  Eleventy:UserConfig Adding universal filter 'url' +1ms
  Eleventy:UserConfig Adding universal filter 'log' +0ms
  Eleventy:UserConfig Adding universal filter 'getCollectionItemIndex' +0ms
  Eleventy:UserConfig Adding universal filter 'getCollectionItem' +0ms
  Eleventy:UserConfig Adding universal filter 'getPreviousCollectionItem' +0ms
  Eleventy:UserConfig Adding universal filter 'getNextCollectionItem' +0ms
  Eleventy:TemplateConfig rootConfig { templateFormats: [ 'liquid', 'md', 'njk', 'html', '11ty.js' ], pathPrefix: '/', markdownTemplateEngine: 'liquid', htmlTemplateEngine: 'liquid', htmlOutputSuffix: '-o', dataFileSuffixes: [ '.11tydata', '' ], dataFileDirBaseNameOverride: false, keys: { package: 'pkg', layout: 'layout', permalink: 'permalink', permalinkRoot: 'permalinkBypassOutputDir', engineOverride: 'templateEngineOverride', computed: 'eleventyComputed' }, dir: { input: '.', includes: '_includes', data: '_data', output: '_site' }, nunjucksFilters: {} } +9s
  Eleventy:TemplateConfig Merging config with eleventy.config.js +0ms
  Eleventy:TemplateConfig overrides: {} +3ms
  Eleventy:TemplateConfig Current configuration: { pathPrefix: '/', markdownTemplateEngine: 'liquid', htmlTemplateEngine: 'liquid', htmlOutputSuffix: '-o', dataFileSuffixes: [ '.11tydata', '' ], dataFileDirBaseNameOverride: false, keys: { package: 'pkg', layout: 'layout', permalink: 'permalink', permalinkRoot: 'permalinkBypassOutputDir', engineOverride: 'templateEngineOverride', computed: 'eleventyComputed' }, dir: { input: './src', includes: '_includes', data: '_data', output: 'build' }, nunjucksFilters: { slug: [Function (anonymous)], slugify: [Function (anonymous)], url: [Function (anonymous)], log: [Function (anonymous)], getCollectionItemIndex: [Function (anonymous)], getCollectionItem: [Function (anonymous)], getPreviousCollectionItem: [Function (anonymous)], getNextCollectionItem: [Function (anonymous)] }, templateFormats: [ 'liquid', 'md', 'njk', 'html', '11ty.js' ], transforms: {}, linters: {}, globalData: {}, layoutAliases: {}, layoutResolution: true, passthroughCopies: {}, liquidOptions: {}, liquidTags: {}, liquidFilters: { slug: [Function (anonymous)], slugify: [Function (anonymous)], url: [Function (anonymous)], log: [Function (anonymous)], getCollectionItemIndex: [Function (anonymous)], getCollectionItem: [Function (anonymous)], getPreviousCollectionItem: [Function (anonymous)], getNextCollectionItem: [Function (anonymous)] }, liquidShortcodes: {}, liquidPairedShortcodes: {}, nunjucksEnvironmentOptions: {}, nunjucksPrecompiledTemplates: {}, nunjucksAsyncFilters: {}, nunjucksTags: {}, nunjucksGlobals: {}, nunjucksAsyncShortcodes: {}, nunjucksShortcodes: {}, nunjucksAsyncPairedShortcodes: {}, nunjucksPairedShortcodes: {}, javascriptFunctions: { slug: [Function (anonymous)], slugify: [Function (anonymous)], url: [Function (anonymous)], log: [Function (anonymous)], getCollectionItemIndex: [Function (anonymous)], getCollectionItem: [Function (anonymous)], getPreviousCollectionItem: [Function (anonymous)], getNextCollectionItem: [Function (anonymous)] }, markdownHighlighter: null, libraryOverrides: {}, dynamicPermalinks: true, useGitIgnore: true, ignores: Set(2) { '**/node_modules/**', '.git/**' }, watchIgnores: Set(2) { '**/node_modules/**', '.git/**' }, dataDeepMerge: true, watchJavaScriptDependencies: true, additionalWatchTargets: [], serverOptions: {}, chokidarConfig: {}, watchThrottleWaitTime: 0, frontMatterParsingOptions: { engines: { node: [Function: node] } }, dataExtensions: Map(0) {}, extensionMap: Set(0) {}, quietMode: false, events: AsyncEventEmitter { _events: [Object: null prototype] {}, _eventsCount: 0, _maxListeners: undefined, [Symbol(shapeMode)]: false, [Symbol(kCapture)]: false }, benchmarkManager: BenchmarkManager { benchmarkGroups: { Configuration: [BenchmarkGroup], Aggregate: [BenchmarkGroup] }, isVerbose: true, start: 8789.180457949638 }, plugins: [], useTemplateCache: true, precompiledCollections: {}, dataFilterSelectors: Set(0) {}, libraryAmendments: {}, serverPassthroughCopyBehavior: 'copy', urlTransforms: [] } +0ms
  Eleventy:TemplatePassthroughManager Resetting counts to 0 +9s
  Eleventy:EleventyFiles .gitignore,.eleventyignore,src/.eleventyignore ignoring: ./node_modules/** +9s
  Eleventy:EleventyFiles .gitignore,.eleventyignore,src/.eleventyignore ignoring: ./build/** +0ms
  Eleventy:EleventyFiles .gitignore,.eleventyignore,src/.eleventyignore ignoring: ./_site/** +0ms
  Eleventy:TemplatePassthroughManager Resetting counts to 0 +1ms
  Eleventy:EleventyFiles .gitignore,.eleventyignore,src/.eleventyignore ignoring: ./node_modules/** +1ms
  Eleventy:EleventyFiles .gitignore,.eleventyignore,src/.eleventyignore ignoring: ./build/** +0ms
  Eleventy:EleventyFiles .gitignore,.eleventyignore,src/.eleventyignore ignoring: ./_site/** +0ms
  Eleventy:EleventyFiles Searching for: [ './src/**/*.{liquid,md,njk,html,11ty.js,11ty.cjs,11ty.mjs}' ] +0ms
  Eleventy:FastGlobManager Glob search ('templates') searching for: [ './src/**/*.{liquid,md,njk,html,11ty.js,11ty.cjs,11ty.mjs}' ] +9s
  Eleventy:FastGlobManager Glob search ('templates') ignoring: [ 'node_modules/**', 'build/**', '_site/**', 'src/_includes/**', 'src/_data/**', '**/node_modules/**', '.git/**' ] +1ms
  Eleventy:TemplatePassthroughManager TemplatePassthrough copy started. +1ms
  Eleventy:TemplatePassthroughManager `addPassthroughCopy` config API paths: {} +0ms
  Eleventy:TemplatePassthroughManager `addPassthroughCopy` config API normalized paths: [] +0ms
  Eleventy:TemplatePassthroughManager `addPassthroughCopy` config API paths: {} +0ms
  Eleventy:TemplatePassthroughManager `addPassthroughCopy` config API normalized paths: [] +0ms
  Eleventy:TemplatePassthroughManager TemplatePassthrough copy finished. Current count: 0 +1ms
[11ty] Problem writing Eleventy templates:
[11ty] TemplateRender has not yet initialized. (via Error)
  Eleventy:EleventyErrorHandler (error stack): Error: TemplateRender has not yet initialized.
  Eleventy:EleventyErrorHandler     at get templateRender [as templateRender] (file:///***/11ty-incremental-esm/node_modules/@11ty/eleventy/src/TemplateContent.js:122:10)
  Eleventy:EleventyErrorHandler     at get engine [as engine] (file:///***/11ty-incremental-esm/node_modules/@11ty/eleventy/src/TemplateContent.js:117:15)
  Eleventy:EleventyErrorHandler     at Template.isFileRelevantToThisTemplate (file:///***/11ty-incremental-esm/node_modules/@11ty/eleventy/src/TemplateContent.js:568:30)
  Eleventy:EleventyErrorHandler     at TemplateWriter._addToTemplateMap (file:///***/11ty-incremental-esm/node_modules/@11ty/eleventy/src/TemplateWriter.js:284:11)
  Eleventy:EleventyErrorHandler     at TemplateWriter._createTemplateMap (file:///***/11ty-incremental-esm/node_modules/@11ty/eleventy/src/TemplateWriter.js:326:14)
  Eleventy:EleventyErrorHandler     at TemplateWriter.generateTemplates (file:///***/11ty-incremental-esm/node_modules/@11ty/eleventy/src/TemplateWriter.js:361:14)
  Eleventy:EleventyErrorHandler     at TemplateWriter.write (file:///***/11ty-incremental-esm/node_modules/@11ty/eleventy/src/TemplateWriter.js:408:32)
  Eleventy:EleventyErrorHandler     at async Eleventy.executeBuild (file:///***/11ty-incremental-esm/node_modules/@11ty/eleventy/src/Eleventy.js:1233:10)
  Eleventy:EleventyErrorHandler     at async Eleventy._watch (file:///***/11ty-incremental-esm/node_modules/@11ty/eleventy/src/Eleventy.js:844:22)
  Eleventy:EleventyErrorHandler     at async watchRun (file:///***/11ty-incremental-esm/node_modules/@11ty/eleventy/src/Eleventy.js:1089:5) +0ms
[11ty] Wrote 0 files in 0.00 seconds (v3.0.0-alpha.4)
  Eleventy:FastGlobManager Glob search ('js-dependencies') searching for: [ './src/**/*.11tydata.js' ] +4ms
  Eleventy:FastGlobManager Glob search ('js-dependencies') ignoring: [ '**/node_modules/**' ] +0ms
  Eleventy:Logger Watching… +9s
```

</details>

### Reproduction steps

1. Run `npx eleventy --serve --incremental` using `v3.0.0-alpha.4`
2. Edit `eleventy.config.js`
3. Save changes

### Expected behavior

In accordance with the documentation, an edit to the eleventy configuration should trigger a full rebuild, or at the very least, a reset of the dev server which in turn will trigger a full rebuild.

### Reproduction URL

https://github.com/noelforte/11ty-incremental-esm

**Comment by AleksandrHovhannisyan** [comment]
I'm also getting this on canary (3.0.0-alpha5)

```
[11ty] TemplateRender has not yet initialized. (via Error)
[11ty]
[11ty] Original error stack trace: Error: TemplateRender has not yet initialized.
[11ty]     at get templateRender [as templateRender] (file:///home/aleks/dev/aleksandrhovhannisyan.com/node_modules/@11ty/eleventy/src/TemplateContent.js:122:10)
[11ty]     at get engine [as engine] (file:///home/aleks/dev/aleksandrhovhannisyan.com/node_modules/@11ty/eleventy/src/TemplateContent.js:117:15)
[11ty]     at Template.isFileRelevantToThisTemplate (file:///home/aleks/dev/aleksandrhovhannisyan.com/node_modules/@11ty/eleventy/src/TemplateContent.js:568:30)
[11ty]     at TemplateWriter._addToTemplateMap (file:///home/aleks/dev/aleksandrhovhannisyan.com/node_modules/@11ty/eleventy/src/TemplateWriter.js:284:11)
[11ty]     at TemplateWriter._createTemplateMap (file:///home/aleks/dev/aleksandrhovhannisyan.com/node_modules/@11ty/eleventy/src/TemplateWriter.js:326:14)
[11ty]     at TemplateWriter.generateTemplates (file:///home/aleks/dev/aleksandrhovhannisyan.com/node_modules/@11ty/eleventy/src/TemplateWriter.js:361:14)
[11ty]     at TemplateWriter.write (file:///home/aleks/dev/aleksandrhovhannisyan.com/node_modules/@11ty/eleventy/src/TemplateWriter.js:408:32)
[11ty]     at async Eleventy.executeBuild (file:///home/aleks/dev/aleksandrhovhannisyan.com/node_modules/@11ty/eleventy/src/Eleventy.js:1234:10)
[11ty]     at async Eleventy._watch (file:///home/aleks/dev/aleksandrhovhannisyan.com/node_modules/@11ty/eleventy/src/Eleventy.js:845:22)
[11ty]     at async watchRun (file:///home/aleks/dev/aleksandrhovhannisyan.com/node_modules/@11ty/eleventy/src/Eleventy.js:1090:5)
[11ty] Wrote 0 files in 0.02 seconds (v3.0.0-alpha.5)
```

**Comment by AleksandrHovhannisyan** [comment]
This is where the error gets thrown:

https://github.com/11ty/eleventy/blob/04e07a42610f52ce367e1199f50c03ec6f79c5e8/src/TemplateContent.js#L120-L125

My guess is that something must've changed that causes `this._templateRender` gets destroyed between builds. Importantly, this is only reproducible when editing `.eleventy.js` or files imported by `.eleventy.js` as OP noted above. Not reproducible when editing pages, posts, data files, etc.

**Comment by zachleat** [comment]
Verified, milestoning for the next canary.

**Comment by zachleat** [comment]
Shipping with `v3.0.0-canary.6`

**Comment by zachleat** [comment]
Just a fair warning, I did rewrite the code affecting this bug that will be shipping with 3.0.0-alpha.14 (currently on `main`).
