### ISSUE TITLE
When I add a .gitignore

### ISSUE THREAD

**Issue by cmaxw** [11ty/eleventy#318]
When I create a .gitignore in the root directory of my project alongside my post/page files, I get an error 

    > You’re trying to use a layout that does not exist: layoutLiquid.liquid (undefined) (Error)

Adding it to a .eleventyignore file didn't help.

I'm trying to ignore the _site directory, but that doesn't seem to play well for some reason.

**Comment by jevets** [comment]
Try with [DEBUG](https://www.11ty.io/docs/debugging/)? `DEBUG=Eleventy* eleventy [--serve]`

**Comment by jevets** [comment]
To ignore the `_site` directory, this `.gitignore` should do it:

```sh
# /.gitignore

_site
node_modules
```

**Comment by yuune** [comment]
Indeed, it looks like this is not about `.gitignore` since it already ignored by default,
unless you're disabling it manually by using `eleventyConfig.setUseGitIgnore(false);`
https://github.com/11ty/eleventy/blob/3671ba1fff033338a320e1fca017efde260e0022/src/EleventyFiles.js#L148-L153

**Comment by cmaxw** [comment]
I've done a bunch of stuff on the repo since then and have moved stuff to a src/ folder. So, if someone closes this, I won't complain. 

I haven't changed the templateFormat config.

I did create an .eleventy.js file, but I'm not convinced that I created it before this started happening.

I also haven't upgraded to 0.6. Maybe just a strange thing. It was failing on my computer. I didn't try deploying to Netlify.

**Comment by cmaxw** [comment]
Is there a good place get help in realtime?

**Comment by zachleat** [comment]
@cmaxw can you send me a DM on Twitter?

**Comment by zachleat** [comment]
I’m happy to help @cmaxw—please get in touch!

> This is an automated message to let you know that a response was posted to your issue and for the health of the repository issue tracker the issue will be closed. This is to help alleviate issues hanging open waiting for a response from the original poster.

> If you’re still having problems, do not let the issue’s closing deter you if you have additional questions! Post another comment and I will reopen the issue. Thanks!

**Comment by zachleat** [comment]
@cmaxw I just ran into this!

Eleventy is trying to process templates in your `node_modules` directory. This happened to me when I added a `.gitignore` file but didn’t list `node_modules` as an entry to ignore. You can add `node_modules` to your `.gitignore` or your `.eleventyignore` file and it should work as expected.

**Comment by liamgreenhill** [comment]
In case this helps anyone else—if you see these errors when trying to deploy to Netlify:

> Problem writing Eleventy templates: (more in DEBUG output)
> Having trouble rendering liquid (and markdown) template ./node_modules/decode-uri-component/readme.md
> `TemplateContentRenderError` was thrown
> Having trouble compiling template ./node_modules/decode-uri-component/readme.md
> `TemplateContentCompileError` was thrown
> tag ab not found, file:./node_modules/decode-uri-component/readme.md, line:44
> `ParseError` was thrown
> tag ab not found
> `AssertionError` was thrown:
>     AssertionError: tag ab not found
>         at assert (/opt/build/repo/node_modules/liquidjs/dist/liquid.common.js:1062:11)
>         at Object.parse (/opt/build/repo/node_modules/liquidjs/dist/liquid.common.js:1873:7)
>         at Object.construct (/opt/build/repo/node_modules/liquidjs/dist/liquid.common.js:1887:14)
>         at parseTag (/opt/build/repo/node_modules/liquidjs/dist/liquid.common.js:2037:16)
>         at parseToken (/opt/build/repo/node_modules/liquidjs/dist/liquid.common.js:2021:15)
>         at Object.parse (/opt/build/repo/node_modules/liquidjs/dist/liquid.common.js:2012:22)
>         at Object.parse$$1 [as parse] (/opt/build/repo/node_modules/liquidjs/dist/liquid.common.js:3420:24)
>         at Liquid.compile (/opt/build/repo/node_modules/@11ty/eleventy/src/Engines/Liquid.js:199:29)
>         at Markdown.compile (/opt/build/repo/node_modules/@11ty/eleventy/src/Engines/Markdown.js:62:25)
>         at TemplateRender.getCompiledTemplate (/opt/build/repo/node_modules/@11ty/eleventy/src/TemplateRender.js:210:26)

...it means that you need to add `node_modules` to your `.gitignore` file in your project folder. That will stop the errors and allow you to build.

It took me a while to work it out. The error message is telling you that eleventy is trying to process the markdown of files within the `node_modules` folder. You don't want that to happen so you need to tell eleventy to ignore it, which you do by adding it to your `.gitignore` file.

The caught me out because I'd followed the Get Started tutorial on the Filament Group website (https://www.filamentgroup.com/lab/build-a-blog/) which had prompted me to install node globally.

So I was happily building away on my local developer environment on my MacBook with no issues.
When I tried to take that across to Netlify, it didn't "just work". I needed to add the following.


### Summary of what's needed to build on Netlify

- `package.json` file in the root of my project folder. Here's mine:

`
{
  "name": "liamnugent.me",
  "version": "1.0.0",
  "description": "A website built using Eleventy static site generator.",
  "scripts": {
    "build": "eleventy",
    "watch": "eleventy --watch",
    "serve": "eleventy --serve",
    "debug": "DEBUG=* eleventy"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/liamgreenhill/liamnugent.me"
  },
  "author": {
    "name": "Liam Nugent",
    "url": "https://www.liamnugent.me/"
  },
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/liamgreenhill/liamnugent.me/issues"
  },
  "homepage": "https://github.com/liamgreenhill/liamnugent.me",
  "devDependencies": {
    "@11ty/eleventy": "^0.11.0-beta.3",
    "@11ty/eleventy-navigation": "^0.1.3",
    "@11ty/eleventy-plugin-rss": "^1.0.7",
    "@11ty/eleventy-plugin-syntaxhighlight": "^3.0.1",
    "luxon": "^1.21.3",
    "markdown-it": "^8.4.2",
    "markdown-it-anchor": "^5.2.5"
  }
}
`

- `.gitignore` file. Here's mine:
`
node_modules
`

I hope that helps someone who has the same issue.

**Comment by stevenpetryk** [comment]
In general, `node_modules` should always be in your gitignore. This is a best practice outside of Eleventy.
