### ISSUE TITLE
Error message provides incorrect/misleading information

### ISSUE THREAD

**Issue by boehs** [11ty/eleventy#3183]
v3.0.0-alpha.4

I have a writeup here: https://boehs.org/node/investigating-a-11ty-race-condition

A portion of the post has been copied below:

---

This error is incorrect:

```
[11ty] Problem writing Eleventy templates: (more in DEBUG output) [11ty] 1. Having trouble writing to "out/og/node/lorum.png" from "./src/og.11ty.js" (via EleventyTemplateError)
[11ty] 2. Transform `html` encountered an error when transforming ./src/og.11ty.js. (via EleventyTransformError)
```

Modifying 11ty source code for the second error to report the output shows the real output file:

```js
} catch (e) {
	throw new EleventyTransformError(
		`Transform \`${name}\` encountered an error when transforming ${inputPath} into "${outputPath}"`,
		e,
	);
}
```

```
1. Having trouble writing to "out/og/node/lorum.png" from "./src/og.11ty.js" (via EleventyTemplateError)
2. Transform 'htmlmin' encountered an error when transforming ./src/og.11ty.js into "out/og/index.html". (via EleventyTransformError)
```

So why is it incorrect in the first error?

Because, the way 11ty works is it internally makes a queue of all the templates that need to be transformed. Because most templates are the actual content, this usually works, but pagination is one template making many output files. There was a hack employeed, where the first file that will be outputted is set as the output file for use in error messages to avoid breaking other code:

```js
for (let page of map._pages) {
	// Copy outputPath to map entry
	if (!map.outputPath) {
		map.outputPath = page.outputPath;
	}
}
```

But, this means that I’m being told false information! And, without modifying 11ty source, there’s no good way to get correct information! No wonder I was confused!

---

Zach, I wrote it another way in your discord DMs

Discussion in the 11ty discord here: https://discord.com/channels/741017160297611315/1201882327509368892

**Comment by zachleat** [comment]
In v3.0.0-alpha.14, references to `map.outputPath` on paginated templates will throw an error letting folks know about this inconsistency. Folks shouldn’t have access to the `map` object there, though. This isn’t exposed in any public API!

Just as an FYI `outputPath` used on Transforms https://www.11ty.dev/docs/transforms/ is **not** the `map.outputPath` in `TemplateMap.js`.

**Comment by bennypowers** [comment]
On my upgrade branch, i ran into this error:

```
> eleventy --serve --incremental

(node:322795) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
[rhds]: Copying RHDS elements assets...
[rhds]:   ...done
[eleventy-plugin-jspm]: Generating import map...
[eleventy-plugin-jspm]:  ...Done!
(node:322795) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 101 eleventy.templateModified listeners added to [AsyncEventEmitter]. MaxListeners is 100. Use emitter.setMaxListeners() to increase limit
[11ty] Problem writing Eleventy templates: (more in DEBUG output)
[11ty] Internal error: `.outputPath` on a paginated map entry is not consistent. Use `_pages[…].outputPath` instead. (via Error)
[11ty] 
[11ty] Original error stack trace: Error: Internal error: `.outputPath` on a paginated map entry is not consistent. Use `_pages[…].outputPath` instead.
[11ty]     at Object.get (file:///home/bennyp/Developer/bennypowers.dev/node_modules/@11ty/eleventy/src/TemplateMap.js:383:17)
[11ty]     at file:///home/bennyp/Developer/bennypowers.dev/node_modules/@11ty/eleventy/src/TemplateWriter.js:392:48
[11ty]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[11ty]     at async Promise.all (index 9)
[11ty]     at async Eleventy.executeBuild (file:///home/bennyp/Developer/bennypowers.dev/node_modules/@11ty/eleventy/src/Eleventy.js:1282:10)
[11ty]     at async Eleventy.watch (file:///home/bennyp/Developer/bennypowers.dev/node_modules/@11ty/eleventy/src/Eleventy.js:1095:16)
[11ty] Copied 315 files / Wrote 1 file in 19.01 seconds (v3.0.0-alpha.14)
[11ty] Eleventy CLI Error: (more in DEBUG output)
[11ty] Internal error: `.outputPath` on a paginated map entry is not consistent. Use `_pages[…].outputPath` instead. (via Error)
[11ty] 
[11ty] Original error stack trace: Error: Internal error: `.outputPath` on a paginated map entry is not consistent. Use `_pages[…].outputPath` instead.
[11ty]     at Object.get (file:///home/bennyp/Developer/bennypowers.dev/node_modules/@11ty/eleventy/src/TemplateMap.js:383:17)
[11ty]     at file:///home/bennyp/Developer/bennypowers.dev/node_modules/@11ty/eleventy/src/TemplateWriter.js:392:48
[11ty]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[11ty]     at async Promise.all (index 9)
[11ty]     at async Eleventy.executeBuild (file:///home/bennyp/Developer/bennypowers.dev/node_modules/@11ty/eleventy/src/Eleventy.js:1282:10)
[11ty]     at async Eleventy.watch (file:///home/bennyp/Developer/bennypowers.dev/node_modules/@11ty/eleventy/src/Eleventy.js:1095:16)
```

It's not clear from here where the error is coming from. ripgrepping my repo for `.outputPath` gives results only for `this.page.outputPath`, which is a red herring per https://github.com/11ty/eleventy/issues/3183#issuecomment-2179000072

some console.log debugging suggests that the inputPath for the template causing the error is posts/index.webc (my paginated post list). I wasn't able to dig deeper, having conceded defeat to the node debugger after a few hours of grumbling.

It's possible .. maybe likely? that I just have a plugin incompatibility between 2.x and 3.0.0-canary

**Comment by zachleat** [comment]
There was an internal reference to `.outputPath` that would swallow application errors on paginated templates. Try the latest on GitHub or 3.0.0-alpha.15 will have this fix https://github.com/11ty/eleventy/commit/8ebd6fef034ba46069d08f5618010ddca5842859
