### ISSUE TITLE
Bug with ESM detection (via `package.json` in a parent directory)

### ISSUE THREAD

**Issue by MangelMaxime** [11ty/eleventy#3200]
### Operating system

macOS Sonoma 14.1.1

### Eleventy

3.0.0-alpha.5

### Describe the bug

If I have a file `.eleventy.js` to configure Eleventy in my docs folder, then running `npx @11ty/eleventy --config=.eleventy.js --serve` crash with the error:

```
[11ty] Writing _site/index.html from ./index.md (njk)
[11ty] Writing _site/posts/post1/index.html from ./posts/post1.md (njk)
[11ty] Wrote 2 files in 0.05 seconds (v3.0.0-alpha.5)
[11ty] Eleventy CLI Error: (more in DEBUG output)
[11ty] require() of ES Module /Users/mmangel/Workspaces/Github/MangelMaxime/eleventy-plugin-fsharp/demo/.eleventy.js from /Users/mmangel/Workspaces/Github/MangelMaxime/eleventy-plugin-fsharp/node_modules/.pnpm/@11ty+dependency-tree@3.0.0/node_modules/@11ty/dependency-tree/main.js not supported.
[11ty] Instead change the require of .eleventy.js in /Users/mmangel/Workspaces/Github/MangelMaxime/eleventy-plugin-fsharp/node_modules/.pnpm/@11ty+dependency-tree@3.0.0/node_modules/@11ty/dependency-tree/main.js to a dynamic import() which is available in all CommonJS modules. (via Error)
[11ty] 
[11ty] Original error stack trace: Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/mmangel/Workspaces/Github/MangelMaxime/eleventy-plugin-fsharp/demo/.eleventy.js from /Users/mmangel/Workspaces/Github/MangelMaxime/eleventy-plugin-fsharp/node_modules/.pnpm/@11ty+dependency-tree@3.0.0/node_modules/@11ty/dependency-tree/main.js not supported.
[11ty] Instead change the require of .eleventy.js in /Users/mmangel/Workspaces/Github/MangelMaxime/eleventy-plugin-fsharp/node_modules/.pnpm/@11ty+dependency-tree@3.0.0/node_modules/@11ty/dependency-tree/main.js to a dynamic import() which is available in all CommonJS modules.
[11ty]     at getDependenciesFor (/Users/mmangel/Workspaces/Github/MangelMaxime/eleventy-plugin-fsharp/node_modules/.pnpm/@11ty+dependency-tree@3.0.0/node_modules/@11ty/dependency-tree/main.js:58:5)
[11ty]     at getCleanDependencyListFor (/Users/mmangel/Workspaces/Github/MangelMaxime/eleventy-plugin-fsharp/node_modules/.pnpm/@11ty+dependency-tree@3.0.0/node_modules/@11ty/dependency-tree/main.js:117:26)
[11ty]     at JavaScriptDependencies.getDependencies (file:///Users/mmangel/Workspaces/Github/MangelMaxime/eleventy-plugin-fsharp/node_modules/.pnpm/@11ty+eleventy@3.0.0-alpha.5/node_modules/@11ty/eleventy/src/Util/JavaScriptDependencies.js:15:18)
[11ty]     at EleventyWatchTargets.addDependencies (file:///Users/mmangel/Workspaces/Github/MangelMaxime/eleventy-plugin-fsharp/node_modules/.pnpm/@11ty+eleventy@3.0.0-alpha.5/node_modules/@11ty/eleventy/src/EleventyWatchTargets.js:119:43)
[11ty]     at Eleventy._initWatchDependencies (file:///Users/mmangel/Workspaces/Github/MangelMaxime/eleventy-plugin-fsharp/node_modules/.pnpm/@11ty+eleventy@3.0.0-alpha.5/node_modules/@11ty/eleventy/src/Eleventy.js:985:27)
[11ty]     at async Eleventy.initWatch (file:///Users/mmangel/Workspaces/Github/MangelMaxime/eleventy-plugin-fsharp/node_modules/.pnpm/@11ty+eleventy@3.0.0-alpha.5/node_modules/@11ty/eleventy/src/Eleventy.js:941:3)
[11ty]     at async Eleventy.watch (file:///Users/mmangel/Workspaces/Github/MangelMaxime/eleventy-plugin-fsharp/node_modules/.pnpm/@11ty+eleventy@3.0.0-alpha.5/node_modules/@11ty/eleventy/src/Eleventy.js:1065:3)
```

If I change `..eleventy.js` to `.eleventy.mjs` then all is good. I think this is because Eleventy is trying to `require` the file even when I am using `type: "module"` in my `package.json`.

Running the build command of Eleventy works as expected.

### Reproduction steps

1. Clone https://github.com/MangelMaxime/eleventy-plugin-fsharp/tree/eleventy_beta_5_watch_mode_bug
2. Make sure to be on the branch named `eleventy_beta_5_watch_mode_bug`
3. Run `pnpm i`
4. Run `cd demo && npx @11ty/eleventy --serve`
5. See that it fails
6. Run `cd demo && npx @11ty/eleventy`
7. See that it succeeds
8. Rename `.eleventy.js` to `.eleventy.mjs`
9. Run `npx @11ty/eleventy --serve`
10. See that it now works

*Note: The code in the demo folder is almost an empty Eleventy project as I was trying to debug the problem and remove my custom plugin from it* 

Edit: Here the problem happens with `.eleventy.js` file but it would also happens the file is named `eleventy.config.js`. I think it will happen for any files named who use `.js`

### Expected behavior

Watch mode should not crash.

**Comment by zachleat** [comment]
Confirmed. Bug with `package.json` in a parent directory of the Eleventy project dir.

https://github.com/MangelMaxime/eleventy-plugin-fsharp/blob/1e5e9737a72fdf0271e81485045884d0389b5c03/package.json#L11-L12
