### ISSUE TITLE
Pagination data could not be found in JavaScript template file

### ISSUE THREAD

**Issue by cgwrench** [11ty/eleventy#3223]
### Operating system

Debian 11 (running under WSL2 on Windows 11 23H2)

### Eleventy

3.0.0-alpha.5

### Describe the bug

I'm attempting to paginate a collection in a `.11ty.js` template file. However, when I try and do this, I get an error stating that the pagination data could not be found:

```sh
> npx @11ty/eleventy
[11ty] Problem writing Eleventy templates: (more in DEBUG output)
[11ty] Could not find pagination data (./open-graph.11ty.js), went looking for: collection.all (via Error)
[11ty] 
[11ty] Original error stack trace: Error: Could not find pagination data (./open-graph.11ty.js), went looking for: collection.all
[11ty]     at Pagination._get (file:///some/path/to/eleventy-test/node_modules/@11ty/eleventy/src/Plugins/Pagination.js:125:10)
[11ty]     at Pagination.setData (file:///some/path/to/eleventy-test/node_modules/@11ty/eleventy/src/Plugins/Pagination.js:81:27)
[11ty]     at new Pagination (file:///some/path/to/eleventy-test/node_modules/@11ty/eleventy/src/Plugins/Pagination.js:24:8)
[11ty]     at Template.getTemplates (file:///some/path/to/eleventy-test/node_modules/@11ty/eleventy/src/Template.js:681:18)
[11ty]     at async TemplateMap.initDependencyMap (file:///some/path/to/eleventy-test/node_modules/@11ty/eleventy/src/TemplateMap.js:409:18)
[11ty]     at async TemplateMap.cache (file:///some/path/to/eleventy-test/node_modules/@11ty/eleventy/src/TemplateMap.js:448:3)
[11ty]     at async TemplateWriter._createTemplateMap (file:///some/path/to/eleventy-test/node_modules/@11ty/eleventy/src/TemplateWriter.js:331:3)
[11ty]     at async TemplateWriter.generateTemplates (file:///some/path/to/eleventy-test/node_modules/@11ty/eleventy/src/TemplateWriter.js:361:3)
[11ty]     at async TemplateWriter.write (file:///some/path/to/eleventy-test/node_modules/@11ty/eleventy/src/TemplateWriter.js:408:21)
[11ty]     at async Eleventy.executeBuild (file:///some/path/to/eleventy-test/node_modules/@11ty/eleventy/src/Eleventy.js:1234:10)
[11ty] Wrote 0 files in 0.13 seconds (v3.0.0-alpha.5)
```

<details>
<summary>Debug mode output</summary>

```sh
> DEBUG=Eleventy* npx @11ty/eleventy
  Eleventy:cmd command: eleventy { _: [], quiet: null, version: false, watch: false, dryrun: false, help: false, serve: false, incremental: false, 'ignore-initial': false } +0ms
  Eleventy:EventBus Setting up global EventBus. +0ms
  Eleventy:UserConfig Resetting EleventyConfig to initial values. +0ms
  Eleventy Setting process.env.ELEVENTY_ROOT: '/some/path/to/eleventy-test' +0ms
  Eleventy:UserConfig Adding universal filter 'slug' +7ms
  Eleventy:UserConfig Adding universal filter 'slugify' +0ms
  Eleventy:UserConfig Adding universal filter 'url' +0ms
  Eleventy:UserConfig Adding universal filter 'log' +0ms
  Eleventy:UserConfig Adding universal filter 'getCollectionItemIndex' +1ms
  Eleventy:UserConfig Adding universal filter 'getCollectionItem' +0ms
  Eleventy:UserConfig Adding universal filter 'getPreviousCollectionItem' +0ms
  Eleventy:UserConfig Adding universal filter 'getNextCollectionItem' +0ms
  Eleventy:UserConfig Adding FilterPlugin plugin +0ms
  Eleventy:UserConfig Adding universal filter 'inputPathToUrl' +0ms
  Eleventy:TemplateConfig rootConfig { templateFormats: [ 'liquid', 'md', 'njk', 'html', '11ty.js' ], pathPrefix: '/', markdownTemplateEngine: 'liquid', htmlTemplateEngine: 'liquid', htmlOutputSuffix: '-o', dataFileSuffixes: [ '.11tydata', '' ], dataFileDirBaseNameOverride: false, keys: { package: 'pkg', layout: 'layout', permalink: 'permalink', permalinkRoot: 'permalinkBypassOutputDir', engineOverride: 'templateEngineOverride', computed: 'eleventyComputed' }, dir: { input: '.', includes: '_includes', data: '_data', output: '_site' }, nunjucksFilters: {} } +0ms
  Eleventy:TemplateConfig Merging config with eleventy.config.js +0ms
  Eleventy:TemplateConfig overrides: {} +1ms
  Eleventy:TemplateConfig Current configuration: { pathPrefix: '/', markdownTemplateEngine: 'liquid', htmlTemplateEngine: 'liquid', htmlOutputSuffix: '-o', dataFileSuffixes: [ '.11tydata', '' ], dataFileDirBaseNameOverride: false, keys: { package: 'pkg', layout: 'layout', permalink: 'permalink', permalinkRoot: 'permalinkBypassOutputDir', engineOverride: 'templateEngineOverride', computed: 'eleventyComputed' }, dir: { input: '.', includes: '_includes', data: '_data', output: '_site' }, nunjucksFilters: { slug: [Function (anonymous)], slugify: [Function (anonymous)], url: [Function (anonymous)], log: [Function (anonymous)], getCollectionItemIndex: [Function (anonymous)], getCollectionItem: [Function (anonymous)], getPreviousCollectionItem: [Function (anonymous)], getNextCollectionItem: [Function (anonymous)], inputPathToUrl: [Function (anonymous)] }, templateFormats: [ 'liquid', 'md', 'njk', 'html', '11ty.js' ], transforms: { 'eleventy.htmlTransformer': [Function (anonymous)] }, linters: {}, globalData: {}, layoutAliases: {}, layoutResolution: true, passthroughCopies: {}, liquidOptions: {}, liquidTags: {}, liquidFilters: { slug: [Function (anonymous)], slugify: [Function (anonymous)], url: [Function (anonymous)], log: [Function (anonymous)], getCollectionItemIndex: [Function (anonymous)], getCollectionItem: [Function (anonymous)], getPreviousCollectionItem: [Function (anonymous)], getNextCollectionItem: [Function (anonymous)], inputPathToUrl: [Function (anonymous)] }, liquidShortcodes: {}, liquidPairedShortcodes: {}, nunjucksEnvironmentOptions: {}, nunjucksPrecompiledTemplates: {}, nunjucksAsyncFilters: {}, nunjucksTags: {}, nunjucksGlobals: {}, nunjucksAsyncShortcodes: {}, nunjucksShortcodes: {}, nunjucksAsyncPairedShortcodes: {}, nunjucksPairedShortcodes: {}, javascriptFunctions: { slug: [Function (anonymous)], slugify: [Function (anonymous)], url: [Function (anonymous)], log: [Function (anonymous)], getCollectionItemIndex: [Function (anonymous)], getCollectionItem: [Function (anonymous)], getPreviousCollectionItem: [Function (anonymous)], getNextCollectionItem: [Function (anonymous)], inputPathToUrl: [Function (anonymous)] }, markdownHighlighter: null, libraryOverrides: {}, dynamicPermalinks: true, useGitIgnore: true, ignores: Set(2) { '**/node_modules/**', '.git/**' }, watchIgnores: Set(2) { '**/node_modules/**', '.git/**' }, dataDeepMerge: true, watchJavaScriptDependencies: true, additionalWatchTargets: [], serverOptions: {}, chokidarConfig: {}, watchThrottleWaitTime: 0, frontMatterParsingOptions: { engines: { node: [Function: node] } }, dataExtensions: Map(0) {}, extensionMap: Set(0) {}, quietMode: false, events: AsyncEventEmitter { _events: [Object: null prototype] { 'eleventy.contentMap': [Function (anonymous)], 'eleventy.directories': [Function (anonymous)] }, _eventsCount: 2, _maxListeners: undefined, [Symbol(shapeMode)]: false, [Symbol(kCapture)]: false }, benchmarkManager: BenchmarkManager { benchmarkGroups: { Configuration: [BenchmarkGroup], Aggregate: [BenchmarkGroup] }, isVerbose: true, start: 224.070507 }, plugins: [], useTemplateCache: true, precompiledCollections: {}, dataFilterSelectors: Set(0) {}, libraryAmendments: {}, serverPassthroughCopyBehavior: 'copy', urlTransforms: [] } +1ms
  Eleventy Eleventy warm up time (in ms) 235.820723 +11ms
  Eleventy:TemplatePassthroughManager Resetting counts to 0 +0ms
  Eleventy Directories:
  Eleventy Input (Dir): .
  Eleventy Input (File): undefined
  Eleventy Data: _data
  Eleventy Includes: _includes
  Eleventy Layouts: undefined
  Eleventy Output: _site
  Eleventy Template Formats: liquid,md,njk,html,11ty.js
  Eleventy Verbose Output: false +5ms
  Eleventy:EleventyFiles Searching for: [ './**/*.{liquid,md,njk,html,11ty.js,11ty.cjs,11ty.mjs}' ] +0ms
  Eleventy:FastGlobManager Glob search ('templates') searching for: [ './**/*.{liquid,md,njk,html,11ty.js,11ty.cjs,11ty.mjs}' ] +0ms
  Eleventy:FastGlobManager Glob search ('templates') ignoring: [ '_site/**', '_includes/**', '_data/**', '**/node_modules/**', '.git/**' ] +1ms
  Eleventy:TemplatePassthroughManager TemplatePassthrough copy started. +21ms
  Eleventy:TemplatePassthroughManager `addPassthroughCopy` config API paths: {} +1ms
  Eleventy:TemplatePassthroughManager `addPassthroughCopy` config API normalized paths: [] +0ms
  Eleventy:TemplateData Using [ '.11tydata', '' ] suffixes to find data files. +0ms
  Eleventy:TemplateData getLocalDataPaths('./index.md'): [ './index.11tydata.js', './index.11tydata.cjs', './index.11tydata.mjs', './index.11tydata.json', './index.json' ] +1ms
  Eleventy:TemplateWriter ./index.md adding to template map. +0ms
  Eleventy:TemplateData Using [ '.11tydata', '' ] suffixes to find data files. +0ms
  Eleventy:TemplateData getLocalDataPaths('./open-graph.11ty.js'): [ './open-graph.11tydata.js', './open-graph.11tydata.cjs', './open-graph.11tydata.mjs', './open-graph.11tydata.json', './open-graph.json' ] +0ms
  Eleventy:TemplateWriter ./open-graph.11ty.js adding to template map. +0ms
  Eleventy:TemplatePassthroughManager TemplatePassthrough copy finished. Current count: 0 +4ms
  Eleventy:FastGlobManager Glob search ('global-data') searching for: [ './_data/**/*.{json,mjs,cjs,js}' ] +24ms
  Eleventy:Template Template date: using file’s 'birthtimeMs' for './open-graph.11ty.js' of 2024-03-20T10:33:18.872Z (from 1710930798872.238) +0ms
  Eleventy:Template Template date: using file’s 'birthtimeMs' for './index.md' of 2024-03-16T16:53:50.849Z (from 1710608030849.7737) +74ms
  Eleventy:TemplateMap Caching collections objects. +0ms
[11ty] Problem writing Eleventy templates:
[11ty] Could not find pagination data (./open-graph.11ty.js), went looking for: collection.all (via Error)
  Eleventy:EleventyErrorHandler (error stack): Error: Could not find pagination data (./open-graph.11ty.js), went looking for: collection.all
  Eleventy:EleventyErrorHandler     at Pagination._get (file:///some/path/to/eleventy-test/node_modules/@11ty/eleventy/src/Plugins/Pagination.js:125:10)
  Eleventy:EleventyErrorHandler     at Pagination.setData (file:///some/path/to/eleventy-test/node_modules/@11ty/eleventy/src/Plugins/Pagination.js:81:27)
  Eleventy:EleventyErrorHandler     at new Pagination (file:///some/path/to/eleventy-test/node_modules/@11ty/eleventy/src/Plugins/Pagination.js:24:8)
  Eleventy:EleventyErrorHandler     at Template.getTemplates (file:///some/path/to/eleventy-test/node_modules/@11ty/eleventy/src/Template.js:681:18)
  Eleventy:EleventyErrorHandler     at async TemplateMap.initDependencyMap (file:///some/path/to/eleventy-test/node_modules/@11ty/eleventy/src/TemplateMap.js:409:18)
  Eleventy:EleventyErrorHandler     at async TemplateMap.cache (file:///some/path/to/eleventy-test/node_modules/@11ty/eleventy/src/TemplateMap.js:448:3)
  Eleventy:EleventyErrorHandler     at async TemplateWriter._createTemplateMap (file:///some/path/to/eleventy-test/node_modules/@11ty/eleventy/src/TemplateWriter.js:331:3)
  Eleventy:EleventyErrorHandler     at async TemplateWriter.generateTemplates (file:///some/path/to/eleventy-test/node_modules/@11ty/eleventy/src/TemplateWriter.js:361:3)
  Eleventy:EleventyErrorHandler     at async TemplateWriter.write (file:///some/path/to/eleventy-test/node_modules/@11ty/eleventy/src/TemplateWriter.js:408:21)
  Eleventy:EleventyErrorHandler     at async Eleventy.executeBuild (file:///some/path/to/eleventy-test/node_modules/@11ty/eleventy/src/Eleventy.js:1234:10) +0ms
  Eleventy:Logger Benchmark     18ms   9%     1× (Aggregate) Searching the file system (templates) +0ms
  Eleventy:Benchmark Benchmark     18ms   9%     1× (Aggregate) Searching the file system (templates) +0ms
  Eleventy:Benchmark Benchmark      2ms   1%     1× (Aggregate) Searching the file system (data) +0ms
  Eleventy:Benchmark Benchmark      1ms   1%     1× (Aggregate) Template Read +0ms
[11ty] Wrote 0 files in 0.19 seconds (v3.0.0-alpha.5)
  Eleventy Finished writing templates. +185ms
  Eleventy 
  Eleventy       Getting frustrated? Have a suggestion/feature request/feedback?
  Eleventy       I want to hear it! Open an issue: https://github.com/11ty/eleventy/issues/new +0ms
```

</details>

### Reproduction steps

I've got two files in a directory, and index page and a `.11ty.js` template, plus a `package.json` (see below).

Running `npx @11ty/eleventy` in this directory causes an error.

## index.md

```md
---
title: Home page
---
# Page header
```

## open-graph.11ty.js

```javascript
import sharp from "sharp";

export function data() {
	return {
		eleventyExcludeFromCollections: true,
		pagination: {
			data: "collection.all", // TODO why does paginating a collection not work here?
			size: 1,
			alias: "preview",
		},
		layout: false,
		permalink: function(data) {
			return `/images/open-graph/${this.slugify(data.preview.title)}.jpg`;
		}
	}
}

export async function render(data) {
	const svg = `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg width="1200" height="630" viewBox="0 0 1200 630" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
	<rect width="100%" height="100%" fill="#00AAFF" />

	<text text-anchor="start" font-family="" font-size="200">
		<tspan x="80" y="350">${data.preview.title}</tspan>
	</text>
</svg>`;

	return sharp(Buffer.from(svg)).toFormat("jpeg").toBuffer();
}
```

## package.json

```json
{
  "name": "eleventy-test",
  "version": "1.0.0",
  "private": true,
  "description": "",
  "type": "module",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "UNLICENSED",
  "devDependencies": {
    "@11ty/eleventy": "3.0.0-alpha.5",
    "sharp": "0.33.2"
  }
}
```

### Expected behavior

I'd expect that running eleventy would generate me a `_site/index.html` file, plus a image file `_site/images/open-graph/home-page.jpg`.

Note that if I replace `data: "collection.all",`  with `data: "testdata",`, and add a `testdata` array to my data:

```javascript
testdata: [
	{ title: "item1" },
	{ title: "item2" },
	{ title: "item3" },
],
```

everything works as expected.

**Comment by cgwrench** [comment]
This was a silly typo on my part. `data: "collection.all"` should have been `data: "collections.all"` (note the extra `s`) 🤦
