### ISSUE TITLE
addTemplateFormats no longer takes array as argument in alpha 7+

### ISSUE THREAD

**Issue by chee** [11ty/eleventy#3265]
### Operating system

macOS 14.4.1 (23E224)

### Eleventy

3.0.0-alpha.6 vs 3.0.0-alpha.7

### Describe the bug

`addTemplateFormats` used to allow an array as the first argument, but now it does not.

### Reproduction steps

1. ### Add multiple template formats using an array
```ts
// in eleventy.config.js
eleventyConfig.addTemplateFormats(["txt", "text"])
```
2. ### try with alpha.6
```sh
npm install @11ty/eleventy@3.0.0-alpha.6
npx eleventy
# [11ty] Wrote 0 files in 0.01 seconds (v3.0.0-alpha.6)
```
3. ### try with alpha.7, alpha.8, alpha.9
```sh
npm install @11ty/eleventy@3.0.0-alpha.9
npx eleventy                                
# [11ty] entry.trim is not a function (via TypeError)
# [11ty] 
# [11ty] Original error stack trace: TypeError: entry.trim is not a function
# [11ty]     at file:///usr/chee/tmp/eleventytest/node_modules/@11ty/eleventy/src/Util/ProjectTemplateFormats.js:28:40
# [11ty]     at Array.map (<anonymous>)
# [11ty]     at #normalize (file:///usr/chee/tmp/eleventytest/node_modules/@11ty/eleventy/src/Util/ProjectTemplateFormats.js:28:19)
# [11ty]     at ProjectTemplateFormats.addViaConfig (file:///usr/chee/tmp/eleventytest/node_modules/@11ty/eleventy/src/Util/ProjectTemplateFormats.js:101:43)
# [11ty]     at TemplateConfig.mergeConfig (file:///usr/chee/tmp/eleventytest/node_modules/@11ty/eleventy/src/TemplateConfig.js:426:25)
# [11ty]     at async TemplateConfig.init (file:///usr/chee/tmp/eleventytest/node_modules/@11ty/eleventy/src/TemplateConfig.js:186:17)
# [11ty]     at async Eleventy.initializeConfig (file:///usr/chee/tmp/eleventytest/node_modules/@11ty/eleventy/src/Eleventy.js:160:3)
```

### Expected behavior

to be like before

**Comment by zachleat** [comment]
Sorry about that! I’ll get it fixed for the next alpha!

**Comment by zachleat** [comment]
Shipping with `3.0.0-alpha.10`
