### ISSUE TITLE
Investigating: `liquidjs@10.15` regression

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#3356]
```
[11ty] Problem writing Eleventy templates: (more in DEBUG output)
[11ty] 1. Having trouble writing to "./_site/web/livecoding-ca/index.html" from "./_posts/2022-10-12-livecoding-ca.md" (via EleventyTemplateError)
[11ty] 2. unexpected "if webmention.url != \"\"", file:/Users/zachleat/Code/zachleat.com/_includes/webmention.liquid, line:20, col:5 (via ParseError)
[11ty] 3. unexpected "if webmention.url != \"\"" (via AssertionError)
[11ty] 
[11ty] Original error stack trace: AssertionError: unexpected "if webmention.url != \"\""
[11ty]     at assert (/Users/zachleat/Code/eleventy/node_modules/liquidjs/dist/liquid.node.cjs.js:358:15)
[11ty]     at assertEmpty (/Users/zachleat/Code/eleventy/node_modules/liquidjs/dist/liquid.node.cjs.js:362:5)
[11ty]     at ParseStream.<anonymous> (/Users/zachleat/Code/eleventy/node_modules/liquidjs/dist/liquid.node.cjs.js:3761:13)
[11ty]     at ParseStream.trigger (/Users/zachleat/Code/eleventy/node_modules/liquidjs/dist/liquid.node.cjs.js:2201:23)
[11ty]     at ParseStream.start (/Users/zachleat/Code/eleventy/node_modules/liquidjs/dist/liquid.node.cjs.js:2209:43)
[11ty]     at new IfTag (/Users/zachleat/Code/eleventy/node_modules/liquidjs/dist/liquid.node.cjs.js:3768:14)
[11ty]     at Parser.parseToken (/Users/zachleat/Code/eleventy/node_modules/liquidjs/dist/liquid.node.cjs.js:2465:24)
[11ty]     at ParseStream.parseToken (/Users/zachleat/Code/eleventy/node_modules/liquidjs/dist/liquid.node.cjs.js:2479:64)
[11ty]     at ParseStream.start (/Users/zachleat/Code/eleventy/node_modules/liquidjs/dist/liquid.node.cjs.js:2212:35)
[11ty]     at new IfTag (/Users/zachleat/Code/eleventy/node_modules/liquidjs/dist/liquid.node.cjs.js:3768:14)
[11ty] Copied 1546 Wrote 24 files in 6.51 seconds (271.3ms each, v3.0.0-alpha.16)
```

After reverting the version for 3.0.0-alpha.16 I’m now realizing this might be an error in my project code?

Related: https://github.com/harttle/liquidjs/issues/713

**Comment by zachleat** [comment]
It was an application code error!

```
{% if webmention.published %}
{% else if webmention.url != "" %}
{% endif %}
```

My code should have been:

```
{% if webmention.published %}
{% elsif webmention.url != "" %}
{% endif %}
```

I reverted too quickly here, there is no issue!
