### ISSUE TITLE
JavaScript template as class can't export any other functions

### ISSUE THREAD

**Issue by pauleveritt** [11ty/eleventy#3359]
### Operating system

macOS Sonoma 14.5

### Eleventy

3.0 alpha 16

### Describe the bug

I'm writing 11ty templates that export a default class. The following works fine:

```javascript
export default class IndexPage {
  render(data) {
    const name = world();
    return <div>Hello</div>;
  }
}

function world() {
  return "World";
}
```

It fails though if `world` is a named export:

```javascript
export default class IndexPage {
  render(data) {
    const name = world();
    return <div>Hello</div>;
  }
}

export function world() {
  return "World";
}
```

Here is the traceback:

```
[11ty] 1. Having trouble rendering 11ty.tsx template ./content/index.11ty.tsx (via TemplateContentRenderError)
[11ty] 2. Class constructor IndexPage cannot be invoked without 'new' (via TypeError)
[11ty] 
[11ty] Original error stack trace: TypeError: Class constructor IndexPage cannot be invoked without 'new'
[11ty]     at JavaScript.<anonymous> (file:///Users/pauleveritt/projects/pauleveritt/www.pauleveritt.org/node_modules/@11ty/eleventy/src/Engines/JavaScript.js:211:39)
[11ty]     at Object.defaultCompilationFn [as defaultRenderer] (file:///Users/pauleveritt/projects/pauleveritt/www.pauleveritt.org/node_modules/@11ty/eleventy/src/Engines/Custom.js:172:12)
[11ty]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[11ty]     at async Object.<anonymous> (file:///Users/pauleveritt/projects/pauleveritt/www.pauleveritt.org/eleventy.config.js:40:25)
[11ty]     at async Template._render (file:///Users/pauleveritt/projects/pauleveritt/www.pauleveritt.org/node_modules/@11ty/eleventy/src/TemplateContent.js:588:19)
[11ty]     at async TemplateMap.populateContentDataInMap (file:///Users/pauleveritt/projects/pauleveritt/www.pauleveritt.org/node_modules/@11ty/eleventy/src/TemplateMap.js:537:7)
[11ty]     at async TemplateMap.cache (file:///Users/pauleveritt/projects/pauleveritt/www.pauleveritt.org/node_modules/@11ty/eleventy/src/TemplateMap.js:444:3)
[11ty]     at async TemplateWriter._createTemplateMap (file:///Users/pauleveritt/projects/pauleveritt/www.pauleveritt.org/node_modules/@11ty/eleventy/src/TemplateWriter.js:346:3)
[11ty]     at async TemplateWriter.generateTemplates (file:///Users/pauleveritt/projects/pauleveritt/www.pauleveritt.org/node_modules/@11ty/eleventy/src/TemplateWriter.js:377:3)
[11ty]     at async TemplateWriter.write (file:///Users/pauleveritt/projects/pauleveritt/www.pauleveritt.org/node_modules/@11ty/eleventy/src/TemplateWriter.js:425:21)
```

(As a note, I'm doing this under `tsx` as the NodeJS runner.)

### Reproduction steps

4. See an error

### Expected behavior

I'd like my template to allow exported other exported functions so I can import them into a test module for tests.

**Comment by zachleat** [comment]
Shipping with 3.0.0-alpha.17 thanks!
