### ISSUE TITLE
Error on serve - eleventyConfig.getFilter(...) is not a function

### ISSUE THREAD

**Issue by reatlat** [11ty/eleventy#3365]
I just bump packages to lates alpha and beta for image plugin, and ` --serve` mode starts show me erros and cant show me images on browser

My packages
```
  "@11ty/eleventy": "^3.0.0-alpha.15",
  "@11ty/eleventy-img": "5.0.0-beta.5",
```

Error log:
```log
[11ty] Server at http://localhost:8080/
[11ty] Unhandled rejection in promise: (more in DEBUG output)
[11ty] eleventyConfig.getFilter(...) is not a function (via TypeError)
[11ty] 
[11ty] Original error stack trace: TypeError: eleventyConfig.getFilter(...) is not a function
[11ty]     at /.11ty/image/ (/Volumes/Work/FreshJuice/freshjuice.dev/node_modules/@11ty/eleventy-img/src/on-request-during-serve-plugin.js:35:108)
[11ty]     at EleventyDevServer.eleventyDevServerMiddleware (/Volumes/Work/FreshJuice/freshjuice.dev/node_modules/@11ty/eleventy-dev-server/server.js:460:28)
[11ty]     at EleventyDevServer.onRequestHandler (/Volumes/Work/FreshJuice/freshjuice.dev/node_modules/@11ty/eleventy-dev-server/server.js:627:11)
[11ty]     at Server.emit (node:events:514:28)
[11ty]     at parserOnIncoming (node:_http_server:1143:12)
[11ty]     at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
```

**Comment by zachleat** [comment]
Shipping with 3.0.0-alpha.17
