### ISSUE TITLE
Eleventy Eleventy 3.0.0-alpha.17 I18nPlugin with ES Module not working

### ISSUE THREAD

**Issue by gasatrya** [11ty/eleventy#3372]
### Operating system

Windows with WSL 2

### Eleventy

3.0.0-alpha.17

### Describe the bug

Hey there,
I tried I18n plugin with es module

```js
import I18nPlugin from '@11ty/eleventy'

export default async function (eleventyConfig) {
  eleventyConfig.addPlugin(I18nPlugin, {
     defaultLanguage: 'en',
   })
}
```

The terminal shows these error

```bash
[11ty] 1. Error processing the `Eleventy` plugin (via EleventyPluginError)
[11ty] 2. Class constructor Eleventy cannot be invoked without 'new' (via TypeError)
[11ty] 
[11ty] Original error stack trace: TypeError: Class constructor Eleventy cannot be invoked without 'new'
[11ty]     at UserConfig._executePlugin (file:///xxx/node_modules/@11ty/eleventy/src/UserConfig.js:642:10)
[11ty]     at TemplateConfig.processPlugins (file:///xxx/node_modules/@11ty/eleventy/src/TemplateConfig.js:318:27)
[11ty]     at async TemplateConfig.mergeConfig (file:///xxx/node_modules/@11ty/eleventy/src/TemplateConfig.js:476:3)
[11ty]     at async TemplateConfig.init (file:///xxx/node_modules/@11ty/eleventy/src/TemplateConfig.js:199:17)
[11ty]     at async Eleventy.initializeConfig (file:///xxx/node_modules/@11ty/eleventy/src/Eleventy.js:192:3)
[11ty]     at async Eleventy.init (file:///xxx/node_modules/@11ty/eleventy/src/Eleventy.js:442:4)
ERROR: "dev:eleventy" exited with 1.
```

Is this a bug @zachleat ?

Thanks!

**Comment by gasatrya** [comment]
Btw, I also tried `EleventyI18nPlugin`, still the same error.

**Comment by zachleat** [comment]
`import { I18nPlugin } from '@11ty/eleventy'` is what you want! It’s a named export

**Comment by gasatrya** [comment]
Nice thanks!
