### ISSUE TITLE
Error when trying to build site.

### ISSUE THREAD

**Issue by mtwb47** [11ty/eleventy#3431]
### Operating system

openSUSE Tumbleweed Linux

### Eleventy

2.0.1

### Describe the bug

I get this error when trying to build my site.

```
[11ty] Eleventy CLI Fatal Error: (more in DEBUG output)
[11ty] 1. Error processing the `eleventyRssPlugin` plugin (via EleventyPluginError)
[11ty] 2. We found Eleventy version '2.0.1' which does not meet the required version range: '>=3.0.0-alpha.15'. Use `npm install @11ty/eleventy` to upgrade your local project to the latest Eleventy version (or `npm install @11ty/eleventy -g` to upgrade the globally installed version). (via UserConfigError)
[11ty] 
[11ty] Original error stack trace: UserConfigError: We found Eleventy version '2.0.1' which does not meet the required version range: '>=3.0.0-alpha.15'. Use `npm install @11ty/eleventy` to upgrade your local project to the latest Eleventy version (or `npm install @11ty/eleventy -g` to upgrade the globally installed version).
[11ty]     at UserConfig.versionCheck (/home/matt/mhome/Documents/Pages/unbuild-site/node_modules/@11ty/eleventy/src/UserConfig.js:115:13)
[11ty]     at eleventyRssPlugin (/home/matt/mhome/Documents/Pages/unbuild-site/node_modules/@11ty/eleventy-plugin-rss/src/rssPlugin.js:12:18)
[11ty]     at UserConfig._executePlugin (/home/matt/mhome/Documents/Pages/unbuild-site/node_modules/@11ty/eleventy/src/UserConfig.js:386:7)
[11ty]     at TemplateConfig.processPlugins (/home/matt/mhome/Documents/Pages/unbuild-site/node_modules/@11ty/eleventy/src/TemplateConfig.js:254:25)
[11ty]     at TemplateConfig.mergeConfig (/home/matt/mhome/Documents/Pages/unbuild-site/node_modules/@11ty/eleventy/src/TemplateConfig.js:367:10)
[11ty]     at TemplateConfig.getConfig (/home/matt/mhome/Documents/Pages/unbuild-site/node_modules/@11ty/eleventy/src/TemplateConfig.js:159:26)
[11ty]     at new Eleventy (/home/matt/mhome/Documents/Pages/unbuild-site/node_modules/@11ty/eleventy/src/Eleventy.js:109:39)
[11ty]     at Object.<anonymous> (/home/matt/mhome/Documents/Pages/unbuild-site/node_modules/@11ty/eleventy/cmd.js:60:16)
[11ty]     at Module._compile (node:internal/modules/cjs/loader:1460:14)
[11ty]     at Module._extensions..js (node:internal/modules/cjs/loader:1544:10)
(node:45935) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node22 --trace-deprecation ...` to show where the warning was created)
```

I don't think it is a bug so much as there is something wrong with my installation. Though it also happened when I tried to build my site on Debian stable as well.

### Reproduction steps

This error occurs when I run `npx @11ty/eleventy`

### Expected behavior

The site should build.

### Reproduction URL

https://thelinuxcast.org

**Comment by VividVisions** [comment]
Which version of the plugin did you install? eleventy-plugin-rss v2 requires Eleventy 3.0 (currently in beta). I think you have to explicitly install v1 of the plugin to work with Eleventy 2.x. 

(Personally, I'd recommend checking out Eleventy 3.0. It's very stable, we already use it in production.)

**Comment by mtwb47** [comment]
Can I ask a noob question and ask how you go about installing that version?

**Comment by bobmonsour** [comment]
The Discord server has a great community willing to answer any questions like this. https://www.11ty.dev/blog/discord/

**Comment by ironnysh** [comment]
Hi @mtwb47, you can use the [Eleventy upgrade helper plugin](https://github.com/11ty/eleventy-upgrade-help), and follow the instructions.

**Comment by mtwb47** [comment]
> > how you go about installing that version?
> 
> Hi @mtwb47, you can use the [Eleventy upgrade helper plugin](https://github.com/11ty/eleventy-upgrade-help), and follow the instructions.

Tried that but end up with the same error that I do when trying to push a new build of my site. The RSSplugin error.

I'm giving up.
