### ISSUE TITLE
Bug Report: Circular Structure Error in Hot Reload with .11ty.js Files

### ISSUE THREAD

**Issue by teamchan3** [11ty/eleventy#3481]
### Operating system

maxOS 15.0.1

### Eleventy

version: 3.0.0

### Describe the bug

I encountered a build error related to circular structure when using .11ty.js files. The error occurs specifically during hot reloading after editing the file.

Steps to Reproduce:

1. Create a new index.11ty.js file with the following content:
`export default "<p>aaa</p>";`

2. Run Eleventy in serve mode:
`npx @11ty/eleventy --serve`

3. Edit and save index.11ty.js in an editor.
4. The following error is thrown in the console, and the hot reload fails:
`reload-client.js:21 [11ty][02:36:03.136 UTC] Build error: Converting circular structure to JSON`

Expected Behavior:

The hot reload should work without throwing an error when editing .11ty.js files.

Actual Behavior:

When editing and saving the file, a “Converting circular structure to JSON” error is thrown, and hot reload does not work.

Error Log:

```
reload-client.js:21 [11ty][02:36:03.136 UTC] Build error: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'page' -> object with constructor 'Object'
    --- property 'rawInput' closes the circle
{stack: 'TypeError: Converting circular structure to JSON\n …de_modules/@11ty/eleventy/src/Eleventy.js:1207:4)', message: "Converting circular structure to JSON\n    --> star…ct'\n    --- property 'rawInput' closes the circle"}
```

•	Eleventy version: 3.0.0
•	Node.js version: 22.1.0
•	OS: maxOS 15.0.1

This issue only seems to occur with .11ty.js files; it does not happen with .njk files. It appears related to the hot reload process involving reload-client.js.

I would appreciate any guidance on how to resolve this or whether a fix is required.

This format should provide enough clarity and detail for the Eleventy team to investigate the issue.

**Comment by zachleat** [comment]
Can anyone else reproduce this one? I tried with the instructions provided and was unable to reproduce.

**Comment by ccoloma** [comment]
[This repo](https://github.com/ccoloma/11ty-with-ts) uses TS (I created it to address another issue related to caching dependencies), but you can reproduce the current error here. Just launch `npm run watch` and update `src/pages/index.11ty.tsx`.

**Comment by abstractvector** [comment]
I am able to reproduce this error. I am also using Typescript. Happy to provide more specific reproduction steps if necessary, but it looks like there are steps to reproduce above now.

**Comment by abstractvector** [comment]
Just been doing a little digging and found the following. The full stack trace from the error above is:

```
"TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'page' -> object with constructor 'Object'
    --- property 'rawInput' closes the circle
    at JSON.stringify (<anonymous>)
    at EleventyDevServer.sendUpdateNotification (/path/to/my/code/node_modules/@11ty/eleventy-dev-server/server.js:799:26)
    at EleventyDevServer.reload (/path/to/my/code/node_modules/@11ty/eleventy-dev-server/server.js:942:10)
    at EleventyServe.reload (file:///path/to/my/code/node_modules/@11ty/eleventy/src/EleventyServe.js:300:22)
    at #watch (file:///path/to/my/code/node_modules/@11ty/eleventy/src/Eleventy.js:965:29)
    at async watchRun (file:///path/to/my/code/node_modules/@11ty/eleventy/src/Eleventy.js:1185:5)
    at async FSWatcher.<anonymous> (file:///path/to/my/code/node_modules/@11ty/eleventy/src/Eleventy.js:1207:4)"
```

If I put a `console.dir(obj, { depth: Infinity });` call just above the call to `JSON.stringify` at `eleventy-dev-server/server.js:799` I get the following output:

```js
{
  type: 'eleventy.reload',
  subtype: undefined,
  files: [ './site/index.11ty.tsx' ],
  build: {
    templates: [
      {
        inputPath: './site/index.11ty.tsx',
        outputPath: './_site/index.html',
        url: '/',
        content: '<div><h1>Hello World</h1></div>',
        rawInput: <ref *1> {
          render: [Function: render],
          page: {
            inputPath: './site/index.11ty.tsx',
            fileSlug: '',
            filePathStem: '/index',
            outputFileExtension: 'html',
            templateSyntax: '11ty.tsx',
            date: 2024-12-02T19:47:43.115Z,
            rawInput: [Circular *1],
            url: '/',
            outputPath: './_site/index.html'
          },
          eleventy: {
            version: '3.0.0',
            generator: 'Eleventy v3.0.0',
            env: {
              source: 'cli',
              runMode: 'serve',
              config: '/path/to/my/code/eleventy.config.ts',
              root: '/path/to/my/code'
            },
            directories: {
              input: './site/',
              inputFile: undefined,
              inputGlob: undefined,
              data: './site/_data/',
              includes: './site/_includes/',
              layouts: undefined,
              output: './_site/'
            }
          },
          getBundle: [Function (anonymous)],
          getBundleFileUrl: [Function (anonymous)],
          inputPathToUrl: [Function (anonymous)],
          slug: [Function (anonymous)],
          slugify: [Function (anonymous)],
          url: [Function (anonymous)],
          log: [Function (anonymous)],
          getCollectionItemIndex: [Function (anonymous)],
          getCollectionItem: [Function (anonymous)],
          getPreviousCollectionItem: [Function (anonymous)],
          getNextCollectionItem: [Function (anonymous)],
          renderTransforms: [Function (anonymous)]
        }
      }
    ]
  }
}
```

So it seems that `obj.build.templates[0].rawInput.page.rawInput` is the circular reference.

From a quick look through the code, I couldn't obviously spot where `rawInput` is including a reference to itself. However, changing the `JSON.stringify` line to the following makes the error go away and hot reloading works fine:

```
client.send(JSON.stringify(obj, function(key, value) { return key === 'rawInput' ? null : value}));
```

Clearly this isn't a solution though.

**Comment by knokmki612** [comment]
I wrote a minimal reproducible code (use 11ty.js template directly)
Could you reproduce with this? @zachleat 
 
https://stackblitz.com/edit/stackblitz-starters-eht2uxn1?file=_includes%2Fbase.11ty.js

**Comment by zachleat** [comment]
A ha, thank you folks — I understand the issue now! Milestoning to v3.0.1.

There are a few options here.

Looks like @knokmki612 opened a PR at #3693 to modify `rawInput` in core, though I would like to keep this feature in place moving forward!

Given that the reload client and dev server doesn’t use `rawInput` I think we can remove it from the object that gets sent to the dev server. https://github.com/11ty/eleventy/blob/7344b74fbe26ff08a01a650681c358da03eef6bd/src/Eleventy.js#L1003

**Comment by zachleat** [comment]
Shipping with v3.0.1-alpha.6

**Comment by knokmki612** [comment]
> I would like to keep this feature in place moving forward!\n\nGiven that the reload client and dev server doesn’t use rawInput I think we can remove it from the object that gets sent to the dev server.

ok, thank you for your great work!
