### ISSUE TITLE
`eleventy --serve` error with JSON imports

### ISSUE THREAD

**Issue by nhoizey** [11ty/eleventy#3491]
### Operating system

macOS 15.0

### Eleventy

3.0.0

### Describe the bug

`eleventy --serve` stops with this error:

```
[11ty] Copied 12 Wrote 26 files in 2.04 seconds (78.6ms each, v3.0.0)
[11ty] Eleventy Error (Watch CLI):
[11ty] 1. A problem was encountered looking for JavaScript dependencies in ESM file: ./src/_data/webmentions.js. This only affects --watch and --serve behavior and does not affect your build. (via EleventyBaseError)
[11ty] 2. Unexpected token (8:37) (via SyntaxError)
[11ty]
[11ty] Original error stack trace: SyntaxError: Unexpected token (8:37)
[11ty]     at pp$4.raise (/path…to/pack11ty/node_modules/acorn/dist/acorn.js:3586:15)
[11ty]     at pp$9.unexpected (/path…to/pack11ty/node_modules/acorn/dist/acorn.js:772:10)
[11ty]     at pp$9.semicolon (/path…to/pack11ty/node_modules/acorn/dist/acorn.js:749:68)
[11ty]     at pp$8.parseImport (/path…to/pack11ty/node_modules/acorn/dist/acorn.js:1851:10)
[11ty]     at pp$8.parseStatement (/path…to/pack11ty/node_modules/acorn/dist/acorn.js:948:51)
[11ty]     at pp$8.parseTopLevel (/path…to/pack11ty/node_modules/acorn/dist/acorn.js:829:23)
[11ty]     at Parser.parse (/path…to/pack11ty/node_modules/acorn/dist/acorn.js:601:17)
[11ty]     at Function.parse (/path…to/pack11ty/node_modules/acorn/dist/acorn.js:651:37)
[11ty]     at Object.parse (/path…to/pack11ty/node_modules/acorn/dist/acorn.js:6024:19)
[11ty]     at findByContents (/path…to/pack11ty/node_modules/@11ty/dependency-tree-esm/main.js:40:18)
```

`token (8:37)` in the error corresponds to the start of `with { type: 'json' };` in this line from my code:

```javascript
import pkg from '../../package.json' with { type: 'json' };
```

So I guess the serve/watch feature doesn't like JSON imports.

Not sure if it's a bug from Eleventy or a dependency.

### Reproduction steps

1. Add a JSON import to your code
2. Run `eleventy --serve`

### Expected behavior

I guess it should watch for changes in the JSON file, like for other resources.

The error says “This only affects --watch and --serve behavior and does not affect your build”, so maybe it's a known bug/limitation?

**Comment by nhoizey** [comment]
I tried to add this to my config, but the error stays the same:

```javascript
eleventyConfig.watchIgnores.add('package.json');
```

**Comment by Ryuno-Ki** [comment]
Are you able to read it from disk using `fs` and parse it afterwards?
I recall having seen something along those lines in the migration guide.

**Comment by nhoizey** [comment]
The error is gone if I disable JavaScript dependencies watching:

```
eleventyConfig.setWatchJavaScriptDependencies(false);
```

But I would like to watch these dependencies of course.

**Comment by nhoizey** [comment]
> Are you able to read it from disk using `fs` and parse it afterwards?

I could, but it would mean that changes in the JSON files (I have other ones, not just `package.json`) are not watched.

> I recall having seen something along those lines in the migration guide.

I don't remember this, will read the guide once again!

**Comment by Ryuno-Ki** [comment]
Appears to be related to #3128.

See https://github.com/11ty/eleventy/issues/3128#issuecomment-1872516498 and following.

**Comment by Ryuno-Ki** [comment]
Perhaps someone in https://github.com/11ty/eleventy/discussions/3196 has also ideas?

**Comment by nhoizey** [comment]
@Ryuno-Ki definitely related to #3128 indeed, so I guess I can close this one. 👍
