### ISSUE TITLE
`eleventyConfig.setFreezeReservedData(false)` unexpected behaviour

### ISSUE THREAD

**Issue by whitep4nth3r** [11ty/eleventy#3536]
### Operating system

macOS Sequoia 15.0.1

### Eleventy

3.0.0

### Describe the bug

Hello!

When upgrading to 11ty 3, the site wouldn't build, and the terminal output instructed me to use `eleventyConfig.setFreezeReservedData(false)` because I was using the variable `content` on a page.

I set `eleventyConfig.setFreezeReservedData(false)` and my site built successfully. I thought that meant I could carry on using the `content` variable.

However, the page using the `content` variable wouldn't render, and output `[object Object]`.

Either I misunderstood what `eleventyConfig.setFreezeReservedData(false)` did (as I presumed I wouldn't need to refactor out the `content` variable, or it didn't work as expected.

Here's the commit where I upgraded to 11ty 3: https://github.com/whitep4nth3r/mk2-p4nth3rblog/commit/d867f256a834b0ec3d9371c1c3ebb70f05ee96c0#diff-c306e0a99961a16f5c5c83996caa0958b94006d97f97475049ea3a08036bb5b0R29

### Reproduction steps

1. Use a `content` variable in a `.js` template
2. Use the `eleventyConfig.setFreezeReservedData(false)` in the `.eleventy` file
3. Observe that the page using the `content` var does not render HTML, except a string of `[object Object]`

### Expected behavior

I expected to continue to be able to use the `content` variable when using `eleventyConfig.setFreezeReservedData(false)`.

### Reproduction URL

https://672b9214f117340008916caf--mk2-p4nth3rblog.netlify.app/sponsorships/

### Screenshots

![image](https://github.com/user-attachments/assets/da4c29ee-3a68-402c-a827-deee7cad914e)

**Comment by zachleat** [comment]
Sorry for the late response but how exactly did you `Use a content variable in a .js template`? Can you link to the code sample for that? Or copy paste it here?

I tried to make a repro locally and `content` from front matter (or returned via the `data` export) seemed to override content in the layout just fine during render

**Comment by whitep4nth3r** [comment]
It was because I named a variable `content` in [this data file](https://github.com/whitep4nth3r/mk2-p4nth3rblog/blob/main/src/sponsorships/sponsorships.11tydata.js) to be able to use in [this template file](https://github.com/whitep4nth3r/mk2-p4nth3rblog/blob/4894d88e46a817cdd5d775aadf276bf536f73421/src/sponsorships/index.11ty.js#L26).

I eventually changed to `sponsorshipsContent` which fixed the issue at the time. Seems like `content` was a reserved word or something.

**Comment by zachleat** [comment]
For next-week me, I see the issue. Setting `content` in a directory data file will override the `content` data expected for use in Eleventy Layouts. We need to have a better error message here.

```js
// src/sponsorships/sponsorships.11tydata.js
const ContentfulSponsorshipPage = require("../../lib/contentfulSponsorshipPage");

module.exports = async function () {
  const content = await ContentfulSponsorshipPage.get({ slug: "sponsorships" });

  return { content };
};
```

**Comment by zachleat** [comment]
I think the main work to be done here is to report WHERE the violation is coming from.

Sample error message in v3.1.2:

```
[11ty] Problem writing Eleventy templates:
[11ty] 1. You attempted to set one of Eleventy’s reserved data property names: content. You can opt-out of this behavior with `eleventyConfig.setFreezeReservedData(false)` or rename/remove the property in your data cascade that conflicts with Eleventy’s reserved property names (e.g. `eleventy`, `pkg`, and others). Learn more: https://v3.11ty.dev/docs/data-eleventy-supplied/ (via EleventyBaseError)
[11ty] 2. Cannot override reserved Eleventy properties: content (via TypeError)
[11ty] 
[11ty] Original error stack trace: TypeError: Cannot override reserved Eleventy properties: content
[11ty]     at ReservedData.check (file:///Users/zachleatherman/Temp/eleventy-3536-b/node_modules/@11ty/eleventy/src/Util/ReservedData.js:55:15)
[11ty]     at #getData (file:///Users/zachleatherman/Temp/eleventy-3536-b/node_modules/@11ty/eleventy/src/Template.js:406:18)
[11ty]     at async TemplateMap.add (file:///Users/zachleatherman/Temp/eleventy-3536-b/node_modules/@11ty/eleventy/src/TemplateMap.js:70:14)
[11ty]     at async Promise.all (index 0)
[11ty]     at async TemplateWriter._addToTemplateMap (file:///Users/zachleatherman/Temp/eleventy-3536-b/node_modules/@11ty/eleventy/src/TemplateWriter.js:340:13)
[11ty]     at async TemplateWriter._createTemplateMap (file:///Users/zachleatherman/Temp/eleventy-3536-b/node_modules/@11ty/eleventy/src/TemplateWriter.js:351:3)
[11ty]     at async TemplateWriter.generateTemplates (file:///Users/zachleatherman/Temp/eleventy-3536-b/node_modules/@11ty/eleventy/src/TemplateWriter.js:382:3)
[11ty]     at async TemplateWriter.write (file:///Users/zachleatherman/Temp/eleventy-3536-b/node_modules/@11ty/eleventy/src/TemplateWriter.js:430:38)
[11ty]     at async Eleventy.executeBuild (file:///Users/zachleatherman/Temp/eleventy-3536-b/node_modules/@11ty/eleventy/src/Eleventy.js:1438:19)
[11ty]     at async #watch (file:///Users/zachleatherman/Temp/eleventy-3536-b/node_modules/@11ty/eleventy/src/Eleventy.js:972:52)
[11ty] Wrote 0 files in 0.01 seconds (v3.1.2)
```

**Comment by zachleat** [comment]
Wait, nope there is another layer here.

```
---
layout: layout.njk
content: "Front matter"
---
Content file: {{ content }}
```

```
Layout: {{ content | safe }}
```

Renders:

```
Layout: Front matter
```

But I would expect:

```
Layout: Content file: Front matter
```

Stay tuned.

**Comment by zachleat** [comment]
Shipping with v4.0.0-alpha.6, specifically when using `eleventyConfig.setFreezeReservedData(false)` you can use the property name `content` in your data cascade (and it will not affect supersede `content` used in Eleventy layout renders)
