### ISSUE TITLE
 TypeError: Invalid URL after upgrading to 11ty 3.0.0

### ISSUE THREAD

**Issue by lennartb-** [11ty/eleventy#3538]
### Operating system

Windows 11 24H2

### Eleventy

3.0.0

### Describe the bug

Hi,

I'm having issues after upgrading my blog repo to 11ty 3.0.0. I used the upgrade helper, but it doesn't seem to report any warnings in my case.

After initially installing upgrade helper and running `npx @11ty/eleventy` I got

```
[11ty] 1. Having trouble rendering njk template ./content/feed/feed.njk (via TemplateContentRenderError)
  Eleventy:EleventyErrorHandler (error stack): TemplateContentRenderError: Having trouble rendering njk template ./content/feed/feed.njk
  Eleventy:EleventyErrorHandler     at Template._render (file:///C:/Users/username/Source/Repos/lennartb.github.io/eleventy/node_modules/@11ty/eleventy/src/TemplateContent.js:624:6)
  Eleventy:EleventyErrorHandler     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
  Eleventy:EleventyErrorHandler     at async TemplateMap.populateContentDataInMap (file:///C:/Users/username/Source/Repos/lennartb.github.io/eleventy/node_modules/@11ty/eleventy/src/TemplateMap.js:545:7)
  Eleventy:EleventyErrorHandler     at async TemplateMap.cache (file:///C:/Users/username/Source/Repos/lennartb.github.io/eleventy/node_modules/@11ty/eleventy/src/TemplateMap.js:451:3)
  Eleventy:EleventyErrorHandler     at async TemplateWriter._createTemplateMap (file:///C:/Users/username/Source/Repos/lennartb.github.io/eleventy/node_modules/@11ty/eleventy/src/TemplateWriter.js:356:3)
  Eleventy:EleventyErrorHandler     at async TemplateWriter.generateTemplates (file:///C:/Users/username/Source/Repos/lennartb.github.io/eleventy/node_modules/@11ty/eleventy/src/TemplateWriter.js:386:3)
  Eleventy:EleventyErrorHandler     at async TemplateWriter.write (file:///C:/Users/username/Source/Repos/lennartb.github.io/eleventy/node_modules/@11ty/eleventy/src/TemplateWriter.js:434:21)
  Eleventy:EleventyErrorHandler     at async Eleventy.executeBuild (file:///C:/Users/username/Source/Repos/lennartb.github.io/eleventy/node_modules/@11ty/eleventy/src/Eleventy.js:1345:19)
  Eleventy:EleventyErrorHandler     at async Eleventy.watch (file:///C:/Users/username/Source/Repos/lennartb.github.io/eleventy/node_modules/@11ty/eleventy/src/Eleventy.js:1155:3) +1ms
[11ty] 2. Invalid URL (via TypeError)
  Eleventy:EleventyErrorHandler (error stack): TypeError: Invalid URL
  Eleventy:EleventyErrorHandler     at new URL (node:internal/url:818:25)
  Eleventy:EleventyErrorHandler     at addPathPrefixToUrl (file:///C:/Users/username/Source/Repos/lennartb.github.io/eleventy/node_modules/@11ty/eleventy/src/Plugins/HtmlBasePlugin.js:12:7)
  Eleventy:EleventyErrorHandler     at Context.<anonymous> (file:///C:/Users/username/Source/Repos/lennartb.github.io/eleventy/node_modules/@11ty/eleventy/src/Plugins/HtmlBasePlugin.js:73:10)
  Eleventy:EleventyErrorHandler     at Context.<anonymous> (file:///C:/Users/username/Source/Repos/lennartb.github.io/eleventy/node_modules/@11ty/eleventy/src/UserConfig.js:419:24)
  Eleventy:EleventyErrorHandler     at Context.fn (file:///C:/Users/username/Source/Repos/lennartb.github.io/eleventy/node_modules/@11ty/eleventy/src/Benchmark/BenchmarkGroup.js:37:23)
  Eleventy:EleventyErrorHandler     at Context.<anonymous> (file:///C:/Users/username/Source/Repos/lennartb.github.io/eleventy/node_modules/@11ty/eleventy/src/Engines/Nunjucks.js:109:15)
  Eleventy:EleventyErrorHandler     at Template.root [as rootRenderFunc] (eval at _compile (C:\Users\username\Source\Repos\lennartb.github.io\eleventy\node_modules\nunjucks\src\environment.js:527:18), <anonymous>:18:73)
  Eleventy:EleventyErrorHandler     at Template.render (C:\Users\username\Source\Repos\lennartb.github.io\eleventy\node_modules\nunjucks\src\environment.js:454:10)
  Eleventy:EleventyErrorHandler     at file:///C:/Users/username/Source/Repos/lennartb.github.io/eleventy/node_modules/@11ty/eleventy/src/Engines/Nunjucks.js:435:10
  Eleventy:EleventyErrorHandler     at new Promise (<anonymous>) +1ms
```

I don't usually work with JS or node, so most of the messages mean nothing to me. If you need more info let me know.

### Reproduction steps

4. See an error

### Reproduction URL

https://github.com/lennartb-/lennartb.github.io/tree/eleventy3upgrade

**Comment by lennartb-** [comment]
Ok, so apparently it couldn't parse `metadata.js`, and I had to change `module.exports = {` to `export default {`. This builds again, but no blog posts are displayed :/ It seems the older `eleventy-base-blog` I used to setup my 2.x blog doesn't upgrade well.

**Comment by Ryuno-Ki** [comment]
Your repo appears to be still written in CommonJS. I cannot start Eleventy 3 with it.
Do you have plans to migrate to ES Modules syntax?

**Comment by zachleat** [comment]
@Ryuno-Ki for the record CommonJS projects still work fine in Eleventy 3

**Comment by lennartb-** [comment]
If I need to rewrite my code to JS's dialect of the week on each update, this isn't suitable for my needs.

**Comment by Ryuno-Ki** [comment]
> @Ryuno-Ki for the record CommonJS projects still work fine in Eleventy 3

I checked the code out and wasn't able to build it. That's why I commented it.

> If I need to rewrite my code to JS's dialect of the week on each update, this doesn't fit my needs.

Understood. Note, that ES Modules is part of the standard now (whereas CommonJS had a different history).
