### ISSUE TITLE
Supported node and npm versions

### ISSUE THREAD

**Issue by thoughtsunificator** [11ty/eleventy#3577]
### Operating system

Linux

### Eleventy

npm test

### Describe the bug

Test are failing on multiple versions of Node.js (18 and onward) using **Eleventy 3.0.0**

Running npm test fails for various reasons:

- `import { register } from "node:module`
> Which is only available since Node.js 20
- DirContainsTest › Compare to parent dir
Fails on all versions of Node.js

I tested using both my machine (Node v23.1.0 and npm 10.9.1) and the Docker images: node:19-alpine to node:23-alpine.

I suggest we clarify which versions of Node are supported in the package.json file, currently it only says "Node.js v18 onward"  which is obviously not the case. We could also add the supported npm version (which is not the same).

Strangely enough, [the CIs all pass](https://github.com/11ty/eleventy/actions/runs/12205443453)?

### Reproduction steps

- Clone 43919d9291b778b504f065863870049d10aff536
- Run `docker run -u $(id -u $USER):$(id -g $USER) -it -v './:/app' -w /app node:23-alpine sh -c 'npm ci && npm test'`

### Expected behavior

Tests should pass

**Comment by thoughtsunificator** [comment]
Some dependencies already state their requirements:
- espree  `"node": "^18.18.0 || ^20.9.0 || >=21.1.0"`
- ava `"node": "^18.18 || ^20.8 || ^22 || >=23"`

**Comment by thoughtsunificator** [comment]
@Ryuno-Ki Did you manage to have the test pass on your setup?

**Comment by Ryuno-Ki** [comment]
Same results with Node v18.20.5.

**Comment by zachleat** [comment]
Please note that there is a distinction between the Node versions that Eleventy supports and the Node versions supported by our devDependencies—they can be different (though that’s not ideal).

`espree` is used by eslint, for example—not a strict requirement for Eleventy.

**Comment by zachleat** [comment]
Test failure on Node 23 is currently filed at #3518

**Comment by thoughtsunificator** [comment]
When running `docker run -u $(id -u $USER):$(id -g $USER) -it -v './:/app' -w /app node:19-alpine sh -c 'npm ci && npm test'`, even with the check it's failing:

<details>
  <summary>Screenshot</summary>
  
![image](https://github.com/user-attachments/assets/2cf85b8d-adeb-4a04-ad85-a574c74ea749)
  
</details>

Maybe I'm wrong, but it looks like the culprit are:

https://github.com/11ty/eleventy/blob/117e7e6b01dd619791619429831d01f72145e92f/test_node/tests.js#L2
https://github.com/11ty/eleventy/blob/117e7e6b01dd619791619429831d01f72145e92f/test_node/MdxTest.js#L6


And when running the version above, `docker run -u $(id -u $USER):$(id -g $USER) -it -v './:/app' -w /app node:20-alpine sh -c 'npm ci && npm test'`:

<details>
  <summary>Screenshot</summary>
  
![image](https://github.com/user-attachments/assets/f8de26ec-c479-4490-b60c-9563bdf33da8)
  
</details>

The test 'DirContainsTest › Compare to parent dir' fails. As I said earlier I cannot pass this test no matter what of Node.js I use, 18, 19, 20, 21, 22, 23...

**Comment by zachleat** [comment]
I’m confused where you’re getting this info, here’s the current dep graph showing the use of `path-scurry`:

<img width="882" alt="image" src="https://github.com/user-attachments/assets/a3beaa0c-8994-4ee0-8f64-1521e50e0270">

https://npmgraph.js.org/?q=%4011ty%2Feleventy#select=exact%3Apath-scurry%401.11.1

v1.11.1 of path-scurry node support `">=16 || 14 >=14.18"` via https://github.com/isaacs/path-scurry/blob/766c9b06aacef86b43c9999cabc5eb824b5958d6/package.json#L67-L69

Happy to look at any other examples you find though!

**Comment by zachleat** [comment]
Ah, that explains some confusion. There are two versions of rimraf here: `v6.0.1` is via devDependency and `v5.0.10` is version used by `@11ty/recursive-copy` (a first-party dependency)

**Comment by zachleat** [comment]
One more thing here, we typically avoid putting resources into debugging odd versions of Node and typically recommend folks use an even number (where possible): https://nodejs.org/en/about/previous-releases

If you feel this policy should be changed, please let me know!

**Comment by zachleat** [comment]
I made a change to `MdxTest.js` to feature test for `module.register` in the _test file_ per your callout above.

**Comment by thoughtsunificator** [comment]
KO on node v19.9.0 (linux) :

```
> @11ty/eleventy@3.0.1-alpha.1 test:node
> node --test test_node/tests.js

ℹ [11ty] Problem writing Eleventy templates:
ℹ [11ty] 1. There was a problem importing 'test/stubs-fancyjs/test.11ty.tsx' via import(esm) (via EleventyImportError)
ℹ [11ty] 2. Unknown file extension ".tsx" for /app/test/stubs-fancyjs/test.11ty.tsx (via TypeError)
ℹ [11ty] 
ℹ [11ty] Original error stack trace: TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".tsx" for /app/test/stubs-fancyjs/test.11ty.tsx
ℹ [11ty]     at new NodeError (node:internal/errors:399:5)
ℹ [11ty]     at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:99:9)
ℹ [11ty]     at defaultGetFormat (node:internal/modules/esm/get_format:139:38)
ℹ [11ty]     at defaultLoad (node:internal/modules/esm/load:83:20)
ℹ [11ty]     at nextLoad (node:internal/modules/esm/hooks:654:28)
ℹ [11ty]     at Hooks.load (node:internal/modules/esm/hooks:445:26)
ℹ [11ty]     at ESMLoader.load (node:internal/modules/esm/loader:337:38)
ℹ [11ty]     at ESMLoader.moduleProvider (node:internal/modules/esm/loader:207:22)
ℹ [11ty]     at new ModuleJob (node:internal/modules/esm/module_job:63:26)
ℹ [11ty]     at #createModuleJob (node:internal/modules/esm/loader:231:17)
✖ Eleventy with JSX (36.955743ms)
  EleventyImportError: "There was a problem importing 'test/stubs-fancyjs/test.11ty.tsx' via import(esm)"
      at file:///app/src/Util/Require.js:192:5
      at async 
      at async 
      at async 
      at async 
      at async TemplateMap.add (file:///app/src/TemplateMap.js:68:14)
      at async Promise.all (index 0)
      at async TemplateWriter._addToTemplateMap (file:///app/src/TemplateWriter.js:342:14)
      at async TemplateWriter._createTemplateMap (file:///app/src/TemplateWriter.js:357:3)
      at async TemplateWriter.generateTemplates (file:///app/src/TemplateWriter.js:389:3)

✔ Eleventy no formats (8.68532ms)
ℹ [11ty] Problem writing Eleventy templates:
ℹ [11ty] 1. There was a problem importing 'test/stubs-fancyjs/test.11ty.tsx' via import(esm) (via EleventyImportError)
ℹ [11ty] 2. Unknown file extension ".tsx" for /app/test/stubs-fancyjs/test.11ty.tsx (via TypeError)
ℹ [11ty] 
ℹ [11ty] Original error stack trace: TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".tsx" for /app/test/stubs-fancyjs/test.11ty.tsx
ℹ [11ty]     at new NodeError (node:internal/errors:399:5)
ℹ [11ty]     at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:99:9)
ℹ [11ty]     at defaultGetFormat (node:internal/modules/esm/get_format:139:38)
ℹ [11ty]     at defaultLoad (node:internal/modules/esm/load:83:20)
ℹ [11ty]     at nextLoad (node:internal/modules/esm/hooks:654:28)
ℹ [11ty]     at Hooks.load (node:internal/modules/esm/hooks:445:26)
ℹ [11ty]     at ESMLoader.load (node:internal/modules/esm/loader:337:38)
ℹ [11ty]     at ESMLoader.moduleProvider (node:internal/modules/esm/loader:207:22)
ℹ [11ty]     at new ModuleJob (node:internal/modules/esm/module_job:63:26)
ℹ [11ty]     at #createModuleJob (node:internal/modules/esm/loader:231:17)
✖ Eleventy JSX --formats=11ty.tsx (7.611089ms)
  EleventyImportError: "There was a problem importing 'test/stubs-fancyjs/test.11ty.tsx' via import(esm)"
      at file:///app/src/Util/Require.js:192:5

✔ Eleventy JSX --formats=tsx (3.73946ms)
✖ Eleventy with MDX (4.420456ms)
  EleventyImportError: "There was a problem importing 'test/stubs-fancyjs/test.mdx' via import(esm)"
      at file:///app/src/Util/Require.js:192:5
      at async 
      at async 
      at async 
      at async 
      at async TemplateMap.add (file:///app/src/TemplateMap.js:68:14)
      at async Promise.all (index 0)
      at async TemplateWriter._addToTemplateMap (file:///app/src/TemplateWriter.js:342:14)
      at async TemplateWriter._createTemplateMap (file:///app/src/TemplateWriter.js:357:3)
      at async TemplateWriter.generateTemplates (file:///app/src/TemplateWriter.js:389:3)

ℹ tests 5
ℹ suites 0
ℹ pass 2
ℹ fail 3
ℹ cancelled 0
ℹ skipped 0
ℹ todo 0
ℹ duration_ms 416.955984

✖ failing tests:

✖ Eleventy with JSX (36.955743ms)
  EleventyImportError: "There was a problem importing 'test/stubs-fancyjs/test.11ty.tsx' via import(esm)"
      at file:///app/src/Util/Require.js:192:5
      at async 
      at async 
      at async 
      at async 
      at async TemplateMap.add (file:///app/src/TemplateMap.js:68:14)
      at async Promise.all (index 0)
      at async TemplateWriter._addToTemplateMap (file:///app/src/TemplateWriter.js:342:14)
      at async TemplateWriter._createTemplateMap (file:///app/src/TemplateWriter.js:357:3)
      at async TemplateWriter.generateTemplates (file:///app/src/TemplateWriter.js:389:3)

✖ Eleventy JSX --formats=11ty.tsx (7.611089ms)
  EleventyImportError: "There was a problem importing 'test/stubs-fancyjs/test.11ty.tsx' via import(esm)"
      at file:///app/src/Util/Require.js:192:5

✖ Eleventy with MDX (4.420456ms)
  EleventyImportError: "There was a problem importing 'test/stubs-fancyjs/test.mdx' via import(esm)"
      at file:///app/src/Util/Require.js:192:5
      at async 
      at async 
      at async 
      at async 

```

**Comment by zachleat** [comment]
`tsx` is not compatible with Node 19: https://github.com/privatenumber/tsx/blob/master/tests/utils/node-versions.ts

**Comment by zachleat** [comment]
Docs shipped to https://www.11ty.dev/docs/javascript-runtime/ and linked from the very top of the Getting Started guide: https://www.11ty.dev/docs/

Contains a specific callout to odd versions of Node: https://www.11ty.dev/docs/javascript-runtime/#odd-versions-of-node-js

Thanks y’all!

**Comment by thoughtsunificator** [comment]
> @thoughtsunificator `tsx` is not compatible with Node 19: https://github.com/privatenumber/tsx/blob/master/tests/utils/node-versions.ts

It's a little off subject but I find it weird that a compatibility layer would instead decrease compatibility.

Thanks for adding it to the documentation.
