### ISSUE TITLE
v3.0.1-alpha.1 Tried to use templateContent too early issue with template concurrency

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#3596]
Probably via #3277 and #3585.

11ty-website `npm run build-production`

```
[11ty] Original error stack trace: TemplateContentPrematureUseError: Tried to use templateContent too early on ./src/docs/quicktips/tag-pages.md
[11ty]     at Object.get [as templateContent] (file:///vercel/path0/node_modules/@11ty/eleventy/src/Template.js:626:14)
[11ty]     at Object.get [as content] (file:///vercel/path0/node_modules/@11ty/eleventy/src/Template.js:646:18)
[11ty]     at Object.memberLookup (/vercel/path0/node_modules/nunjucks/src/runtime.js:201:17)
[11ty]     at eval (eval at _compile (/vercel/path0/node_modules/nunjucks/src/environment.js:527:18), <anonymous>:68:57)
[11ty]     at iterCallback (/vercel/path0/node_modules/nunjucks/src/runtime.js:236:11)
[11ty]     at next (/vercel/path0/node_modules/nunjucks/src/lib.js:258:7)
[11ty]     at eval (eval at _compile (/vercel/path0/node_modules/nunjucks/src/environment.js:527:18), <anonymous>:72:1)
[11ty]     at Context.<anonymous> (file:///vercel/path0/node_modules/@11ty/eleventy/src/UserConfig.js:457:5)
[11ty]     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
```

Viable workaround is to use `eleventyConfig.setConcurrency(1);`

**Comment by zachleat** [comment]
Concurrency default changed to `1` to stay on the safe side for now. Shipping with v3.0.1-alpha.2
