### ISSUE TITLE
Cannot find module 'lodash.merge' (Error)

### ISSUE THREAD

**Issue by mx41** [11ty/eleventy#377]
So I'm having issues since a few hours now, whenever I try to run `npm run build` (which is effectively `eleventy`) I get 

>Problem writing Eleventy templates: (more in DEBUG output)
> Cannot find module \'lodash.merge\' (Error):
    Error: Cannot find module 'lodash.merge'
        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
        at Function.Module._load (internal/modules/cjs/loader.js:507:25)
        at Module.require (internal/modules/cjs/loader.js:637:17)
        at require (internal/modules/cjs/helpers.js:22:18)
        at Object.<anonymous> (/Users/max/mx41/blog/mx41.github.com/node_modules/@11ty/eleventy/src/Engines/JavaScript.js:4:21)
        at Module._compile (internal/modules/cjs/loader.js:689:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
        at Module.load (internal/modules/cjs/loader.js:599:32)
        at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
        at Function.Module._load (internal/modules/cjs/loader.js:530:3)
Processed 0 files in 3.34 seconds
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mx41.github.com@1.0.0 build: `eleventy`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mx41.github.com@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/max/.npm/_logs/2019-01-11T18_50_10_425Z-debug.log`

I thought it is an issue with my node / npm setup, but after uninstalling and reinstalling node several times in different ways (homebrew, manual, now settled with nvm) I am still getting this issue.

I have the slight feeling that it has something to do with my dev machine, as I didn't find anyone else having the problem of missing dependencies.

It should be enough to have @11ty/eleventy as the only dependency for starting out my project, am I right?

**Comment by kleinfreund** [comment]
In https://github.com/11ty/eleventy/blob/master/src/Engines/JavaScript.js#L3-L4, the following two imports are unused:

```js
const dependencyTree = require("dependency-tree");
const lodashMerge = require("lodash.merge");
```

@mx41 Can you do me a favor and open this file, remove these lines at the top and try again? It’s located there on your computer: /Users/max/mx41/blog/mx41.github.com/node_modules/@11ty/eleventy/src/Engines/JavaScript.js (judging from the output you posted).

If it works, I’ll submit a pull request to fix this.

**Comment by zachleat** [comment]
Ahh hmm. I’m not surprised that errors but I am surprised that it doesn’t throw an error on my machine or the travis server.

If that `lodashMerge` were necessary it should be `const lodashMerge = require("lodash/merge");` instead of `"lodash.merge"`

I’m planning on doing a 0.7.1 later today. We can include this.

**Comment by mx41** [comment]
> In [src/Engines/JavaScript.js#L3-L4](https://github.com/11ty/eleventy/blob/master/src/Engines/JavaScript.js#L3-L4), the following two imports are unused:
> 
> ```js
> const dependencyTree = require("dependency-tree");
> const lodashMerge = require("lodash.merge");
> ```
> 
> @mx41 Can you do me a favor and open this file, remove these lines at the top and try again? It’s located there on your computer at `/Users/max/mx41/blog/mx41.github.com/node_modules/@11ty/eleventy/src/Engines/JavaScript.js` (judging from the output you posted).

I tried that, now there is the next dependency missing:
>Problem writing Eleventy templates: (more in DEBUG output)
> Cannot find module 'viperhtml' (Error):
    Error: Cannot find module 'viperhtml'
        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
        at Function.Module._load (internal/modules/cjs/loader.js:507:25)
        at Module.require (internal/modules/cjs/loader.js:637:17)
        at require (internal/modules/cjs/helpers.js:22:18)
        at Object.<anonymous> (/Users/max/mx41/blog/mx41.github.com/node_modules/@11ty/eleventy/test/stubs/viperhtml.11ty.js:1:81)
        at Module._compile (internal/modules/cjs/loader.js:689:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
        at Module.load (internal/modules/cjs/loader.js:599:32)
        at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
        at Function.Module._load (internal/modules/cjs/loader.js:530:3)



> I wonder why it cannot find the module `lodash.merge`. Have you installed all dependencies in your project by running `npm install` in your project’s root directory?

Yes I did `npm install` multiple times even, deleting the entire project, starting from scratch and various npm / node reinstallments.

**Comment by kleinfreund** [comment]
@mx41 Yes, please raise this as a new issue. This time, I don’t see immediately why it doesn’t work.

When you do, can you please run the following commands individually from the Windows console and tell us the output (in the new issue):

```
node -v
npm -v
```

This will print the Node and NPM versions. I’d also like to know which Eleventy version you currently have installed.
