### ISSUE TITLE
Error while generating some pages

### ISSUE THREAD

**Issue by nhoizey** [11ty/eleventy#449]
Hi,

I started a new Eleventy site using Phil Hawksworth's [EleventyOne](https://github.com/philhawksworth/eleventyone) as a starting point, and I struggle adding a new type of content.

The repository is public: https://github.com/nhoizey/precious-prana.com

An exemple build trace on Netlify, with the error: https://app.netlify.com/sites/precious-prana/deploys/5c89f9e3821e51000b865361

Here's the error:

```
7:52:08 AM: 2019-03-14T06:52:08.878Z Eleventy:EleventyErrorHandler Error writing templates:
7:52:08 AM: 2019-03-14T06:52:08.878Z Eleventy:EleventyErrorHandler Having trouble writing template: dist/evenements/2019-03-28-atelier-journal-creatif/index.html (TemplateWriterWriteError)
7:52:08 AM: 2019-03-14T06:52:08.878Z Eleventy:EleventyErrorHandler (error stack): TemplateWriterWriteError: Having trouble writing template: dist/evenements/2019-03-28-atelier-journal-creatif/index.html
7:52:08 AM:     at /opt/build/repo/node_modules/@11ty/eleventy/src/TemplateWriter.js:136:13
7:52:08 AM:     at <anonymous>
7:52:08 AM:     at process._tickCallback (internal/process/next_tick.js:189:7)
7:52:08 AM: 2019-03-14T06:52:08.878Z Eleventy:EleventyErrorHandler (unknown path)
7:52:08 AM:   ReferenceError: sd is not defined (Template render error)
7:52:08 AM: 2019-03-14T06:52:08.878Z Eleventy:EleventyErrorHandler (error stack): Template render error: (unknown path)
7:52:08 AM:   ReferenceError: sd is not defined
7:52:08 AM:     at Object._prettifyError (/opt/build/repo/node_modules/nunjucks/src/lib.js:36:11)
7:52:08 AM:     at /opt/build/repo/node_modules/nunjucks/src/environment.js:545:19
7:52:08 AM:     at Template.root [as rootRenderFunc] (eval at _compile (/opt/build/repo/node_modules/nunjucks/src/environment.js:615:18), <anonymous>:24:3)
7:52:08 AM:     at Template.render (/opt/build/repo/node_modules/nunjucks/src/environment.js:538:10)
7:52:08 AM:     at /opt/build/repo/node_modules/@11ty/eleventy/src/Engines/Nunjucks.js:129:14
7:52:08 AM:     at new Promise (<anonymous>)
7:52:08 AM:     at /opt/build/repo/node_modules/@11ty/eleventy/src/Engines/Nunjucks.js:128:14
7:52:08 AM:     at /opt/build/repo/node_modules/@11ty/eleventy/src/Engines/Markdown.js:67:47
7:52:08 AM:     at TemplateLayout.render (/opt/build/repo/node_modules/@11ty/eleventy/src/TemplateLayout.js:129:31)
7:52:08 AM:     at <anonymous>
```

It comes from pages of `evenement` type, using a Markdown template. Don't ask me why Markdown instead of Nunjucks, I just renamed Phil's `post` files.

I really don't find where this error comes from. I guess I could start from scratch without ElventyOne, but I would like to understand what's wrong.

Thanks.

**Comment by nhoizey** [comment]
Well, I'm really sorry, this was a silly little typo in a filter… 🤦‍♂️

https://github.com/nhoizey/precious-prana.com/commit/17bf346cdacaa2be66ea410203d8eaf527e21f4e
