### ISSUE TITLE
Can't manage to use dates in permalinks

### ISSUE THREAD

**Issue by nhoizey** [11ty/eleventy#459]
I'm trying to use this permalink:

`permalink: "/evenements/{{ page.date | date: '%Y/%m/%d' }}/{{ title | slug }}/"`

Unfortunately, build doesn't work, I get this error (with shorten files paths):

```
Eleventy:TemplateContent Having trouble rendering md template ./src/site/evenements/2019-02-19-atelier-auto-massage-shiatsu.md: "/evenements/{{ page.date | date: '%Y/%m/NaN' }}/{{ title | slug }}/"
  Eleventy:EleventyErrorHandler Problem writing Eleventy templates: +0ms
  Eleventy:EleventyErrorHandler Having trouble rendering md template ./src/site/evenements/2019-02-19-atelier-auto-massage-shiatsu.md (TemplateContentRenderError) +0ms
  Eleventy:EleventyErrorHandler (error stack): TemplateContentRenderError: Having trouble rendering md template ./src/site/evenements/2019-02-19-atelier-auto-massage-shiatsu.md
  Eleventy:EleventyErrorHandler     at Template.render (…precious-prana.com/node_modules/@11ty/eleventy/src/TemplateContent.js:179:13)
  Eleventy:EleventyErrorHandler     at processTicksAndRejections (internal/process/next_tick.js:81:5) +0ms
  Eleventy:EleventyErrorHandler (unknown path) [Line 1, Column 32]
  Eleventy:EleventyErrorHandler   expected variable end (Template render error): +0ms
  Eleventy:EleventyErrorHandler (error stack): Template render error: (unknown path) [Line 1, Column 32]
  Eleventy:EleventyErrorHandler   expected variable end
  Eleventy:EleventyErrorHandler     at Object._prettifyError (…precious-prana.com/node_modules/nunjucks/src/lib.js:36:11)
  Eleventy:EleventyErrorHandler     at Template.render (…precious-prana.com/node_modules/nunjucks/src/environment.js:542:21)
  Eleventy:EleventyErrorHandler     at …precious-prana.com/node_modules/@11ty/eleventy/src/Engines/Nunjucks.js:133:14
  Eleventy:EleventyErrorHandler     at new Promise (<anonymous>)
  Eleventy:EleventyErrorHandler     at …precious-prana.com/node_modules/@11ty/eleventy/src/Engines/Nunjucks.js:132:14
  Eleventy:EleventyErrorHandler     at …precious-prana.com/node_modules/@11ty/eleventy/src/Engines/Markdown.js:61:18
  Eleventy:EleventyErrorHandler     at Template.render (…precious-prana.com/node_modules/@11ty/eleventy/src/TemplateContent.js:167:28)
  Eleventy:EleventyErrorHandler     at processTicksAndRejections (internal/process/next_tick.js:81:5) +0ms
```

I've tried with `date` and `page.date`, in YFM and Directory Data Files, with `date` in YFM or filename, etc.

I don't understand why my permalink definition says `"/evenements/{{ page.date | date: '%Y/%m/%d' }}/{{ title | slug }}/"` and the one in the log says `"/evenements/{{ page.date | date: '%Y/%m/NaN' }}/{{ title | slug }}/"`. `%d` should be valid, isn't it?

I'm using 11ty 0.7.1

**Comment by zachleat** [comment]
We do have this exact thing in our test suite: https://github.com/11ty/eleventy/blob/master/test/stubs/2016-02-01-permalinkdate.liquid#L3

`date: '%Y/%m/%d'` is a Liquid thing though, and you’re trying to use it in Nunjucks.

**Comment by nhoizey** [comment]
OMG, I feel so dumb. Coming from Jekyll, I have too much Liquid in my brain… 😅

Sorry.

**Comment by geshan** [comment]
@nhoizey maybe it is a simple thing, but how did you end up solving this issue?

**Comment by nhoizey** [comment]
@geshan I was not using the right format for dates, if I remember well.

Now, I don't use this anymore, as my source folders match my destination ones, so I don't have to use any permalink.
