### ISSUE TITLE
Error: `Problem writing Eleventy templates`, `Tried to use templateContent too early`

### ISSUE THREAD

**Issue by paulshryock** [11ty/eleventy#505]
I just ran some npm updates, and then tried to run Eleventy. I received an error, so I ran it with debug on, and here's the full error set:

(I've replaced my directory path with `/path/to/directory`)

```bash
Eleventy:EleventyErrorHandler Problem writing Eleventy templates: +0ms
  Eleventy:EleventyErrorHandler Tried to use templateContent too early (./src/pages/404.md) (TemplateContentPrematureUseError): +1ms
  Eleventy:EleventyErrorHandler (error stack): TemplateContentPrematureUseError: Tried to use templateContent too early (./src/pages/404.md)
  Eleventy:EleventyErrorHandler     at Object.get templateContent [as templateContent] (/path/to/directory/node_modules/@11ty/eleventy/src/Template.js:412:19)
  Eleventy:EleventyErrorHandler     at items.map.item (/path/to/directory/.eleventy.js:169:19)
  Eleventy:EleventyErrorHandler     at Array.map (<anonymous>)
  Eleventy:EleventyErrorHandler     at Object.api_pages (/path/to/directory/.eleventy.js:150:16)
  Eleventy:EleventyErrorHandler     at TemplateMap.getUserConfigCollection (/path/to/directory/node_modules/@11ty/eleventy/src/TemplateMap.js:438:47)
  Eleventy:EleventyErrorHandler     at TemplateMap.initDependencyMap (/path/to/directory/node_modules/@11ty/eleventy/src/TemplateMap.js:225:54) +0ms
```

My **package.json** dependencies:

```javascript
{
  "devDependencies": {
    "@11ty/eleventy": "^0.8.2",
    "@babel/core": "^7.4.0",
    "@babel/polyfill": "^7.4.0",
    "@babel/preset-env": "^7.4.2",
    "@babel/register": "^7.4.0",
    "autoprefixer": "^9.5.0",
    "babel-loader": "^8.0.5",
    "css-loader": "^2.1.1",
    "cssnano": "^4.1.10",
    "file-loader": "^3.0.1",
    "html-minifier": "^4.0.0",
    "image-webpack-loader": "^4.6.0",
    "mini-css-extract-plugin": "^0.6.0",
    "postcss-easy-import": "^3.0.0",
    "postcss-loader": "^3.0.0",
    "postcss-node-sass": "^2.1.8",
    "postcss-preset-env": "^6.6.0",
    "precss": "^4.0.0",
    "standard": "^12.0.1",
    "style-loader": "^0.23.1",
    "webpack": "^4.29.6",
    "webpack-cli": "^3.3.0"
  }
}
```

How can I resolve this error?

**Comment by kleinfreund** [comment]
Have a look at https://github.com/11ty/eleventy/issues/479#issuecomment-481524101. This could be the same issue.

**Comment by paulshryock** [comment]
Thanks @kleinfreund, that does look like the same error.

But I'm not using any shortcodes or pagination in my `404.md` file; just standard frontmatter and markdown content. Does that imply it could be a different cause, or am I missing the connection between the two issues?

It ran fine before I ran these npm updates:

```javascript
"@11ty/eleventy": "^0.7.1"  =>  "@11ty/eleventy": "^0.8.2",
"html-minifier": "^3.5.21"  =>  "html-minifier": "^4.0.0"
"mini-css-extract-plugin": "^0.5.0"  =>  "mini-css-extract-plugin": "^0.6.0"

**Comment by kleinfreund** [comment]
I’m pretty sure it’s still the same issue and related to the upgrade of your Eleventy version. Hope 0.8.3 is released soon.

**Comment by paulshryock** [comment]
That makes sense. Thanks @kleinfreund! I appreciate the quick responses. I downgraded to `0.7.1` and the errors went away, so I'll just wait for the `0.8.3` release like you suggested.

**Comment by paulshryock** [comment]
I upgraded to **0.8.3** and the issue is not resolved.

**Related: #551**

**Comment by paulshryock** [comment]
I found the cause of my error:

In `.eleventy.js`, I was adding a custom collection called `apiPages`, which made use of the `templateContent` key. This was considered "too early", and threw the error.

```javascript
module.exports = function(eleventyConfig) {

  eleventyConfig.addCollection("apiPages", function(collection) {

    let items = collection.getAll().filter(function(item) {
      return item.data.contentType == "page"
    });

    return items.map(item => {
      return {
        title: item.data.title,
        excerpt: item.data.excerpt,
        date: item.data.date,
        tags: item.data.tags,
        slug: item.data.slug,
        permalink: item.data.permalink,
        content: item.templateContent,
      }
    })

  })

}
```

I removed the line that says `content: item.templateContent`, and that fixed the error, and Eleventy is able to build.

Problem solved!

But now I wonder how I can still output the collection item's content in the returned object... that will be a task for another day.
