### ISSUE TITLE
Updating to 0.8.3 breaks my pagination (TemplateContentPrematureUseError)

### ISSUE THREAD

**Issue by octoxalis** [11ty/eleventy#551]
I'm using Eleventy for more than a year now, following each update. But I had to stop updating since 0.8, getting a _TemplateContentPrematureUseError_ with my pagination which works perfectly using 0.7.1 version.

I'm now trying to find a solution to be able to update to 0.8.3 and had a look at similar issues, mainly **#479**, but even with 0.8.3, I still have the error (everything else is OK). I don't use pagination keys in a layout.

Is there any way to access global **collections** object within JS  front-matter?

Here is my pagination template (njk) with JS front-matter:
```
---js
{
  pagination:
  {
    data: 'collections.biblio',
    size: 9,
    alias: 'biblio',
  },
  permalink: 'biblio/list_{{ pagination.pageNumber }}.html'
}
---
{% extends "base.njk" %}

{% block content %}
{% set @items = biblio %}
{% set @foldTitle = 'Bibibliographie' %}
{% include "partials/_list_.njk" %}
{% endblock %}

```
Included `partials/_list_.njk` has further nested included templates.

Here is the markdown with only front-matter and no content at all:

```
---js
{
  layout: `layouts/biblio/list.njk`,
  areas:  [ 'menu' ,'text' ],
  active: 'text',
  isList: true,
  title:  `Chercheur d'Art: Bibliographie`,
  date:   `2019-01-30`,
}
---
```

**Comment by paulshryock** [comment]
Same here, I'm getting `TemplateContentPrematureUseError` in **0.8.3**, and have been ever since **0.8**. But I never got this error in previous versions of Eleventy.

Specifically, I have this inside `.eleventy.js`:

```javascript
module.exports = function(eleventyConfig) {

  eleventyConfig.addCollection("api_pages", function(collection) {

    let items = collection.getAll().filter(function(item) {
      return item.data.content_type == "page";
    });

    return items.map(item => {
      return {
        title: item.data.title,
        date: item.data.date,
        tags: item.data.tags,
        inputPath: item.inputPath,
        slug: item.data.slug,
        permalink: item.data.permalink,
        url: item.url,
        outputPath: item.outputPath,
        content: item.templateContent,
      };
    });

  });

}
```

And I get this error:

```bash
Tried to use templateContent too early (./path/to/page.md) (TemplateContentPrematureUseError):
  TemplateContentPrematureUseError: Tried to use templateContent too early (./path/to/page.md)
    at Object.get templateContent [as templateContent] (/path/to/project/node_modules/@11ty/eleventy/src/Template.js:412:19)
    at /path/to/project/.eleventy.js:169:19
    at Array.map (<anonymous>)
    at Object.api_pages (/path/to/project/.eleventy.js:150:16)
```

**Related: #505**

**Comment by paulshryock** [comment]
I don't know if this helps, but I removed this line from my custom collection: `content: item.templateContent`, and that resolved the error for me.

**Comment by zachleat** [comment]
@octoxalis can you provide the content inside `layouts/biblio/list.njk`?

**Comment by octoxalis** [comment]
@zachleat here is the file content:
```
---js
{
  pagination:
  {
    data: 'collections.biblio',
    size: 9,
    alias: 'biblio',
  },
  permalink: 'biblio/list_{{ pagination.pageNumber }}.html'
}
---
{% extends "base.njk" %}

{% block content %}
{% set @items = biblio %}
{% set @foldTitle = 'Bibibliographie' %}
{% include "partials/_list_.njk" %}
{% endblock %}

```
+ Then included `partials/_list_.njk`:
```
{# @items, @foldTitle #}
{% set @asList = ' ca_area_list' %}
{% set @listfolder = ' ca_folder_inverse' %}
{% set @is_open = 'ca_is_open' %}

{% include "partials/blocks/_area_text_.njk" %}

```
+ Then included `partials/blocks/_area_text_.njk`:
```
{% if ( active === 'text' ) %}{% set @active = ' ca_area_active' %}{% endif %}
{% if ( @asList === '') %}
{% set @template = 'partials/_in_text_.njk' %}
{% else %}
{% set @template = 'partials/_fold_items_list_.njk' %}
{% endif %}
{% set @dialog = 'status' %}
{% set @type = '' %}{# status dialog has no type #}

<section id="ca_area_section_text" class="ca_area_region">
  <input id="ca_select_area_text" class="ca_unseen" value="ca_select_area_text" name="area" type="radio">
  <div id="ca_area_text" class="ca_area_text ca_area{{ @active }}{{ @asList }}">
    <label for="ca_select_area_text" class="ca_area_selector" onclick="AreaSwitch( this.getAttribute( 'for') )">
      {% include "partials/icons/menu.svg" %}
    </label>
    {% if not isList and areas.length > 2 %}
    <label class="ca_toggle_text_img" onclick="AreaSwap( 'text', 'gallery' )" title="Voir les images">
      {% include "partials/icons/image.svg" %}
    </label>
    {% endif %}
    {% include @template %}
  </div>
</section>
```
+ Then included `partials/_in_text_.njk` (@template)
```
{# @foldTitle, @id, @author, @date, @is_open, @ dir #}

<div id="ca_blocktxt" class="ca_layout_blocktxt">
  {% include @dir + "/_header_.njk" %}
  {# ==============Markdown========= #}
  {{ layoutContent | map( { permalink:permalink, date:date, title:title, subtitle:subtitle, abstract:abstract, author:author, img:image } ) | safe }}
  {# =============================== #}
</div>
```
_`map` is a filter to produce the site map._

I confess it's a bit complex as a structure...

**Thanks for your help (and this enjoying SSG).**

**Comment by octoxalis** [comment]
I tried again **0.8.3** version, removing the blank line at the end of my `list.md `file.
I have no _TemplateContentPrematureUseError_ but also **no** `list_0.html`... output!

**Comment by zachleat** [comment]
Going to coalesce over at #634 for this!
