### ISSUE TITLE
Eleventy 0.8.3 isn't recognizing layouts directory

### ISSUE THREAD

**Issue by paulshryock** [11ty/eleventy#571]
I'm having trouble getting Eleventy `0.8.3` to recognize my **layouts** directory, as described in the docs: [Configuration: Directory for layouts](https://www.11ty.io/docs/config/#directory-for-layouts-(optional)).

`.eleventy.js`:

```javascript
module.exports = function(eleventyConfig) {
  return {
    dir: {
      input: "src",
      includes: "_includes",
      layouts: "_layouts",
      data: "_data",
      output: "dist"
    }
  };
};
```

I have layout files in `src/_layouts`:

- global.liquid
- single.liquid
- page.liquid
- article.liquid

When I run `DEBUG=Eleventy* npx eleventy`, it looks like all my `dir` directories are discovered except for **layouts**:

```bash
Eleventy Directories:
Eleventy Input: src
Eleventy Data: src/_data
Eleventy Includes: src/_includes
Eleventy Output: dist
Eleventy Template Formats: liquid,ejs,md,hbs,mustache,haml,pug,njk,html,jstl,11ty.js +0ms
```

and further down in the ouput:

```bash
Eleventy:EleventyErrorHandler Problem writing Eleventy templates: +0ms
Eleventy:EleventyErrorHandler You’re trying to use a layout that does not exist: global (undefined) (Error): +1ms
Eleventy:EleventyErrorHandler (error stack): Error: You’re trying to use a layout that does not exist: global (undefined)
Eleventy:EleventyErrorHandler     at TemplateLayoutPathResolver.getFullPath (/path/to/project/node_modules/@11ty/eleventy/src/TemplateLayoutPathResolver.js:63:13)
Eleventy:EleventyErrorHandler     at new TemplateLayout (/path/to/project/node_modules/@11ty/eleventy/src/TemplateLayout.js:19:7)
Eleventy:EleventyErrorHandler     at Function.getTemplate (/path/to/project/node_modules/@11ty/eleventy/src/TemplateLayout.js:39:16)
Eleventy:EleventyErrorHandler     at Template.getData (/path/to/project/node_modules/@11ty/eleventy/src/Template.js:216:37)
Eleventy:EleventyErrorHandler     at async Template.getInitialMapEntry (/path/to/project/node_modules/@11ty/eleventy/src/Template.js:600:16)
Eleventy:EleventyErrorHandler     at async Template.getMapped (/path/to/project/node_modules/@11ty/eleventy/src/Template.js:634:12)
Eleventy:EleventyErrorHandler     at async TemplateMap.add (/path/to/project/node_modules/@11ty/eleventy/src/TemplateMap.js:17:15)
Eleventy:EleventyErrorHandler     at async Promise.all (index 0)
Eleventy:EleventyErrorHandler     at async TemplateWriter._createTemplateMap (/path/to/project/node_modules/@11ty/eleventy/src/TemplateWriter.js:122:3)
Eleventy:EleventyErrorHandler     at async TemplateWriter.write (/path/to/project/node_modules/@11ty/eleventy/src/TemplateWriter.js:159:3) +0ms
```

Do I have this wrongly configured?

**Comment by paulshryock** [comment]
I found why **debug** isn't showing `Eleventy Templates:`, because the block in `@11ty/eleventy/src/Eleventy.js` (lines 165-170) doesn't include [`dir.layouts`](https://www.11ty.io/docs/config/#directory-for-layouts-(optional)):

```javascript
    debug(`Directories:
Input: ${this.inputDir}
Data: ${this.templateData.getDataDir()}
Includes: ${this.eleventyFiles.getIncludesDir()}
Output: ${this.outputDir}
Template Formats: ${formats.join(",")}`);
```

**Comment by paulshryock** [comment]
I created `eleventyFiles.getLayoutsDir` inside `@11ty/eleventy/src/EleventyFiles.js` right after eleventyFiles.getIncludesDir:

```javascript
  getLayoutsDir() {
    return this.layoutsDir;
  }
```

and now I'm getting the expected debug output:

```javascript
Eleventy Directories:
  Eleventy Input: src
  Eleventy Data: src/_data
  Eleventy Includes: src/_includes
  Eleventy Layouts: src/_layouts
  Eleventy Output: dist
```

I also have no idea if this fixed my problem, but I'm **no longer** getting my original error:

```bash
Eleventy:EleventyErrorHandler You’re trying to use a layout that does not exist: global (undefined) (Error): +1ms
```

@zachleat would you mind if I submit this as a pull request?

**Comment by zachleat** [comment]
Hmm, I suspect what happened here might crop up again but I appreciate the PR!
