### ISSUE TITLE
false permalinks: v0.9.0-beta.1  wants distinct values to resolve conflict

### ISSUE THREAD

**Issue by paulrobertlloyd** [11ty/eleventy#639]
**Describe the bug**
I have folder whose contents I don’t want written to disk, so [set the `permalink` value to `false`](https://www.11ty.io/docs/permalinks/#permalink%3A-false) in the folder data file:

```json
{
  "permalink": false,
  "tags": ["testimonial"],
  "vocab": "review"
}
```

Eleventy build fails with `DuplicatePermalinkOutputError`.

**Environment:**
 - OS and Version: macOS 10.14.6
 - Eleventy Version: 0.9.0-beta.1

**Additional context**
0.9.0-beta.1 doesn’t like this!

```
Problem writing Eleventy templates: (more in DEBUG output)
> Output conflict: multiple input files are writing to `false`. Use distinct `permalink` values to resolve this conflict.
  1. ./src/_content/testimonials/emma_begg.md
  2. ./src/_content/testimonials/richard_rutter.md

`DuplicatePermalinkOutputError` was thrown:
    (Repeated output has been truncated…)
        at TemplateMap.checkForDuplicatePermalinks (/Users/paulrobertlloyd/Sites/paulrobertlloyd-v4/node_modules/@11ty/eleventy/src/TemplateMap.js:535:13)
        at TemplateMap.cache (/Users/paulrobertlloyd/Sites/paulrobertlloyd-v4/node_modules/@11ty/eleventy/src/TemplateMap.js:310:10)
        at async TemplateWriter._createTemplateMap (/Users/paulrobertlloyd/Sites/paulrobertlloyd-v4/node_modules/@11ty/eleventy/src/TemplateWriter.js:124:3)
        at async TemplateWriter.write (/Users/paulrobertlloyd/Sites/paulrobertlloyd-v4/node_modules/@11ty/eleventy/src/TemplateWriter.js:155:3)
        at async Eleventy.write (/Users/paulrobertlloyd/Sites/paulrobertlloyd-v4/node_modules/@11ty/eleventy/src/Eleventy.js:423:13)
```

**Comment by zachleat** [comment]
Ugh wow, yep. Sorry about that!

**Comment by zachleat** [comment]
I’ll push another beta here after I triage a few more issues
