### ISSUE TITLE
Override override individual data object properties in nested directory data files

### ISSUE THREAD

**Issue by paulshryock** [11ty/eleventy#692]
I have a page called `child.md` in a nested directory, like this:

```bash
.
└── src
    └── parent
        ├── parent.11tydata.js
        └── child
            ├── child.11tydata.js
            └── child.md
```

The contents of `child.md` are outputting a couple data values:

```markdown
- {{ parent.child1 }}
- {{ parent.child2 }}
```

I have set this data in a directory data file: `/src/parent/parent.11tydata.js`, like this:

```javascript
const data = {
  parent: {
    child1: 'old value',
    child2: 'old value'
  }
}
module.exports = data
```

And I would like to override some of that data in `/src/parent/child/child.11tydata.js`, like this:

```javascript
const data = {}
data.parent.child1 = 'new value'
module.exports = data
```

But when I run `npx eleventy`, I get an error with this output:

```bash
Problem writing Eleventy templates: (more in DEBUG output)
> Cannot set property 'child1' of undefined

`TypeError` was thrown:
    TypeError: Cannot set property 'child1' of undefined
        at Object.<anonymous> (~/project/src/parent/child/child.11tydata.js:3:20)
        at Module._compile (internal/modules/cjs/loader.js:759:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
        at Module.load (internal/modules/cjs/loader.js:628:32)
        at Function.Module._load (internal/modules/cjs/loader.js:555:12)
        at Module.require (internal/modules/cjs/loader.js:666:19)
        at require (internal/modules/cjs/helpers.js:16:16)
        at TemplateData.getDataValue (~/node_modules/@11ty/eleventy/src/TemplateData.js:237:27)
        at async TemplateData.combineLocalData (~/node_modules/@11ty/eleventy/src/TemplateData.js:201:25)
        at async TemplateData.getLocalData (~/node_modules/@11ty/eleventy/src/TemplateData.js:211:24)
Processed 0 files in 0.02 seconds (v0.9.0)
```

So it seems that if I want to override a single data value, I must override all of them in `/src/parent/child/child.11tydata.js`, like this:

```javascript
const data = {
  parent: {
    child1: 'new value',
    child2: 'old value'
  }
}
module.exports = data
```

Is it possible to override **individual** data object properties in nested directory data files without having to override them **all**?

**Comment by paulshryock** [comment]
I figured it out.

I needed to first **require** the parent directory data file inside the child directory data file: `/src/parent/child/child.11tydata.js`, like this:

```javascript
const data = require('../parent.11tydata.js')
data.parent.child1 = 'new value'
module.exports = data
```

Then when I ran `npx eleventy`, the resulting page (`/_site/parent/child/index.html`) had the following desired output:

```html
<ul>
  <li>new value</li>
  <li>old value</li>
</ul>
```
