### ISSUE TITLE
Permalink functions causing exceptions

### ISSUE THREAD

**Issue by justinfagnani** [11ty/eleventy#838]
**Describe the bug**
A permalink function in a data object is never being called, but it's presence is causing an exception.

**To Reproduce**

1. Create a JavaScript template like so:

page.11ty.cjs:
```js
module.exports = class {

  data() {
    return {
      dynamicPermalink: false,
      permalink(data) {
        const date = data.page.date;
        const year = date.getFullYear();
        const month = String(date.getMonth() + 1).padStart(2, '0');
        const day = String(date.getDate()).padStart(2, '0');
        return `/${year}/${month}/${day}/${data.slug}/`;
      },
    }
  }

  render(data) {
    return `<body>${data.content}</body>`;
  }
};
```

2. Create a document:

```markdown
---
title: Permalink Functions
date: 2019-12-30 15:00:00
slug: permalink-functions
---
Permalink functions don't seem to work...
```

3. Run eleventy

If `dynamicPermalink` is true, this error is thrown:

```
`TemplateContentCompileError` was thrown
> illegal input

`AssertionError` was thrown:
    AssertionError: illegal input
        at assert (/Users/justinfagnani/Projects/Personal/justinfagnani-com/packages/client/node_modules/liquidjs/dist/liquid.common.js:1062:11)
        at parse (/Users/justinfagnani/Projects/Personal/justinfagnani-com/packages/client/node_modules/liquidjs/dist/liquid.common.js:1426:3)
        at Object.parse$$1 [as parse] (/Users/justinfagnani/Projects/Personal/justinfagnani-com/packages/client/node_modules/liquidjs/dist/liquid.common.js:3419:18)
        at Liquid.compile (/Users/justinfagnani/Projects/Personal/justinfagnani-com/packages/client/node_modules/@11ty/eleventy/src/Engines/Liquid.js:181:29)
        at Markdown.compile (/Users/justinfagnani/Projects/Personal/justinfagnani-com/packages/client/node_modules/@11ty/eleventy/src/Engines/Markdown.js:63:25)
        at TemplateRender.getCompiledTemplate (/Users/justinfagnani/Projects/Personal/justinfagnani-com/packages/client/node_modules/@11ty/eleventy/src/TemplateRender.js:192:26)
        at Template.compile (/Users/justinfagnani/Projects/Personal/justinfagnani-com/packages/client/node_modules/@11ty/eleventy/src/TemplateContent.js:167:42)
        at async Template.render (/Users/justinfagnani/Projects/Personal/justinfagnani-com/packages/client/node_modules/@11ty/eleventy/src/TemplateContent.js:181:16)
        at async Template._getLink (/Users/justinfagnani/Projects/Personal/justinfagnani-com/packages/client/node_modules/@11ty/eleventy/src/Template.js:102:26)
        at async Template.getOutputHref (/Users/justinfagnani/Projects/Personal/justinfagnani-com/packages/client/node_modules/@11ty/eleventy/src/Template.js:137:16)
```

If `dynamicPermalink` is false, this error is thrown:

```
> link.substr is not a function

`TypeError` was thrown:
    TypeError: link.substr is not a function
        at TemplatePermalink._cleanLink (/Users/justinfagnani/Projects/Personal/justinfagnani-com/packages/client/node_modules/@11ty/eleventy/src/TemplatePermalink.js:10:23)
        at new TemplatePermalink (/Users/justinfagnani/Projects/Personal/justinfagnani-com/packages/client/node_modules/@11ty/eleventy/src/TemplatePermalink.js:5:20)
        at Template._getLink (/Users/justinfagnani/Projects/Personal/justinfagnani-com/packages/client/node_modules/@11ty/eleventy/src/Template.js:112:18)
        at Template.getOutputHref (/Users/justinfagnani/Projects/Personal/justinfagnani-com/packages/client/node_modules/@11ty/eleventy/src/Template.js:137:27)
        at Template.getTemplates (/Users/justinfagnani/Projects/Personal/justinfagnani-com/packages/client/node_modules/@11ty/eleventy/src/Template.js:397:34)
        at TemplateMap.initDependencyMap (/Users/justinfagnani/Projects/Personal/justinfagnani-com/packages/client/node_modules/@11ty/eleventy/src/TemplateMap.js:246:41)
        at async TemplateMap.cache (/Users/justinfagnani/Projects/Personal/justinfagnani-com/packages/client/node_modules/@11ty/eleventy/src/TemplateMap.js:279:5)
        at async TemplateWriter._createTemplateMap (/Users/justinfagnani/Projects/Personal/justinfagnani-com/packages/client/node_modules/@11ty/eleventy/src/TemplateWriter.js:124:3)
        at async TemplateWriter.write (/Users/justinfagnani/Projects/Personal/justinfagnani-com/packages/client/node_modules/@11ty/eleventy/src/TemplateWriter.js:155:3)
        at async Eleventy.write (/Users/justinfagnani/Projects/Personal/justinfagnani-com/packages/client/node_modules/@11ty/eleventy/src/Eleventy.js:428:13)
```

It looks like the permalink function is always interpreted as a string, and never called.

**Expected behavior**
The permalink function is called.

**Environment:**

- OS and Version: macOS 10.14.6
- Eleventy Version: 0.9.0

**Comment by oliverjam** [comment]
I just hit this issue as well. I think this might be the problem:

> These will be parsed with the current template’s rendering engine  
[Use Data Variables in Permalink](https://www.11ty.dev/docs/permalinks/#use-data-variables-in-permalink)

Since your template is markdown the permalink is parsed using Liquid (the default Markdown templating engine), even though the permalink itself is defined in a JS file.

I initially worked around this by specifying the permalink using a Liquid string (e.g. `permalink: "{{page.filePath}}"`), but this breaks the second you have a different template engine. I have mostly markdown in a directory, plus some `11ty.js` templates. The JS templates appear to just output the permalink as a string literal, so I get files like `_site/{{page.filePath}}/index.html`

**Comment by zachleat** [comment]
#3472 was the issue that improved some of the error messaging here.

**Comment by zachleat** [comment]
I think I’m open to changing the behavior here and to make `dynamicPermalink` specific to template syntax processing only.

If we find a permalink JavaScript `function` in the data cascade, we will execute that (and ignore the value of `dynamicPermalink`)

**Comment by zachleat** [comment]
Though, just thinking out loud, why are we using `dynamicPermalink: false` at all here?

It might be most consistent to keep the current behavior and remind folks about `dynamicPermalink` in the error messaging here, as @uncenter suggested.

**Comment by zachleat** [comment]
One more vote to allow `function` to bypass this behavior as it would improve the global case https://www.11ty.dev/docs/permalinks/#globally-disable-templating-in-permalinks but I’ll just leave as-is for now

**Comment by zachleat** [comment]
Sample error message from the test case:

```
[11ty] Problem writing Eleventy templates:
[11ty] 1. Error generating template page(s) for ./page.11ty.cjs. (via EleventyMapPagesError)
[11ty] 2. Expected permalink value to be a string. Received `function` (dynamicPermalink: false):
[11ty] 
[11ty] permalink(data) {
[11ty]         const date = data.page.date;
[11ty]         const year = date.getFullYear();
[11ty]         const month = String(date.getMonth() + 1).padStart(2, '0');
[11ty]         const day = String(date.getDate()).padStart(2, '0');
[11ty]         return `/${year}/${month}/${day}/${data.slug}/`;
[11ty]       }
```
