### ISSUE TITLE
[0.3.0][Windows:7] Can't use pagination

### ISSUE THREAD

**Issue by chrisdmacrae** [11ty/eleventy#89]
I'm attempting to use pagination on a front matter key with the following structure:

```
---
steps:
- one
- two
pagination:
  data: steps
  size: 1
---
```

And I get the following error:
```
Problem writing eleventy templates:
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string
    at assertPath (path.js:28:11)
    at Object.dirname (path.js:714:5)
    at outputFile (C:\Users\CDMACRAE\Development\style-guide-comms\node_modules\@11ty\eleventy\node_modules\fs-extra\lib\output\index.js:15:20)
    at outputFile (C:\Users\CDMACRAE\Development\style-guide-comms\node_modules\universalify\index.js:5:67)
    at P (C:\Users\CDMACRAE\Development\style-guide-comms\node_modules\pify\index.js:49:6)
    at new Promise (<anonymous>)
    at C:\Users\CDMACRAE\Development\style-guide-comms\node_modules\pify\index.js:11:9
    at ret (C:\Users\CDMACRAE\Development\style-guide-comms\node_modules\pify\index.js:72:32)
    at Template.write (C:\Users\CDMACRAE\Development\style-guide-comms\node_modules\@11ty\eleventy\src\Template.js:452:32)
    at <anonymous>
```

The debug is as follows:
```
$ DEBUG=* eleventy
2018-03-27T19:32:25.882Z Eleventy:Config Setting up global TemplateConfig.
2018-03-27T19:32:25.883Z Eleventy:EleventyConfig Adding universal filter 'slug'
2018-03-27T19:32:25.883Z Eleventy:EleventyConfig Adding universal filter 'url'
2018-03-27T19:32:25.884Z Eleventy:TemplateConfig rootConfig { templateFormats: [ 'liquid', 'ejs', 'md', 'hbs', 'mustache', 'haml', 'pug', 'njk', 'html', 'jstl' ], pathPrefix: '/', markdownTemplateEngine: 'liquid', htmlTemplateEngine: 'liquid', dataTemplateEngine: 'liquid', passthroughFileCopy: true, htmlOutputSuffix: '-o', keys: { package: 'pkg', layout: 'layout', permalink: 'permalink', permalinkRoot: 'permalinkBypassOutputDir', engineOverride: 'templateEngineOverride' }, dir: { input: '.', includes: '_includes', data: '_data', output: '_site' }, filters: {}, handlebarsHelpers: {}, nunjucksFilters: {} }
2018-03-27T19:32:25.885Z Eleventy:TemplateConfig Merging config with C:/Users/CDMACRAE/Development/style-guide-comms/.eleventy.js
2018-03-27T19:32:25.887Z Eleventy:TemplateConfig localConfig: { dir: { input: 'style-guide/', includes: '../src/', data: '_data', output: 'dist' }, dataTemplateEngine: 'ejs', markdownTemplateEngine: 'ejs', htmlTemplateEngine: 'ejs', templateFormats: [ 'md', 'html', 'png', 'jpg', 'jpeg', 'gif', 'svg' ], passthroughFileCopy: true, liquidTags: {}, liquidFilters: { slug: [Function], url: [Function] }, nunjucksFilters: { slug: [Function], url: [Function] }, nunjucksAsyncFilters: {}, handlebarsHelpers: { slug: [Function], url: [Function] }, filters: {}, layoutAliases: {}, passthroughCopies: {} }
2018-03-27T19:32:25.887Z Eleventy:TemplateConfig overrides: {}
2018-03-27T19:32:25.888Z Eleventy:TemplateConfig Current configuration: { templateFormats: [ 'md', 'html', 'png', 'jpg', 'jpeg', 'gif', 'svg' ], pathPrefix: '/', markdownTemplateEngine: 'ejs', htmlTemplateEngine: 'ejs', dataTemplateEngine: 'ejs', passthroughFileCopy: true, htmlOutputSuffix: '-o', keys: { package: 'pkg', layout: 'layout', permalink: 'permalink', permalinkRoot: 'permalinkBypassOutputDir', engineOverride: 'templateEngineOverride' }, dir: { input: 'style-guide/', includes: '../src/', data: '_data', output: 'dist' }, filters: {}, handlebarsHelpers: { slug: [Function], url: [Function] }, nunjucksFilters: { slug: [Function], url: [Function] }, liquidTags: {}, liquidFilters: { slug: [Function], url: [Function] }, nunjucksAsyncFilters: {}, layoutAliases: {}, passthroughCopies: {} }
2018-03-27T19:32:25.992Z Eleventy-CLI command: eleventy
2018-03-27T19:32:25.994Z Eleventy:TemplateWriter .gitignore ignoring: ./dist
2018-03-27T19:32:25.994Z Eleventy:TemplateWriter .gitignore ignoring: ./*.tmp.css
2018-03-27T19:32:25.995Z Eleventy:TemplateWriter .gitignore ignoring: ./node_modules
2018-03-27T19:32:25.995Z Eleventy:TemplateWriter .gitignore ignoring: ./yarn.lock
2018-03-27T19:32:25.995Z Eleventy Directories:
Input: style-guide/
Data: style-guide//_data
Includes: style-guide//../src/
Output: dist
Template Formats: md,html,png,jpg,jpeg,gif,svg
2018-03-27T19:32:26.014Z Eleventy:TemplateData Found global data file ./style-guide/_data/globals.json and adding as: globals
2018-03-27T19:32:26.022Z Eleventy:TemplateData Found global data file ./style-guide/_data/menus/header/default.json and adding as: menus.header.default
2018-03-27T19:32:26.023Z Eleventy:TemplateData Found global data file ./style-guide/_data/menus/header/docs.json and adding as: menus.header.docs
2018-03-27T19:32:26.024Z Eleventy:TemplateData Found global data file ./style-guide/_data/menus/header/guides.json and adding as: menus.header.guides
2018-03-27T19:32:26.024Z Eleventy:TemplateData Found global data file ./style-guide/_data/menus/main.json and adding as: menus.main
2018-03-27T19:32:26.025Z Eleventy:TemplateData Found global data file ./style-guide/_data/menus/policies.json and adding as: menus.policies
2018-03-27T19:32:26.025Z Eleventy:TemplateWriter Searching for: [ './style-guide/**/*.md',
  './style-guide/**/*.html',
  './style-guide/**/*.png',
  './style-guide/**/*.jpg',
  './style-guide/**/*.jpeg',
  './style-guide/**/*.gif',
  './style-guide/**/*.svg',
  '!./dist/**',
  '!./*.tmp.css',
  '!./node_modules/**',
  '!./yarn.lock',
  '!./dist/**',
  '!./src/**',
  '!./style-guide/_data/**' ]
2018-03-27T19:32:26.032Z Eleventy:TemplateWriter Found: [ './style-guide/_example.md', './style-guide/colors.md', './style-guide/components/index.md', './style-guide/guides/index.md', './style-guide/index.md' ]
2018-03-27T19:32:26.032Z Eleventy:TemplateWriter TemplatePassthrough copy started.
2018-03-27T19:32:26.033Z Eleventy:TemplateWriter TemplatePassthrough copied 0 items.
2018-03-27T19:32:26.033Z Dev:Eleventy:Template new Template('./style-guide/_example.md')
2018-03-27T19:32:26.101Z Dev:Eleventy:Template './style-guide/_example.md' getMapped()
2018-03-27T19:32:26.102Z Dev:Eleventy:Template './style-guide/_example.md' getData()
2018-03-27T19:32:26.103Z Dev:Eleventy:Template './style-guide/_example.md' getAllLayoutFrontMatterData
2018-03-27T19:32:26.104Z Eleventy:Template getMappedDate: using file created time for './style-guide/_example.md' of 2018-03-26T19:03:16.173Z
2018-03-27T19:32:26.104Z Eleventy:TemplateWriter Template for ./style-guide/_example.md added to map.
2018-03-27T19:32:26.104Z Dev:Eleventy:Template new Template('./style-guide/colors.md')
2018-03-27T19:32:26.105Z Dev:Eleventy:Template './style-guide/colors.md' getMapped()
2018-03-27T19:32:26.105Z Dev:Eleventy:Template './style-guide/colors.md' getData()
2018-03-27T19:32:26.106Z Dev:Eleventy:Template './style-guide/colors.md' getAllLayoutFrontMatterData
2018-03-27T19:32:26.107Z Eleventy:Template getMappedDate: using file created time for './style-guide/colors.md' of 2018-03-26T19:03:16.182Z
2018-03-27T19:32:26.107Z Eleventy:TemplateWriter Template for ./style-guide/colors.md added to map.
2018-03-27T19:32:26.107Z Dev:Eleventy:Template new Template('./style-guide/components/index.md')
2018-03-27T19:32:26.107Z Dev:Eleventy:Template './style-guide/components/index.md' getMapped()
2018-03-27T19:32:26.107Z Dev:Eleventy:Template './style-guide/components/index.md' getData()
2018-03-27T19:32:26.108Z Dev:Eleventy:Template './style-guide/components/index.md' getAllLayoutFrontMatterData
2018-03-27T19:32:26.108Z Eleventy:Template getMappedDate: using file created time for './style-guide/components/index.md' of 2018-03-26T19:03:16.192Z
2018-03-27T19:32:26.108Z Eleventy:TemplateWriter Template for ./style-guide/components/index.md added to map.
2018-03-27T19:32:26.108Z Dev:Eleventy:Template new Template('./style-guide/guides/index.md')
2018-03-27T19:32:26.109Z Dev:Eleventy:Template './style-guide/guides/index.md' getMapped()
2018-03-27T19:32:26.109Z Dev:Eleventy:Template './style-guide/guides/index.md' getData()
2018-03-27T19:32:26.110Z Dev:Eleventy:Template './style-guide/guides/index.md' getAllLayoutFrontMatterData
2018-03-27T19:32:26.110Z Eleventy:Template getMappedDate: using file created time for './style-guide/guides/index.md' of 2018-03-27T18:58:01.635Z
2018-03-27T19:32:26.110Z Eleventy:TemplateWriter Template for ./style-guide/guides/index.md added to map.
2018-03-27T19:32:26.110Z Dev:Eleventy:Template new Template('./style-guide/index.md')
2018-03-27T19:32:26.110Z Dev:Eleventy:Template './style-guide/index.md' getMapped()
2018-03-27T19:32:26.110Z Dev:Eleventy:Template './style-guide/index.md' getData()
2018-03-27T19:32:26.111Z Dev:Eleventy:Template './style-guide/index.md' getAllLayoutFrontMatterData
2018-03-27T19:32:26.111Z Eleventy:Template getMappedDate: using file created time for './style-guide/index.md' of 2018-03-15T18:28:39.635Z
2018-03-27T19:32:26.111Z Eleventy:TemplateWriter Template for ./style-guide/index.md added to map.
2018-03-27T19:32:26.111Z Eleventy:TemplateMap Caching collections objects.
2018-03-27T19:32:26.115Z Eleventy:TemplateMap Collection: collections.all has 5 items.
2018-03-27T19:32:26.116Z Eleventy:TemplateMap Collection: collections.docs has 3 items.
2018-03-27T19:32:26.117Z Eleventy:TemplateMap Collection: collections.components has 1 items.
2018-03-27T19:32:26.117Z Dev:Eleventy:TemplateMap Added this.map[...].data.collections
2018-03-27T19:32:26.118Z Dev:Eleventy:Template './style-guide/_example.md' render()
2018-03-27T19:32:26.118Z Dev:Eleventy:Template Template.render is bypassing layouts for './style-guide/_example.md'.
2018-03-27T19:32:26.118Z Dev:Eleventy:Template Template.render renderContent for './style-guide/_example.md'
2018-03-27T19:32:26.118Z Dev:Eleventy:Template './style-guide/_example.md' renderContent() using 'md'
2018-03-27T19:32:26.123Z Dev:Eleventy:Template './style-guide/colors.md' render()
2018-03-27T19:32:26.123Z Dev:Eleventy:Template Template.render is bypassing layouts for './style-guide/colors.md'.
2018-03-27T19:32:26.123Z Dev:Eleventy:Template Template.render renderContent for './style-guide/colors.md'
2018-03-27T19:32:26.123Z Dev:Eleventy:Template './style-guide/colors.md' renderContent() using 'md'
2018-03-27T19:32:26.125Z Dev:Eleventy:Template './style-guide/components/index.md' render()
2018-03-27T19:32:26.125Z Dev:Eleventy:Template Template.render is bypassing layouts for './style-guide/components/index.md'.
2018-03-27T19:32:26.126Z Dev:Eleventy:Template Template.render renderContent for './style-guide/components/index.md'
2018-03-27T19:32:26.126Z Dev:Eleventy:Template './style-guide/components/index.md' renderContent() using 'md'
2018-03-27T19:32:26.126Z Dev:Eleventy:Template new Template('./style-guide/guides/index.md')
2018-03-27T19:32:26.127Z Dev:Eleventy:Template './style-guide/guides/index.md' render()
2018-03-27T19:32:26.127Z Dev:Eleventy:Template './style-guide/guides/index.md' getData()
2018-03-27T19:32:26.128Z Dev:Eleventy:Template './style-guide/guides/index.md' getAllLayoutFrontMatterData
2018-03-27T19:32:26.128Z Eleventy:Template getMappedDate: using file created time for './style-guide/guides/index.md' of 2018-03-27T18:58:01.635Z
2018-03-27T19:32:26.128Z Dev:Eleventy:Template Template.render found layout: '/layouts/guide/index.ejs'
2018-03-27T19:32:26.128Z Dev:Eleventy:Template renderLayout('./style-guide/guides/index.md'): '/layouts/guide/index.ejs'
2018-03-27T19:32:26.128Z Dev:Eleventy:Template No layout name saved, saving: '/layouts/guide/index.ejs' for './style-guide/guides/index.md'
2018-03-27T19:32:26.128Z Dev:Eleventy:Template Layout deleted from data ('layout'): undefined
2018-03-27T19:32:26.129Z Dev:Eleventy:Template new Template('style-guide/../src///layouts/guide/index.ejs')
2018-03-27T19:32:26.129Z Dev:Eleventy:Template 'style-guide/../src///layouts/guide/index.ejs' getData()
2018-03-27T19:32:26.129Z Dev:Eleventy:Template 'style-guide/../src///layouts/guide/index.ejs' getAllLayoutFrontMatterData
2018-03-27T19:32:26.129Z Dev:Eleventy:Template new Template('style-guide/../src///layouts/base/index.ejs')
2018-03-27T19:32:26.129Z Dev:Eleventy:Template 'style-guide/../src///layouts/guide/index.ejs' getAllLayoutFrontMatterData
2018-03-27T19:32:26.129Z Dev:Eleventy:Template './style-guide/guides/index.md' renderContent() using 'md'
2018-03-27T19:32:26.130Z Dev:Eleventy:Template renderLayout found another layout '/layouts/base/index.ejs' ('./style-guide/guides/index.md')
2018-03-27T19:32:26.130Z Dev:Eleventy:Template renderLayout('style-guide/../src///layouts/guide/index.ejs'): '/layouts/base/index.ejs'
2018-03-27T19:32:26.130Z Dev:Eleventy:Template Layout deleted from data ('layout'): undefined
2018-03-27T19:32:26.130Z Dev:Eleventy:Template Found 'style-guide/../src///layouts/base/index.ejs' in TemplateCache
2018-03-27T19:32:26.130Z Dev:Eleventy:Template 'style-guide/../src///layouts/base/index.ejs' getData()
2018-03-27T19:32:26.130Z Dev:Eleventy:Template 'style-guide/../src///layouts/base/index.ejs' getAllLayoutFrontMatterData
2018-03-27T19:32:26.130Z Dev:Eleventy:Template 'style-guide/../src///layouts/guide/index.ejs' renderContent() using 'ejs'
2018-03-27T19:32:26.132Z Dev:Eleventy:Template 'style-guide/../src///layouts/base/index.ejs' renderContent() using 'ejs'

Problem writing eleventy templates:
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string
    at assertPath (path.js:28:11)
    at Object.dirname (path.js:714:5)
    at outputFile (C:\Users\CDMACRAE\AppData\Local\Yarn\config\global\node_modules\fs-extra\lib\output\index.js:15:20)
    at outputFile (C:\Users\CDMACRAE\AppData\Local\Yarn\config\global\node_modules\universalify\index.js:5:67)
    at P (C:\Users\CDMACRAE\AppData\Local\Yarn\config\global\node_modules\@11ty\eleventy\node_modules\pify\index.js:49:6)
    at new Promise (<anonymous>)
    at C:\Users\CDMACRAE\AppData\Local\Yarn\config\global\node_modules\@11ty\eleventy\node_modules\pify\index.js:11:9
    at ret (C:\Users\CDMACRAE\AppData\Local\Yarn\config\global\node_modules\@11ty\eleventy\node_modules\pify\index.js:72:32)
    at Template.write (C:\Users\CDMACRAE\AppData\Local\Yarn\config\global\node_modules\@11ty\eleventy\src\Template.js:452:32)
    at <anonymous>


Start time: (2018-03-27 19:32:24 UTC) [treshold=1%]
 #  module                           time  %
 1  check-node-ver...ion\index.js)   21ms  ■ 2%
 2  ./src/VersionC...sionCheck.js)   23ms  ■ 2%
 3  chalk (..\..\A...alk\index.js)   14ms  ■ 1%
 4  fs-extra (..\....lib\index.js)   55ms  ■■ 4%
 5  glob (..\..\Ap...glob\glob.js)   19ms  ■ 2%
 6  globby (..\..\...bby\index.js)   36ms  ■ 3%
 7  ./Config (..\....rc\Config.js)   20ms  ■ 2%
 8  ./TemplateRend...ateRender.js)   26ms  ■ 2%
 9  ./TemplateData...plateData.js)  125ms  ■■■ 10%
10  ./schema/defau...ault_safe.js)   18ms  ■ 1%
11  esprima (..\.....t\esprima.js)   26ms  ■ 2%
12  ../type/js/fun...\function.js)   27ms  ■ 2%
13  ./schema/defau...ault_full.js)   31ms  ■ 2%
14  ./js-yaml/load...ml\loader.js)   53ms  ■■ 4%
15  ./lib/js-yaml....b\js-yaml.js)   56ms  ■■ 4%
16  js-yaml (..\.....aml\index.js)   58ms  ■■ 5%
17  ./engines (..\...b\engines.js)   59ms  ■■ 5%
18  ./defaults (.....\defaults.js)   63ms  ■■ 5%
19  ./lib/parse (....lib\parse.js)   65ms  ■■ 5%
20  gray-matter (....ter\index.js)   71ms  ■■ 6%
21  ./Template (.....\Template.js)   87ms  ■■■ 7%
22  ./TemplateWrit...ateWriter.js)  103ms  ■■■ 8%
23  ./src/Eleventy...\Eleventy.js)  254ms  ■■■■■■■ 20%
24  ./common/utils...mon\utils.js)   15ms  ■ 1%
25  ./parser_inlin...er_inline.js)   13ms  ■ 1%
26  ./lib/ (..\..\...lib\index.js)   58ms  ■■ 5%
27  markdown-it (....-it\index.js)   59ms  ■■ 5%
28  ./Markdown (.....\Markdown.js)   64ms  ■■ 5%
Total require(): 593
Total time: 1.3s
```

**Comment by chrisdmacrae** [comment]
EleventyConfig is as follows; wonder if this has something to do with path resolution differences between UNIX and Windows?

```
/**
 * Configuration for the static site generator, eleventy
 * http://11ty.io/
 **/
module.exports = {
  dir: {
    input: "style-guide/",
    includes: "../src/",
    data: "_data",
    output: "dist"
  },
  dataTemplateEngine: "ejs",
  markdownTemplateEngine: "ejs",
  htmlTemplateEngine: "ejs",
  templateFormats: ["md", "html", "png", "jpg", "jpeg", "gif", "svg"],
  passthroughFileCopy: true
};
```

**Comment by chrisdmacrae** [comment]
This was an issue w/ Yarn, not eleventy.
