### ISSUE TITLE
JSTL files won't compile (circular reference)

### ISSUE THREAD

**Issue by DominoPivot** [11ty/eleventy#948]
**Describe the bug**

`.jstl` files won't compile at all. Eleventy complains about recursive reference in the template. This is true even when the jstl file is just the text `Hello World!` without any actual templating done.

I've been scratching my head to make sure this wasn't just me as I'm making my first 11ty site, then I realized even the sample site using JSTL doesn't work.

```
Problem writing Eleventy templates: (more in DEBUG output)
> ./index.jstl contains a circular reference (using collections) to its own templateContent.

`UsingCircularTemplateContentReferenceError` was thrown:
    UsingCircularTemplateContentReferenceError: ./index.jstl contains a circular reference (using collections) to its own templateContent.
        at TemplateMap.populateContentDataInMap (H:\eleventy-sample-jstl\node_modules\@11ty\eleventy\src\TemplateMap.js:382:17)
Wrote 0 files in 0.14 seconds (v0.10.0)
```

**To Reproduce**

1. Clone sample repository for JSTL templates at https://github.com/11ty/eleventy-sample-jstl
2. Delete `package.json` as it requires an old version of 11ty.
3. `npm init -y`
4. `npm install --save-dev @11ty/eleventy`
5. `npx @11ty/eleventy`

**Environment:**

- OS and Version: Windows 10 Pro 64bits
- Eleventy Version 0.10.0

**Comment by DominoPivot** [comment]
The bug doesn't occur for jstl files with `eleventyExcludeFromCollections: true`.

**Comment by jonathantneal** [comment]
I’m experiencing this bug as well using the sample. I was unable to resolve it by updating the dependency from `^0.5.4` to `^0.11.0`.

Here is the error from `0.11.0`:

```
npx eleventy
```

```
Problem writing Eleventy templates: (more in DEBUG output)
> ./index.jstl contains a circular reference (using collections) to its own templateContent.

`UsingCircularTemplateContentReferenceError` was thrown:
    UsingCircularTemplateContentReferenceError: ./index.jstl contains a circular reference (using collections) to its own templateContent.
        at TemplateMap.populateContentDataInMap (/path/to/eleventy-sample-jstl/node_modules/@11ty/eleventy/src/TemplateMap.js:384:17)
        at async TemplateMap.cache (/path/to/eleventy-sample-jstl/node_modules/@11ty/eleventy/src/TemplateMap.js:303:5)
        at async TemplateWriter._createTemplateMap (/path/to/eleventy-sample-jstl/node_modules/@11ty/eleventy/src/TemplateWriter.js:170:5)
        at async TemplateWriter.writeTemplates (/path/to/eleventy-sample-jstl/node_modules/@11ty/eleventy/src/TemplateWriter.js:203:5)
        at async TemplateWriter.write (/path/to/eleventy-sample-jstl/node_modules/@11ty/eleventy/src/TemplateWriter.js:254:25)
        at async Eleventy.write (/path/to/eleventy-sample-jstl/node_modules/@11ty/eleventy/src/Eleventy.js:741:13)
Wrote 0 files in 0.14 seconds (v0.11.0)
```

Here is the debug output from `0.11.0`, which does not seem to reveal the error:

```
DEBUG=true npx eleventy
```

```
Wrote 0 files in 0.14 seconds (v0.11.0)


Start time: (2020-06-19 21:36:14 UTC) [treshold=1%]
 #  module                                                                             time  %
 1  ./src/EleventyErrorHandler (node_module.../eleventy/src/EleventyErrorHandler.js)    6ms  ▇▇ 2%
 2  ./TemplatePath (node_modules/@11ty/eleventy/src/TemplatePath.js)                    4ms  ▇ 1%
 3  ./fs (node_modules/fs-extra/lib/fs/index.js)                                        5ms  ▇▇ 1%
 4  ./copy-sync (node_modules/fs-extra/lib/copy-sync/index.js)                          4ms  ▇ 1%
 5  ./json (node_modules/fs-extra/lib/json/index.js)                                    4ms  ▇ 1%
 6  fs-extra (node_modules/fs-extra/lib/index.js)                                      25ms  ▇▇▇▇▇▇ 7%
 7  braces (node_modules/fast-glob/node_modules/braces/index.js)                        4ms  ▇ 1%
 8  micromatch (node_modules/fast-glob/node_modules/micromatch/index.js)                8ms  ▇▇ 2%
 9  ./pattern (node_modules/fast-glob/out/utils/pattern.js)                            11ms  ▇▇▇ 3%
10  ../utils (node_modules/fast-glob/out/utils/index.js)                               13ms  ▇▇▇ 4%
11  ./managers/tasks (node_modules/fast-glob/out/managers/tasks.js)                    14ms  ▇▇▇▇ 4%
12  ../readers/async (node_modules/@nodelib/fs.walk/out/readers/async.js)               5ms  ▇▇ 1%
13  ./providers/async (node_modules/@nodelib/fs.walk/out/providers/async.js)            6ms  ▇▇ 2%
14  @nodelib/fs.walk (node_modules/@nodelib/fs.walk/out/index.js)                       7ms  ▇▇ 2%
15  ../readers/stream (node_modules/fast-glob/out/readers/stream.js)                   10ms  ▇▇▇ 3%
16  ./provider (node_modules/fast-glob/out/providers/provider.js)                       4ms  ▇ 1%
17  ./providers/async (node_modules/fast-glob/out/providers/async.js)                  14ms  ▇▇▇▇ 4%
18  fast-glob (node_modules/fast-glob/out/index.js)                                    29ms  ▇▇▇▇▇▇▇ 8%
19  ./_getNative (node_modules/lodash/_getNative.js)                                    4ms  ▇ 1%
20  ./_defineProperty (node_modules/lodash/_defineProperty.js)                          4ms  ▇ 1%
21  ./_baseAssignValue (node_modules/lodash/_baseAssignValue.js)                        5ms  ▇▇ 1%
22  ./_assignValue (node_modules/lodash/_assignValue.js)                                5ms  ▇▇ 1%
23  ./_mapCacheClear (node_modules/lodash/_mapCacheClear.js)                            4ms  ▇ 1%
24  ./_MapCache (node_modules/lodash/_MapCache.js)                                      6ms  ▇▇ 2%
25  ./memoize (node_modules/lodash/memoize.js)                                          6ms  ▇▇ 2%
26  ./_memoizeCapped (node_modules/lodash/_memoizeCapped.js)                            6ms  ▇▇ 2%
27  ./_stringToPath (node_modules/lodash/_stringToPath.js)                              7ms  ▇▇ 2%
28  ./_castPath (node_modules/lodash/_castPath.js)                                     10ms  ▇▇▇ 3%
29  ./_baseSet (node_modules/lodash/_baseSet.js)                                       15ms  ▇▇▇▇ 4%
30  lodash/set (node_modules/lodash/set.js)                                            16ms  ▇▇▇▇ 4%
31  ./_baseUniq (node_modules/lodash/_baseUniq.js)                                      4ms  ▇ 1%
32  lodash/uniq (node_modules/lodash/uniq.js)                                           4ms  ▇ 1%
33  ./_baseMergeDeep (node_modules/lodash/_baseMergeDeep.js)                            8ms  ▇▇ 2%
34  ./_baseMerge (node_modules/lodash/_baseMerge.js)                                   11ms  ▇▇▇ 3%
35  lodash/merge (node_modules/lodash/merge.js)                                        14ms  ▇▇▇▇ 4%
36  semver (node_modules/semver/index.js)                                              18ms  ▇▇▇▇ 5%
37  luxon (node_modules/luxon/build/node/luxon.js)                                      5ms  ▇▇ 1%
38  ./UserConfig (node_modules/@11ty/eleventy/src/UserConfig.js)                       27ms  ▇▇▇▇▇▇ 8%
39  ./EleventyConfig (node_modules/@11ty/eleventy/src/EleventyConfig.js)               27ms  ▇▇▇▇▇▇ 8%
40  ./TemplateConfig (node_modules/@11ty/eleventy/src/TemplateConfig.js)               43ms  ▇▇▇▇▇▇▇▇▇▇ 12%
41  ./Config (node_modules/@11ty/eleventy/src/Config.js)                               49ms  ▇▇▇▇▇▇▇▇▇▇▇ 14%
42  ./TemplateEngineManager (node_modules/@...eleventy/src/TemplateEngineManager.js)   49ms  ▇▇▇▇▇▇▇▇▇▇▇ 14%
43  ./EleventyExtensionMap (node_modules/@1.../eleventy/src/EleventyExtensionMap.js)   50ms  ▇▇▇▇▇▇▇▇▇▇▇▇ 14%
44  ./TemplateRender (node_modules/@11ty/eleventy/src/TemplateRender.js)               50ms  ▇▇▇▇▇▇▇▇▇▇▇▇ 14%
45  ./TemplateData (node_modules/@11ty/eleventy/src/TemplateData.js)                  130ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 37%
46  ./json (node_modules/js-yaml/lib/js-yaml/schema/json.js)                            5ms  ▇▇ 1%
47  ./core (node_modules/js-yaml/lib/js-yaml/schema/core.js)                            5ms  ▇▇ 1%
48  ./schema/default_safe (node_modules/js-...ml/lib/js-yaml/schema/default_safe.js)    8ms  ▇▇ 2%
49  esprima (node_modules/esprima/dist/esprima.js)                                      8ms  ▇▇ 2%
50  ../type/js/function (node_modules/js-yaml/lib/js-yaml/type/js/function.js)          8ms  ▇▇ 2%
51  ./schema/default_full (node_modules/js-...ml/lib/js-yaml/schema/default_full.js)   10ms  ▇▇▇ 3%
52  ./js-yaml/loader (node_modules/js-yaml/lib/js-yaml/loader.js)                      21ms  ▇▇▇▇▇ 6%
53  ./lib/js-yaml.js (node_modules/js-yaml/lib/js-yaml.js)                             23ms  ▇▇▇▇▇▇ 6%
54  js-yaml (node_modules/js-yaml/index.js)                                            23ms  ▇▇▇▇▇▇ 6%
55  ./engines (node_modules/gray-matter/lib/engines.js)                                23ms  ▇▇▇▇▇▇ 6%
56  ./lib/defaults (node_modules/gray-matter/lib/defaults.js)                          24ms  ▇▇▇▇▇▇ 7%
57  gray-matter (node_modules/gray-matter/index.js)                                    29ms  ▇▇▇▇▇▇▇ 8%
58  ./TemplateContent (node_modules/@11ty/eleventy/src/TemplateContent.js)             30ms  ▇▇▇▇▇▇▇ 8%
59  ./Template (node_modules/@11ty/eleventy/src/Template.js)                           37ms  ▇▇▇▇▇▇▇▇▇ 10%
60  multimatch (node_modules/multimatch/index.js)                                       4ms  ▇ 1%
61  ./TemplateCollection (node_modules/@11ty/eleventy/src/TemplateCollection.js)        5ms  ▇▇ 1%
62  ./TemplateMap (node_modules/@11ty/eleventy/src/TemplateMap.js)                      6ms  ▇▇ 2%
63  glob (node_modules/glob/glob.js)                                                    6ms  ▇▇ 2%
64  globby (node_modules/globby/index.js)                                               8ms  ▇▇ 2%
65  del (node_modules/del/index.js)                                                    12ms  ▇▇▇ 3%
66  ./lib/copy (node_modules/recursive-copy/lib/copy.js)                               19ms  ▇▇▇▇▇ 5%
67  recursive-copy (node_modules/recursive-copy/index.js)                              19ms  ▇▇▇▇▇ 5%
68  ./TemplatePassthrough (node_modules/@11ty/eleventy/src/TemplatePassthrough.js)     19ms  ▇▇▇▇▇ 5%
69  ./TemplatePassthroughManager (node_modu...nty/src/TemplatePassthroughManager.js)   20ms  ▇▇▇▇▇ 6%
70  ./EleventyFiles (node_modules/@11ty/eleventy/src/EleventyFiles.js)                 20ms  ▇▇▇▇▇ 6%
71  ./TemplateWriter (node_modules/@11ty/eleventy/src/TemplateWriter.js)               64ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 18%
72  ./src/Eleventy (node_modules/@11ty/eleventy/src/Eleventy.js)                      202ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 57%
73  ./common/utils (node_modules/markdown-it/lib/common/utils.js)                       6ms  ▇▇ 2%
74  ./parser_block (node_modules/markdown-it/lib/parser_block.js)                       5ms  ▇▇ 1%
75  ./parser_inline (node_modules/markdown-it/lib/parser_inline.js)                     5ms  ▇▇ 1%
76  ./lib/ (node_modules/markdown-it/lib/index.js)                                     22ms  ▇▇▇▇▇ 6%
77  markdown-it (node_modules/markdown-it/index.js)                                    23ms  ▇▇▇▇▇▇ 6%
78  ./Engines/Markdown (node_modules/@11ty/eleventy/src/Engines/Markdown.js)           24ms  ▇▇▇▇▇▇ 7%
79  liquidjs (node_modules/liquidjs/dist/liquid.common.js)                              4ms  ▇ 1%
80  ./Engines/Liquid (node_modules/@11ty/eleventy/src/Engines/Liquid.js)                6ms  ▇▇ 2%
Total require(): 1147
Total time: 356ms
```

**Comment by wilddeer** [comment]
Wow, this is still broken. Any workarounds?

**Comment by DominoPivot** [comment]
None than I'm aware of. Seems like trying to support too many features was eleventy's downfall. The lack of followup on this issues convinced me to try Hugo instead, and I found it much simpler to use and much more stable.

**Comment by zachleat** [comment]
Sorry y’all, JSTL is going away in 1.0. It just didn’t make sense to keep it with the better `11ty.js` alternative.

See #1084.
