### ISSUE TITLE
Pagination, before example not working

### ISSUE THREAD

**Issue by cfjedimaster** [11ty/eleventy#954]
I copied the code from before callback example (https://www.11ty.dev/docs/pagination/#the-before-callback) and it does not work as is. I get the following:

```
Problem writing Eleventy templates: (more in DEBUG output)
> SyntaxError: Unexpected identifier

`SyntaxError` was thrown:
    SyntaxError: SyntaxError: Unexpected identifier
        at parse (/home/ray/.nvm/versions/node/v12.10.0/lib/node_modules/@11ty/eleventy/node_modules/gray-matter/lib/engines.js:48:13)
        at Object.parse (/home/ray/.nvm/versions/node/v12.10.0/lib/node_modules/@11ty/eleventy/node_modules/gray-matter/lib/engines.js:46:16)
        at module.exports (/home/ray/.nvm/versions/node/v12.10.0/lib/node_modules/@11ty/eleventy/node_modules/gray-matter/lib/parse.js:12:17)
        at parseMatter (/home/ray/.nvm/versions/node/v12.10.0/lib/node_modules/@11ty/eleventy/node_modules/gray-matter/index.js:109:17)
        at matter (/home/ray/.nvm/versions/node/v12.10.0/lib/node_modules/@11ty/eleventy/node_modules/gray-matter/index.js:50:10)
        at Template.read (/home/ray/.nvm/versions/node/v12.10.0/lib/node_modules/@11ty/eleventy/src/TemplateContent.js:75:16)
        at async Template.getFrontMatterData (/home/ray/.nvm/versions/node/v12.10.0/lib/node_modules/@11ty/eleventy/src/TemplateContent.js:129:7)
        at async Template.getData (/home/ray/.nvm/versions/node/v12.10.0/lib/node_modules/@11ty/eleventy/src/Template.js:212:29)
        at async Template.getTemplateMapEntries (/home/ray/.nvm/versions/node/v12.10.0/lib/node_modules/@11ty/eleventy/src/Template.js:681:16)
        at async TemplateMap.add (/home/ray/.nvm/versions/node/v12.10.0/lib/node_modules/@11ty/eleventy/src/TemplateMap.js:32:21)
```

debug info didn't help, but it was also quite overwhelming. I named my file `categories.liquid` if that matters.

**Comment by cfjedimaster** [comment]
Ok, looks to be stupid simple - add a comma after `data: "testdata"` and `size: 2`. My fault for not noticing, but the docs should fix it.

**Comment by pdehaan** [comment]
https://github.com/11ty/11ty-website/pull/328

Ah, you beat me to it, thanks!

**Comment by cfjedimaster** [comment]
I'm here to help. :) I forgot to mention the bug in the PR, sorry.

**Comment by zachleat** [comment]
Fixed by https://github.com/11ty/11ty-website/pull/328 thanks!!
