### ISSUE TITLE
Site variables like Hugo

### ISSUE THREAD

**Issue by plainspace** [11ty/eleventy#974]
Does Eleventy have the concept of site variables like Hugo? 

https://gohugo.io/variables/site/

**Comment by DirtyF** [comment]
You can mimick the `{{ site.variable }}` syntax, by using a data file named `{{ site.json }}`

**Comment by zachleat** [comment]
In addition to what @DirtyF said, Eleventy supplied data to your page is documented here https://www.11ty.dev/docs/data-eleventy-supplied/

**Comment by zachleat** [comment]
> This is an automated message to let you know that a helpful response was posted to your issue and for the health of the repository issue tracker the issue will be closed. This is to help alleviate issues hanging open waiting for a response from the original poster.

> If the response works to solve your problem—great! But if you’re still having problems, do not let the issue’s closing deter you if you have additional questions! Post another comment and I will reopen the issue. Thanks!

**Comment by plainspace** [comment]
I’ve tried this 3 different ways and still can’t get it working. Is there an example out there?

**Comment by pdehaan** [comment]
> I’ve tried this 3 different ways and still can’t get it working. Is there an example out there?

@plainspace How about this? https://github.com/pdehaan/11ty-global-data
That's just custom global variable stuff though, not all the config and taxonomy stuff that Hugo seems to have.

**Comment by zachleat** [comment]
Ah sorry @plainspace are you familiar with global data?

https://www.11ty.dev/docs/data-global/

Create a `_data/site.json`. The object will now be available in your templates as `site.SOMETHING_IN_THE_DATA_JSON_FILE`.

So if your `_data/site.json` file looks like `{"myKey": "hi"}` then you could use `{{ site.myKey }}` in a Nunjucks or Liquid template and it would output `hi`.

Does that help?

**Comment by plainspace** [comment]
It does help to clarify... and it's what I've been done. I must have something configured incorrectly because it is not working.
 
My `_data/site.json`:
```
[
  { "myKey": "hi" }
]
```
Console error:

```
[Browsersync] Reloading Browsers...
File changed: src/site/_data/site.json
Eleventy fatal watch error: (more in DEBUG output)
> Having trouble parsing data file ./src/site/_data/site.json

`TemplateDataParseError` was thrown
> Unexpected token { in JSON at position 22
`SyntaxError` was thrown:
    SyntaxError: Unexpected token { in JSON at position 22
        at JSON.parse (<anonymous>)
        at TemplateData.getDataValue (/user/eleventy/node_modules/@11ty/eleventy/src/TemplateData.js:268:25)
        at async TemplateData.getAllGlobalData (/user/eleventy/node_modules/@11ty/eleventy/src/TemplateData.js:173:18)
        at async TemplateData.getData (/user/eleventy/node_modules/@11ty/eleventy/src/TemplateData.js:184:24)
        at async Eleventy.restart (/user/eleventy/node_modules/@11ty/eleventy/src/Eleventy.js:91:5)
        at async Eleventy._watch (/user/eleventy/node_modules/@11ty/eleventy/src/Eleventy.js:263:5)
        at async Eleventy.watchRun (/user/eleventy/node_modules/@11ty/eleventy/src/Eleventy.js:382:9)
        at async FSWatcher.<anonymous> (/user/eleventy/node_modules/@11ty/eleventy/src/Eleventy.js:391:7)
```

**Comment by pdehaan** [comment]
Worked for me in https://github.com/pdehaan/11ty-974/tree/master/src/site

But I regularly get dev errors when developing and using the `--serve` flag. Are you seeing the error 100% of the time, or only during development while the browsers are refreshing and data might not be in a 100% valid state?

**Comment by plainspace** [comment]
It is never working so I can't say...

**Comment by plainspace** [comment]
Implementing like your example kind of works but... I want to grab one variable and use it in a specific link, not run through the loop.

More like this: 

`<a href="{{ site.myKey }}" target="_blank">Link</a>`
